'use strict';

// English strings. Same keys, same order and same {placeholders} as es.js.

module.exports = Object.freeze({
  ...require('./year.en'),
  ...require('./year-ui.en'),
  ...require('./workshop.en'),

  // Interface
  'ui.title': 'P&L QUEST',
  'ui.subtitle': 'A quest through the income statement',
  'ui.press': 'Press Enter or tap the screen',
  'ui.language': 'Language',
  'lang.es': 'Español',
  'lang.en': 'English',
  'ui.best': 'Best: {n} of 3 stars',
  'ui.fictional': '100% fictional data',
  'ui.btn.start': 'Enter: start',
  'ui.btn.pick': 'Enter: pick',
  'ui.btn.next': 'Enter: next',
  'ui.btn.close': 'Enter: close',
  'ui.btn.again': 'Enter: again',
  'ui.btn.note': 'N note',
  'ui.btn.sound': 'M sound',
  'ui.btn.lang': 'L ES/EN',
  'ui.calm.on': 'Calm effects (E)',
  'ui.calm.off': 'Full effects (E)',
  'ui.floor': 'FLOOR {n}',
  'ui.stage': 'Floor {f} - Turn {n}/3',
  'ui.prompt': 'Which card do you play?',
  'ui.appears': '{boss} appears!',
  'ui.played': 'You played: {card}',
  'ui.oiChange': 'OI {from}% > {to}%  ({delta} pp)',
  'ui.noChange': 'OI does not change.',
  'ui.shift': 'The cost does not vanish: it returns on floor {n}.',
  'ui.scanDone': "You measured the client's savings. A new card is ready.",
  'ui.measuredDone': 'Value measured! Your price cards improve.',
  'ui.entryDeferred': 'The bill from earlier choices arrives: OI {delta} pp',
  'ui.entryShock': 'Floor shock: OI {delta} pp',
  'ui.tierUp': 'The plant is modernizing!',
  'ui.tierDown': 'The plant is deteriorating...',
  'ui.floorDone': 'Floor {n} complete',
  'ui.floorImpact': 'OI impact: {delta} pp',
  'ui.room': 'CONTROL ROOM',
  'ui.saved': 'Game saved',
  'ui.gameOver': 'GAME OVER',
  'ui.autopsy': 'AUTOPSY',
  'ui.autopsyBiggest': 'The line that bit you hardest: {line}.',
  'ui.autopsyWorst': 'Floor {floor}, turn {turn}: you played {chosen}. You could have played {best}.',
  'ui.retryRoom': 'You restart from the control room.',
  'ui.retryStart': 'You restart from floor 1.',
  'ui.result': 'RESULT',
  'ui.finalOi': 'Final OI: {n}%',
  'ui.stars': '{n} of 3 stars',
  'ui.star1': '1: you survive',
  'ui.star2': '2: OI above the minimum ({n}%)',
  'ui.star3': '3: goal ({n}%) with Scan used',
  'ui.intro1': 'You run a plant that sells to mining. Your life bar is OI: operating income as a % of net sales.',
  'ui.intro2': "Each floor is a P&L line that wants to bite your margin. Play cards, measure the client's value and keep the plant standing.",
  'ui.oiBar': 'Projected OI',
  'ui.goalMark': 'goal {n}',
  'chip.price': 'Price',
  'chip.volume': 'Volume',
  'chip.unlock': 'Unlocks',
  'chip.shift': 'Other floor',
  'lesson.measured': "You measured the client's savings: you had a card to negotiate.",
  'lesson.unmeasured': 'You did not measure the savings: what is not measured is not negotiated.',
  'lesson.shifted': 'The free freight came back as freight on floor 4.',
  'lesson.cts': 'Contribution margin is not Gross Profit: freight and direct charges sit between them.',
  'lesson.fixed': 'Fixed cost weighs more when volume falls.',

  // P&L lines
  'line.sales': 'Sales',
  'line.incentives': 'Incentives',
  'line.cost': 'Cost',
  'line.cm': 'Contribution margin',
  'line.freight': 'Freight',
  'line.direct': 'Direct charges',
  'line.delivery': 'Freight and direct chg',
  'line.gp': 'Gross Profit',
  'line.sga': 'SG&A',
  'line.oi': 'OI',
  'line.short.sales': 'Sales',
  'line.short.incentives': 'Incentives',
  'line.short.net': 'Net sales',
  'line.short.cost': 'Cost',
  'line.short.cm': 'Contrib. mgn',
  'line.short.freight': 'Freight',
  'line.short.direct': 'Direct Chg',
  'line.short.gp': 'Gross Profit',
  'line.short.sga': 'SG&A',
  'line.short.oi': 'OI',
  'stmt.unit': 'US$ M',
  'stmt.col.real': 'Actual',
  'stmt.col.plan': 'Plan',
  'stmt.col.var': 'Var.',
  'stmt.ratio': 'Ratio %',

  // Areas of the company
  'area.sales': 'Sales',
  'area.procurement': 'Procurement',
  'area.ops': 'Operations',
  'area.finance': 'Finance',
  'area.mgmt': 'Management',
  'area.tag.sales': 'SALES',
  'area.tag.procurement': 'PROCURE',
  'area.tag.ops': 'OPS',
  'area.tag.finance': 'FINANCE',
  'area.tag.mgmt': 'MGMT',

  // Factory states
  'tier.collapse': 'Collapse',
  'tier.edge': 'On the brink',
  'tier.worn': 'Run-down plant',
  'tier.normal': 'Normal plant',
  'tier.modern': 'Modern plant',
  'tier.hightech': 'Cutting-edge plant',

  // Floors, bosses and what the boss says each turn
  'floor.1.name': 'SALES',
  'floor.1.place': 'Order desk',
  'floor.2.name': 'INCENTIVES',
  'floor.2.place': 'Negotiation room',
  'floor.3.name': 'COST',
  'floor.3.place': 'Warehouse and line',
  'floor.4.name': 'FREIGHT & DIRECT CHG',
  'floor.4.place': 'Dispatch and field',
  'floor.5.name': 'SG&A',
  'floor.5.place': 'Offices',
  'floor.6.name': 'OI',
  'floor.6.place': 'Boardroom',
  'boss.order': 'THE ORDER',
  'boss.rebate': 'THE REBATE',
  'boss.cost': 'THE COST',
  'boss.truck': 'THE TRUCK',
  'boss.fixed': 'FIXED COST',
  'floor.1.t1': "The mine's annual order arrives. How do you enter the room?",
  'floor.1.t2': 'The client wants more volume for less.',
  'floor.1.t3': 'Last tweak before the order is signed.',
  'floor.2.t1': 'The mine demands a 3% rebate to renew.',
  'floor.2.t2': 'They push back: the competition offers more.',
  'floor.2.t3': 'They want to close today. The clock is ticking.',
  'floor.3.t1': 'The supplier raises input cost 8% and sale price will not move by itself.',
  'floor.3.t2': 'Sales cannot see cost. Procurement cannot see price.',
  'floor.3.t3': 'The quarter is closing. What do you do about cost?',
  'floor.4.t1': 'The client asks for weekly visits and loaned equipment.',
  'floor.4.t2': 'The field team is stretched thin.',
  'floor.4.t3': 'Month-end: what gets billed and what is given away?',
  'floor.5.t1': 'Sales fall 8% and fixed cost stays put.',
  'floor.5.t2': 'Management asks to trim the budget.',
  'floor.5.t3': 'Last quarter of the year.',

  // Technical notes (N key)
  'note.1.title': 'Sales',
  'note.1.body': 'The starting point: price x volume. Price falls almost entirely to OI; volume only adds its margin. Sales controls it.',
  'note.2.title': 'Incentives (rebates)',
  'note.2.body': 'Rebates and discounts deducted from sales. Sales decides with Finance. A concession without measured backing is paid in margin.',
  'note.3.title': 'Cost (replacement cost)',
  'note.3.body': 'Replacement cost of the product. Procurement and suppliers move it. If it rises and price does not, contribution margin shrinks.',
  'note.4.title': 'Freight and direct charges',
  'note.4.body': 'Freight (getting the product to the client) and Direct Charges (like loaned gear). Operations controls them, but Sales promises trigger them. They sit between contribution margin and Gross Profit.',
  'note.5.title': 'SG&A',
  'note.5.body': 'Selling and administrative expense. Mostly fixed: if volume falls, it weighs more on every sale. Management controls it.',
  'note.6.title': 'OI (Operating Income)',
  'note.6.body': 'What is left after every line: Gross Profit minus SG&A. It is measured as a % of net sales: OI 15% is 15 for every 100 of net sales. Interest and taxes are outside the game.',
  'room.cm.title': 'Contribution margin',
  'room.cm.body': 'Sales - Incentives - Cost. It is what you see before serving the client.',
  'room.gp.title': 'Gross Profit',
  'room.gp.body': 'Contribution margin minus Freight and Direct charges. The gap between them is what it costs to serve the client.',

  // Cards: floor 1
  'card.raise.name': 'Raise price 1.5%',
  'card.raise.desc': 'More margin on every sale, but a client may leave.',
  'card.listPrice.name': 'Hold list price',
  'card.listPrice.desc': 'You change nothing. Safe, but no gain.',
  'card.discount.name': 'Cut price 3%',
  'card.discount.desc': 'You sell more, but each sale leaves less margin.',
  'card.chase.name': 'Take every order',
  'card.chase.desc': 'More volume, but every small shipment costs more.',
  'card.bundle.name': 'Service bundle',
  'card.bundle.desc': 'You sell more value per order; service costs a bit.',
  'card.forecast.name': 'Plan with Ops',
  'card.forecast.desc': 'Operations sees what is coming and avoids rush shipments.',

  // Cards: floor 2
  'card.give3.name': 'Give the 3%',
  'card.give3.desc': 'You close today, but set a precedent.',
  'card.hold.name': 'Hold the price',
  'card.hold.desc': 'No rebate. The client may buy less.',
  'card.freight.name': 'Free freight',
  'card.freight.desc': 'No rebate today. Who pays the freight?',
  'card.scan.name': 'Scan: find savings',
  'card.scan.desc': "You spend the turn measuring the client's savings.",
  'card.measured.name': 'Documented savings',
  'card.measured.desc': 'US$400k a year in water. You trade the rebate for a 3-year contract.',
  'card.giveHalf.name': 'Concede 1.5%',
  'card.giveHalf.desc': 'Halfway: you lose margin without an argument.',
  'card.walkAway.name': 'Walk away',
  'card.walkAway.desc': 'You lose the client: volume collapses.',
  'card.contract3y.name': '3-year contract',
  'card.contract3y.desc': 'With savings on the table, you sign with an annual price step.',

  // Cards: floor 3
  'card.absorb.name': 'Absorb the hike',
  'card.absorb.desc': 'You do nothing: the hike eats your margin.',
  'card.passLight.name': 'Pass it on',
  'card.passLight.desc': 'The client sees only the hike: some volume leaves.',
  'card.passValue.name': 'Backed price rise',
  'card.passValue.desc': 'You show the measured savings and the client accepts.',
  'card.renegotiate.name': 'Renegotiate supply',
  'card.renegotiate.desc': 'Procurement wins a partial volume discount.',
  'card.swapInput.name': 'Swap the input',
  'card.swapInput.desc': 'Cost drops, but service must validate the formula.',
  'card.stockUp.name': 'Stock up early',
  'card.stockUp.desc': 'Cost drops, but cash sits in the warehouse.',
  'card.hedge.name': 'Long-term contract',
  'card.hedge.desc': 'You lock the input price for 12 months.',

  // Cards: floor 4
  'card.acceptAll.name': 'Accept it all',
  'card.acceptAll.desc': 'Weekly visits and loaned gear: service eats the margin.',
  'card.routeOpt.name': 'Optimize routes',
  'card.routeOpt.desc': 'Fewer trips, fuller trucks.',
  'card.remote.name': 'Remote monitoring',
  'card.remote.desc': 'Visits only when needed.',
  'card.fee.name': 'Charge for service',
  'card.fee.desc': 'With savings measured, the client agrees to pay a fee.',
  'card.comodatoReview.name': 'Review loaned gear',
  'card.comodatoReview.desc': 'Minimum term for loaned gear: less idle depreciation.',
  'card.ignore.name': 'Cheer the margin',
  'card.ignore.desc': 'Contribution margin looks fine. The service cost is still there.',
  'card.billExtras.name': 'Bill the extras',
  'card.billExtras.desc': 'You charge for out-of-contract visits.',

  // Cards: floor 5
  'card.freeze.name': 'Hiring freeze',
  'card.freeze.desc': 'No new hires: fixed cost drops a bit.',
  'card.trimTravel.name': 'Trim travel',
  'card.trimTravel.desc': 'Fewer trips and outside consultants.',
  'card.restructure.name': 'Restructure',
  'card.restructure.desc': 'Big savings, but customer service suffers.',
  'card.hireGrowth.name': 'Hire to grow',
  'card.hireGrowth.desc': 'More people today; volume comes later, if it does.',
  'card.keep.name': 'Keep it all',
  'card.keep.desc': 'Fixed cost stays. So does the pressure on OI.',
  'card.priceSmall.name': 'Raise small accts',
  'card.priceSmall.desc': 'You adjust price on small accounts only.',
});
