'use strict';

// Spanish strings. Keep both languages in the same order and with the same {placeholders};
// tests/content.test.js checks parity, character support and line lengths.

module.exports = Object.freeze({
  ...require('./year.es'),
  ...require('./year-ui.es'),
  ...require('./workshop.es'),

  // Interface
  'ui.title': 'P&L QUEST',
  'ui.subtitle': 'Una aventura por el estado de resultados',
  'ui.press': 'Presiona Enter o toca la pantalla',
  'ui.language': 'Idioma',
  'lang.es': 'Español',
  'lang.en': 'English',
  'ui.best': 'Mejor: {n} de 3 estrellas',
  'ui.fictional': 'Datos 100% ficticios',
  'ui.btn.start': 'Enter: empezar',
  'ui.btn.pick': 'Enter: elegir',
  'ui.btn.next': 'Enter: seguir',
  'ui.btn.close': 'Enter: cerrar',
  'ui.btn.again': 'Enter: otra vez',
  'ui.btn.note': 'N nota',
  'ui.btn.sound': 'M sonido',
  'ui.btn.lang': 'L ES/EN',
  'ui.calm.on': 'Efectos suaves (E)',
  'ui.calm.off': 'Efectos completos (E)',
  'ui.floor': 'PISO {n}',
  'ui.stage': 'Piso {f} - Turno {n}/3',
  'ui.prompt': '¿Qué carta juegas?',
  'ui.appears': '¡Aparece {boss}!',
  'ui.played': 'Jugaste: {card}',
  'ui.oiChange': 'OI {from}% > {to}%  ({delta} pp)',
  'ui.noChange': 'El OI no cambia.',
  'ui.shift': 'El costo no desaparece: reaparece en el piso {n}.',
  'ui.scanDone': 'Mediste el ahorro del cliente. Hay una carta nueva.',
  'ui.measuredDone': '¡Valor medido! Mejoran tus cartas de precio.',
  'ui.entryDeferred': 'Llega la factura de decisiones anteriores: OI {delta} pp',
  'ui.entryShock': 'Golpe del piso: OI {delta} pp',
  'ui.tierUp': '¡La fábrica se moderniza!',
  'ui.tierDown': 'La fábrica se deteriora...',
  'ui.floorDone': 'Piso {n} completo',
  'ui.floorImpact': 'Impacto en OI: {delta} pp',
  'ui.room': 'SALA DE CONTROL',
  'ui.saved': 'Partida guardada',
  'ui.gameOver': 'GAME OVER',
  'ui.autopsy': 'AUTOPSIA',
  'ui.autopsyBiggest': 'La línea que más te mordió: {line}.',
  'ui.autopsyWorst': 'Piso {floor}, turno {turn}: jugaste {chosen}. Pudiste jugar {best}.',
  'ui.retryRoom': 'Reinicias desde la sala de control.',
  'ui.retryStart': 'Reinicias desde el primer piso.',
  'ui.result': 'RESULTADO',
  'ui.finalOi': 'OI final: {n}%',
  'ui.stars': '{n} de 3 estrellas',
  'ui.star1': '1: llegas con vida',
  'ui.star2': '2: OI sobre el mínimo ({n}%)',
  'ui.star3': '3: meta ({n}%) con Scan usado',
  'ui.intro1': 'Diriges una fábrica que le vende a la minería. Tu barra de vida es el OI: la utilidad operacional como % de las ventas netas.',
  'ui.intro2': 'Cada piso es una línea del P&L y quiere morder tu margen. Juega cartas, mide el valor del cliente y mantén la fábrica en pie.',
  'ui.oiBar': 'OI proyectado',
  'ui.goalMark': 'meta {n}',
  'chip.price': 'Precio',
  'chip.volume': 'Volumen',
  'chip.unlock': 'Desbloquea',
  'chip.shift': 'Otro piso',
  'lesson.measured': 'Mediste el ahorro del cliente: tuviste carta para negociar.',
  'lesson.unmeasured': 'No mediste el ahorro: lo que no se mide, no se negocia.',
  'lesson.shifted': 'El flete incluido reapareció como flete en el piso 4.',
  'lesson.cts': 'El margen de contribución no es el Gross Profit: los separan el flete y los Direct Charges.',
  'lesson.fixed': 'El gasto fijo pesa más cuando cae el volumen.',

  // P&L lines
  'line.sales': 'Ventas',
  'line.incentives': 'Incentivos',
  'line.cost': 'Costo',
  'line.cm': 'Margen de contribución',
  'line.freight': 'Flete',
  'line.direct': 'Direct charges',
  'line.delivery': 'Flete y Direct Chg',
  'line.gp': 'Gross Profit',
  'line.sga': 'SG&A',
  'line.oi': 'OI',
  'line.short.sales': 'Ventas',
  'line.short.incentives': 'Incentivos',
  'line.short.net': 'Ventas netas',
  'line.short.cost': 'Costo',
  'line.short.cm': 'M. contrib.',
  'line.short.freight': 'Flete',
  'line.short.direct': 'Direct Chg',
  'line.short.gp': 'Gross Profit',
  'line.short.sga': 'SG&A',
  'line.short.oi': 'OI',
  'stmt.unit': 'US$ M',
  'stmt.col.real': 'Real',
  'stmt.col.plan': 'Plan',
  'stmt.col.var': 'Var.',
  'stmt.ratio': 'Ratio %',

  // Areas of the company
  'area.sales': 'Comercial',
  'area.procurement': 'Compras',
  'area.ops': 'Operaciones',
  'area.finance': 'Finanzas',
  'area.mgmt': 'Gerencia',
  'area.tag.sales': 'COMERCIAL',
  'area.tag.procurement': 'COMPRAS',
  'area.tag.ops': 'OPERAC.',
  'area.tag.finance': 'FINANZAS',
  'area.tag.mgmt': 'GERENCIA',

  // Factory states
  'tier.collapse': 'Colapso',
  'tier.edge': 'Al borde del colapso',
  'tier.worn': 'Fábrica deteriorada',
  'tier.normal': 'Fábrica normal',
  'tier.modern': 'Fábrica moderna',
  'tier.hightech': 'Fábrica de punta',

  // Floors, bosses and what the boss says each turn
  'floor.1.name': 'VENTAS',
  'floor.1.place': 'Recepción de pedidos',
  'floor.2.name': 'INCENTIVOS',
  'floor.2.place': 'Sala de negociación',
  'floor.3.name': 'COSTO',
  'floor.3.place': 'Almacén y línea',
  'floor.4.name': 'FLETE Y DIRECT CHG',
  'floor.4.place': 'Despacho y terreno',
  'floor.5.name': 'SG&A',
  'floor.5.place': 'Oficinas',
  'floor.6.name': 'OI',
  'floor.6.place': 'Sala de directorio',
  'boss.order': 'EL PEDIDO',
  'boss.rebate': 'EL REBATE',
  'boss.cost': 'EL COSTO',
  'boss.truck': 'EL CAMIÓN',
  'boss.fixed': 'EL GASTO FIJO',
  'floor.1.t1': 'Llega el pedido anual de la minera. ¿Cómo entras a la mesa?',
  'floor.1.t2': 'El cliente pide más volumen por menos.',
  'floor.1.t3': 'Último ajuste antes de firmar el pedido.',
  'floor.2.t1': 'La minera exige un rebate de 3% para renovar.',
  'floor.2.t2': 'Insisten: la competencia ofrece más.',
  'floor.2.t3': 'Quieren cerrar hoy. El reloj corre.',
  'floor.3.t1': 'El proveedor sube el insumo 8% y el precio de venta no se mueve solo.',
  'floor.3.t2': 'Comercial no ve el costo. Compras no ve el precio.',
  'floor.3.t3': 'Cierra el trimestre. ¿Qué haces con el costo?',
  'floor.4.t1': 'El cliente pide visitas semanales y equipo en comodato.',
  'floor.4.t2': 'El equipo en terreno ya no da abasto.',
  'floor.4.t3': 'Cierre de mes: ¿qué se factura y qué se regala?',
  'floor.5.t1': 'Las ventas caen 8% y el gasto fijo sigue igual.',
  'floor.5.t2': 'Gerencia pide ajustar el presupuesto.',
  'floor.5.t3': 'Último trimestre del año.',

  // Technical notes (N key)
  'note.1.title': 'Ventas (Sales)',
  'note.1.body': 'Es el punto de partida: precio x volumen. El precio cae casi entero al OI; el volumen solo aporta su margen. Lo controla Comercial.',
  'note.2.title': 'Incentivos (rebates)',
  'note.2.body': 'Rebates y descuentos que se restan de la venta. Los decide Comercial con Finanzas. Una concesión sin respaldo medido se paga en margen.',
  'note.3.title': 'Costo (replacement cost)',
  'note.3.body': 'Costo de reposición del producto. Lo mueven Compras y los proveedores. Si sube y el precio no, el margen de contribución se achica.',
  'note.4.title': 'Flete y Direct Charges',
  'note.4.body': 'Flete (llevar el producto al cliente) y Direct Charges (como el comodato). Los controla Operaciones, pero los disparan las promesas de Comercial. Van entre el margen de contribución y el Gross Profit.',
  'note.5.title': 'SG&A',
  'note.5.body': 'Gasto de ventas y administración. Es mayormente fijo: si el volumen cae, pesa más sobre cada venta. Lo controla Gerencia.',
  'note.6.title': 'OI (Operating Income)',
  'note.6.body': 'Lo que queda tras todas las líneas: Gross Profit menos SG&A. Se mide como % de las ventas netas: OI 15% son 15 por cada 100 de ventas netas. Intereses e impuestos quedan fuera del juego.',
  'room.cm.title': 'Margen de contribución',
  'room.cm.body': 'Ventas - Incentivos - Costo. Es lo que ves antes de servir al cliente.',
  'room.gp.title': 'Gross Profit',
  'room.gp.body': 'Margen de contribución menos Flete y Direct Charges. La diferencia entre ambos es lo que cuesta atender al cliente.',

  // Cards: floor 1
  'card.raise.name': 'Subir precio 1,5%',
  'card.raise.desc': 'Más margen en cada venta, pero algún cliente se va.',
  'card.listPrice.name': 'Mantener lista',
  'card.listPrice.desc': 'No tocas nada. Seguro, pero sin mejora.',
  'card.discount.name': 'Rebajar precio 3%',
  'card.discount.desc': 'Vendes más, pero cada venta deja menos margen.',
  'card.chase.name': 'Aceptar todo pedido',
  'card.chase.desc': 'Más volumen, pero cada despacho chico cuesta más.',
  'card.bundle.name': 'Paquete + servicio',
  'card.bundle.desc': 'Vendes más valor por pedido; el servicio cuesta algo.',
  'card.forecast.name': 'Planificar con Ops',
  'card.forecast.desc': 'Operaciones sabe qué viene y evita despachos de urgencia.',

  // Cards: floor 2
  'card.give3.name': 'Dar el 3%',
  'card.give3.desc': 'Cierras hoy, pero sientas precedente.',
  'card.hold.name': 'Mantener precio',
  'card.hold.desc': 'Sin rebate. El cliente podría comprar menos.',
  'card.freight.name': 'Flete incluido',
  'card.freight.desc': 'Hoy no hay rebate. ¿Quién paga el flete?',
  'card.scan.name': 'Scan: medir ahorro',
  'card.scan.desc': 'Gastas el turno midiendo cuánto ahorra el cliente.',
  'card.measured.name': 'Ahorro documentado',
  'card.measured.desc': 'US$400 mil al año en agua. Cambias el rebate por un contrato a 3 años.',
  'card.giveHalf.name': 'Ceder 1,5%',
  'card.giveHalf.desc': 'Medio camino: pierdes margen sin tener un argumento.',
  'card.walkAway.name': 'Dejar la mesa',
  'card.walkAway.desc': 'Pierdes al cliente: el volumen se cae.',
  'card.contract3y.name': 'Contrato a 3 años',
  'card.contract3y.desc': 'Con el ahorro a la vista, firmas con ajuste anual de precio.',

  // Cards: floor 3
  'card.absorb.name': 'Absorber el alza',
  'card.absorb.desc': 'No haces nada: el alza se come tu margen.',
  'card.passLight.name': 'Subir el precio',
  'card.passLight.desc': 'El cliente ve solo el alza: algo de volumen se va.',
  'card.passValue.name': 'Alza con respaldo',
  'card.passValue.desc': 'Muestras el ahorro medido y el cliente acepta el alza.',
  'card.renegotiate.name': 'Renegociar compra',
  'card.renegotiate.desc': 'Compras logra un descuento parcial por volumen.',
  'card.swapInput.name': 'Sustituir insumo',
  'card.swapInput.desc': 'Baja el costo, pero el servicio debe validar la fórmula.',
  'card.stockUp.name': 'Comprar stock antes',
  'card.stockUp.desc': 'Baja el costo, pero la caja queda en bodega.',
  'card.hedge.name': 'Contrato largo',
  'card.hedge.desc': 'Fijas el precio del insumo por 12 meses.',

  // Cards: floor 4
  'card.acceptAll.name': 'Aceptar todo',
  'card.acceptAll.desc': 'Visitas semanales y comodato: el servicio se come el margen.',
  'card.routeOpt.name': 'Optimizar rutas',
  'card.routeOpt.desc': 'Menos despachos, más carga por camión.',
  'card.remote.name': 'Monitoreo remoto',
  'card.remote.desc': 'Visitas solo cuando hacen falta.',
  'card.fee.name': 'Cobrar el servicio',
  'card.fee.desc': 'Con el ahorro medido, el cliente acepta pagar un fee.',
  'card.comodatoReview.name': 'Revisar comodato',
  'card.comodatoReview.desc': 'Plazo mínimo para el equipo en comodato: menos depreciación sin uso.',
  'card.ignore.name': 'Celebrar el margen',
  'card.ignore.desc': 'El margen de contribución se ve bien. El servicio sigue ahí.',
  'card.billExtras.name': 'Facturar extras',
  'card.billExtras.desc': 'Cobras las visitas fuera de contrato.',

  // Cards: floor 5
  'card.freeze.name': 'Congelar dotación',
  'card.freeze.desc': 'Nadie nuevo entra: el gasto fijo baja un poco.',
  'card.trimTravel.name': 'Recortar viajes',
  'card.trimTravel.desc': 'Menos viajes y consultores externos.',
  'card.restructure.name': 'Reestructurar',
  'card.restructure.desc': 'Gran ahorro, pero el servicio al cliente se resiente.',
  'card.hireGrowth.name': 'Contratar y crecer',
  'card.hireGrowth.desc': 'Más gente hoy; el volumen llega después, si llega.',
  'card.keep.name': 'Mantener todo',
  'card.keep.desc': 'El gasto fijo no se mueve. Tampoco la presión sobre el OI.',
  'card.priceSmall.name': 'Subir precio chicos',
  'card.priceSmall.desc': 'Ajustas precio solo en clientes pequeños.',
});
