'use strict';

// Year mode, English. Same rows, same order and same answer order as year.es.js.

const ANSWERS = ['smart', 'temp', 'plac', 'ign'];

const ROWS = [
  ['m01c', 'Annual renewal', 'A hotel chain, 18% of your sales, asks for a 3% rebate to renew the contract.',
    ['2-year contract', 'You offer a 1% rebate rising to 2% above plan if they sign for 2 years.'],
    ['Accept and offset', 'You accept the 3% and offset it with a 2% rise on their other products.'],
    ['Give the 3%', 'You concede the 3% on the contract and seal the renewal on the spot.'],
    ['Ask for more time', 'You ask a month to study the offer; the contract expires in 20 days.']],
  ['m01p', 'Low inventory', 'Key inputs cover 3 weeks and big orders arrive in January.',
    ['Staggered purchase', 'You buy in 2 lots, the second 20 days out, and flag which orders are firm.'],
    ['Run at the limit', 'You ask the plant for 110% capacity in January instead of buying dear.'],
    ['Bulk purchase', 'You buy 3 months of inputs at spot price and cover any demand.'],
    ['Delay the purchase', 'You postpone buying to the inventory review at cycle end.']],
  ['m01e', 'Budget and the dollar', 'The dollar is 7% above budget and 40% of your inputs are imported.',
    ['Dollar adjustment', 'You agree in writing a dollar-linked adjustment and buy half forward.'],
    ['Price hike', 'You apply a 3% rise from tomorrow, existing contracts included.'],
    ['Absorb the hit', 'You leave prices and purchases as they are so the margin pays the 7% rise.'],
    ['Check at close', 'You analyze the dollar effect with the close numbers, 3 months out.']],
  ['m01s', 'Measure or push', "Corporate asks for 6% more volume; your clients' savings remain unmeasured.",
    ['Measure the savings', 'You document the water savings of 3 clients and negotiate with data later.'],
    ['Push volume', "You offer 4% off on extra orders to reach corporate's 6%."],
    ["Corporate's plan", "You apply corporate's volume plan strictly; measurement stays on hold."],
    ['Postpone both', 'You park both ideas for about 3 months, until the year gets going.']],

  ['m02c', 'Spec change', "A client, 12% of your sales, asks for a new spec with 2 weeks' notice.",
    ['Short trial', 'You run a 3-day trial and get the client to agree on a realistic date.'],
    ['Change the formula', 'You change the formula with warehouse stock and ship in 2 weeks.'],
    ['Accept the request', 'You accept the 2-week date and take on the extra plant cost.'],
    ['Answer on Monday', "You take it to Monday's sales meeting and answer within a week."]],
  ['m02p', 'Maintenance vs orders', 'Major maintenance is due (4 days stopped) and urgent orders are in.',
    ['Partial maintenance', 'You stop half the line in shifts for 8 days and split the urgent orders.'],
    ['Delay maintenance', "You move maintenance back 60 days and meet the month's orders."],
    ['Stop the line', 'You halt the line 4 days and tell the client to wait for shipments.'],
    ['Follow the calendar', 'You keep the original calendar; only 2 of 5 urgent orders get in.']],
  ['m02e', 'Coastal storm', 'A storm cuts the coastal road: 14 shipments are pending.',
    ['Alternate route', 'You take the inland route, 120 km longer, and prioritize what is critical.'],
    ['Ship anyway', 'You send the 14 trucks anyway and hit the dates despite the damaged road.'],
    ['4x4 trucks', 'You rent 14 4x4 trucks to arrive on time, at triple the freight rate.'],
    ['Closed road', 'You halt shipments while the road is shut, a week or so.']],
  ['m02s', 'Aggressive forecast', "Corporate asks to raise the yearly forecast 8% for Monday's meeting.",
    ['Ranged forecast', 'You give a base case and an upside of +8%, both explained.'],
    ['Inflate the number', 'You boost the forecast 8% to comply and adjust it in the next report.'],
    ['Accept the 8%', 'You gladly accept the +8% target and split it among the teams.'],
    ['Send it later', 'You email the forecast in 7 days, with last month already closed.']],

  ['m03c', 'Off-spec batch', 'A client complains about 40 tons that came out off specification.',
    ['Replace the batch', 'You replace the 40 tons today and share the analysis to avoid another claim.'],
    ['Point at freight', 'You blame transport for the damage and answer with half a replacement.'],
    ['10% discount', "You give 10% off the client's next purchase and close the claim today."],
    ['Formal claim', 'You wait for the formal claim, coming in 15 days, and then check the batch.']],
  ['m03p', 'Breakdown and shortage', 'A pump on line 2 fails and a key raw material has 5 days left.',
    ['Prioritize orders', 'You prioritize critical orders using what is left and buy the pump locally.'],
    ['Temporary patch', 'You make a temporary repair over 2 days and keep running at full load.'],
    ['Buy urgently', 'You buy the pump and the raw material within 24 hours and pay what they ask.'],
    ['Stop the line', 'You stop line 2 today for the supplier to deliver the spare parts.']],
  ['m03e', 'Health rule', 'A draft health rule is published and 3 large clients hold back purchases.',
    ['Map scenarios', "You go through each client's scenarios and give 2% off only to firm orders."],
    ['Pull sales forward', 'You give 5% off to whoever buys before the rule is final.'],
    ['Freeze prices', 'You freeze prices over 12 months to reassure the 3 clients.'],
    ['Rule comes first', 'You wait for the final text of the rule, in 2 months, before moving the plan.']],
  ['m03s', 'Water product', 'An opportunity: a water-saving program that 5 plants asked about.',
    ['Narrow pilot', 'You test it for 3 months at a friendly client and measure the effect.'],
    ['Launch to all', 'You offer it to the 5 plants now, with results you promise to deliver.'],
    ['Draft a proposal', 'You prepare a proposal with a budget and start when it is approved.'],
    ['Another chance', 'You prioritize the 4 projects of the year and park the program.']],

  ['m04c', 'Budget cut', 'A client cuts its input budget 10% and asks for lower prices.',
    ['Lower their usage', 'You adjust the dosing so it spends 10% less and bill a service for that saving.'],
    ['Change the mix', 'You cut the main product 5% and recover it with 5% more on services.'],
    ['Cut the contract', 'You cut the contract price 5% over 12 months, and the client stays.'],
    ['Keep the offer', 'You keep the offer on the same terms and the client decides within 30 days.']],
  ['m04p', 'Operator turnover', '2 of 9 key operators leave and the shifts are left short.',
    ['Relief plan', 'You train two juniors over 6 weeks of practice and reorganize the shifts.'],
    ['Overtime', 'You put the remaining team on double shifts during a quarter.'],
    ['Raise wages', "You raise every operator's pay on the shift 8% and nobody else leaves."],
    ['Vacant slots', 'You reassign tasks during the quarter and the 2 slots stay vacant.']],
  ['m04e', 'Green tax', 'A green tax kicks in and clients review all their input contracts.',
    ['Value-based deals', 'You propose contracts tied to the savings you create, not only volume.'],
    ['Squeeze the captive', 'You raise prices 6% for clients that have no other qualified supplier.'],
    ['Price break', 'You offer clients 3% off to keep them loyal before they ask.'],
    ['Handle requests', 'You handle renegotiation requests as they come in from clients.']],
  ['m04s', 'SG&A cut', 'Corporate asks to cut SG&A 5% starting next month.',
    ['Selective cut', 'You cut travel and consulting and protect client visits and measurement.'],
    ['Flat cut', "You cut every line 5% evenly to reach corporate's target."],
    ['Ask for exemption', "You ask for an exemption citing this half-year's commercial plan."],
    ['Schedule a review', 'You take the order to the budget meeting at quarter end.']],

  ['m05c', 'Free visits', 'A client (9% of your sales) asks for weekly visits at no extra charge.',
    ['Visits on demand', 'You offer remote monitoring so that visits happen only when the data asks.'],
    ['Junior technician', 'You accept weekly visits with a junior technician and cut spending 40%.'],
    ['Weekly visits', 'You grant 4 visits a month at your own cost and carry the service cost.'],
    ['Route to Ops', 'You pass the request to Operations and reply with a date in 20 days.']],
  ['m05p', 'Safety incident', 'A no-injury incident hits the plant and an audit arrives in 10 days.',
    ['Investigate cause', 'You stop the area 2 days with the team and correct the procedure.'],
    ['Close the file', 'You close the file as minor, given the 7 days a stoppage would cost.'],
    ['Stop the plant', 'You stop the plant 7 days and redo the procedures from zero.'],
    ['Keep working', 'You keep producing to fill 120 orders, since nobody was hurt.']],
  ['m05e', 'Tourism falls', 'Tourism drops 15% and hotels freeze non-essential purchases.',
    ['Volume rebate', 'You set a 1% rebate on the volumes above their minimum purchase.'],
    ['Charge active ones', 'You raise the price 4% for clients still buying and trim their rebate.'],
    ['General rebate', 'You give a 3% rebate to hotel clients so they stop cutting purchases.'],
    ['Watch the cycle', 'You keep prices and the usual rebate while waiting for tourism to rebound.']],
  ['m05s', 'Remote monitoring', 'You can invest in remote monitoring for 6 plants with monthly visits.',
    ['Invest in stages', 'You install at the 2 biggest plants and track visit savings for 6 months.'],
    ['Cancel the plan', "You cancel the investment to lift this year's margin and trim visits."],
    ['Install at all 6', 'You install the system at all 6 plants with a budget of 0.8.'],
    ['Decide later', 'You keep weighing the savings 3 more months while visits cost the same.']],

  ['m06c', 'Competitor 8% lower', 'A competitor offers 8% less and threatens a contract worth 14% of sales.',
    ['Show the savings', 'You present the measured savings and hold the price with a 2-year rebate.'],
    ['Lock in the client', 'You sign 3 years with 20% exit penalties and keep your list price.'],
    ['Match the price', 'You cut the price 8% for the length of the contract and keep the rest.'],
    ['Trust the bond', 'You nurture the relationship and take a loyal bond for granted for 3 years.']],
  ['m06p', 'Quality drift', 'This week 4 batches out of 10 come out at the edge of spec.',
    ['Tune the process', 'You adjust the process alongside quality and reinforce the batch controls.'],
    ['Blend batches', 'You blend doubtful batches in parts with good ones so the average passes.'],
    ['Extra checks', 'You add checks to each batch and release slips 2 days.'],
    ['Wait for a claim', 'You ship 4 batches to log whether any client complains.']],
  ['m06e', 'Water regulation', 'An environmental rule cuts water use 20% at food plants.',
    ['Reuse program', 'You offer a water-reuse program paid per m3 saved.'],
    ['Closed package', 'You sell an untested turnkey package and sign 3 contracts.'],
    ['Free diagnostics', 'You run free savings diagnostics with clients to win their trust.'],
    ['Let them ask', 'You help only whoever asks, with a reply in 10 days.']],
  ['m06s', 'New country', 'A big client abroad asks for a quote within 30 days.',
    ['Enter with partner', 'You pick a local distributor and cap the first-year investment.'],
    ['Serve from afar', 'You serve from here at prices 15% higher to cover the initial risk.'],
    ['Take the terms', "You take the client's requirements and contracts from day 1."],
    ['Late quote', 'You email the quote in 45 days, with the requirements reviewed.']],

  ['m07c', 'Cost audit', 'A client (11% of your sales) asks to audit your costs and margin.',
    ['Open with rules', 'You accept the audit and show freight and Direct Chg to set how costs compare.'],
    ['Show only part', 'You hand over the costs that favor you, the rest in summary.'],
    ['Open book', 'You hand over costs by line and agree to cut your margin 2 points.'],
    ['Audit postponed', 'You put off the audit for lack of time, up to 6 months.']],
  ['m07p', 'Late supplier', 'Your only supplier is 3 weeks late on an input that is 30% of cost.',
    ['Second supplier', 'You qualify a second supplier with 2 tests and cover the gap with stock.'],
    ['Alternative input', 'You switch to a cheaper input for 3 months and tell the client afterwards.'],
    ['Urgent freight', 'You fly the input in at any rate and cover the week.'],
    ['Single plan', 'You stay with the only supplier and trust it to recover the delay.']],
  ['m07e', 'Snowstorm', 'A snowstorm closes the mountain pass for 7 days.',
    ['Stock at the client', "You move stock to the client's warehouse for 10 days and reschedule trips."],
    ['Calm window', 'You send trucks in the calm window and arrive before the close.'],
    ['Air shipment', 'You cover the critical items by air so that nothing slips.'],
    ['Closed pass', 'You halt shipments with the pass closed, about 7 days.']],
  ['m07s', 'Reorganization', 'Corporate proposes reorganizing the team and cutting headcount 10%.',
    ['Redesign roles', 'You reassign duties and automate processes before cutting 4 posts.'],
    ['Cut 10% evenly', "You cut headcount 10% in each area to meet the quarter's goal."],
    ['Keep the team', 'You keep headcount with a promise to improve productivity in 6 months.'],
    ['Defer the topic', 'You defer the reorganization and pick it up in the second half.']],

  ['m08c', 'New buyer', "A client's new procurement head (16% of sales) wants to tender.",
    ['Value meeting', 'You present measured results and offer a tiered rebate over 2 years.'],
    ['Low base price', 'You enter with a base price 6% lower and charge services apart.'],
    ['Bid the minimum', 'You offer the lowest price possible on 3-year contracts.'],
    ['Formal invitation', 'You await the formal invitation and prepare the offer in 10 days.']],
  ['m08p', 'Capacity at the limit', 'Demand exceeds plant capacity by 12% for 3 months.',
    ['Extra shift', 'You add a planned shift and keep the priority by margin in production.'],
    ['Plant nonstop', 'You run the line 24 hours for 3 months and postpone maintenance.'],
    ['Take the orders', 'You take the orders of the 3 months and settle lead times with them afterwards.'],
    ['Keep the routine', 'You run the standing plan and demand sorts itself out.']],
  ['m08e', 'Dollar jumps', 'The dollar rises 10% and so does your imported input cost.',
    ['Phased pass-through', "You pass half of the rise into prices in stages, giving 30 days' notice."],
    ['One-step increase', "You adjust prices 10% at once and make up the month's rise."],
    ['Absorb the rise', 'You leave prices as they are to protect clients and the margin pays 10%.'],
    ['Track the dollar', 'You use the price list as is and assess the dollar every 30 days.']],
  ['m08s', 'Distributor deal', 'A distributor would serve your small clients for an 8% commission.',
    ['6-month pilot', 'You test on 10 small clients and compare service and margin.'],
    ['Hand over the book', 'You hand over the book of 120 small clients to cut your costs.'],
    ['Pay the commission', 'You pay the 8% commission on the terms the distributor asks.'],
    ['Reject the offer', 'You reject the 8% offer on internal policy, before seeing the numbers.']],

  ['m09c', 'Volume for price', 'A client (13% of your sales) promises 20% more volume if you cut 5%.',
    ['Tiered discount', 'You cut 5% on the new shipments and review the result after 3 months.'],
    ['Charge the others', 'You lift the list 3% for minor clients, who rarely haggle, to cover the cost.'],
    ['Give 5% on all', 'You grant a 5% discount all year and trust their promise to grow.'],
    ['Send to committee', 'You leave the proposal with the pricing committee, which meets in 4 weeks.']],
  ['m09p', 'Peak-hour energy', 'The power tariff rises 12% at peak hours, where the plant uses 40%.',
    ['Shift the load', 'You push 2 plant lines to the night shift with the same staff.'],
    ['Short shift', 'You cut the afternoon shift by 25% and small orders run late.'],
    ['Cover the rise', 'You cover the whole rise and keep the 3 shifts to leave the routine alone.'],
    ['Plan unchanged', 'You run the current 3 shifts and the tariff gets reviewed in 3 months.']],
  ['m09e', 'Elections', 'Elections are coming and 4 clients hold back orders amid the uncertainty.',
    ['Bridge contract', 'You offer 6-month contracts at a fixed price, with an option to extend to 12.'],
    ['Prize for signing', 'You cut 8% for the 4 clients who sign in 30 days, though they planned to buy.'],
    ['Go at their pace', 'You adopt whatever calendar each client sets and reschedule the whole plant.'],
    ['Campaign pause', 'You pause offers during the campaign and resume them after the election.']],
  ['m09s', 'Supplier contract', 'Your key supplier (32% of cost) offers 6% less for a 3-year contract.',
    ['Contract with exit', 'You sign 36 months with an exit clause at month 18 and an indexed price.'],
    ['Total exclusivity', 'You accept 5 years of exclusivity and get 9% less right away.'],
    ['Sign unchanged', 'You approve the supplier text as it came, with yearly price hikes.'],
    ['Offer lapses', 'You keep buying at list price and the offer lapses in 30 days.']],

  ['m10c', 'Loaned equipment', 'A client asks for 3 dosing units on loan for its new plants.',
    ['Loan on conditions', 'You lend the units if it commits to yearly purchases and pays the upkeep.'],
    ['Add to the price', 'You add 3% to the price of supplies and fund the units with that.'],
    ['Hand over freely', 'You hand over the 3 units and cover upkeep even if it buys little.'],
    ['Buy their own', 'You explain that loans do not exist and that it should buy its own units.']],
  ['m10p', 'Partial strike', 'The union announces a 2-day partial strike if there is no year-end bonus.',
    ['Goal bonus', 'You link a variable bonus to plant and safety goals, in 2 installments.'],
    ['Cover with overtime', 'You cover the 2 days with supervisors and avoid talking to the union.'],
    ['Meet the demand', 'You give in on the fixed bonus they demand and avoid a costly strike.'],
    ['Ignore the notice', 'You brush off the announcement and see if the strike goes ahead or fades.']],
  ['m10e', 'Drought at the plant', "A drought cuts your plant's water 20% and orders cannot all be covered.",
    ['Profitable orders', 'You allocate output to the orders that pay best and tell the others.'],
    ['Scarcity surcharge', 'You impose a 10% scarcity surcharge, even on orders already quoted.'],
    ['Water trucks', 'You hire water tankers to supply everyone, whatever it costs.'],
    ['Order of arrival', 'You run on the water available and ship orders as they come in.']],
  ['m10s', 'Industry fair', 'The fair costs US$ 0.5 M in booth and travel, and 6 of your clients skip it.',
    ['Go with meetings', 'You go with a small booth and 15 meetings already booked with clients.'],
    ['Fair discount', 'You give 5% to visitors who sign at the fair, though they already bought.'],
    ['Big booth', 'You book the big booth that Marketing wants so as not to fall behind.'],
    ['Repeat the booth', "You repeat last year's booth, with the same team and budget."]],

  ['m11c', 'Disputed charges', 'A client disputes 3% of charges on 4 invoices, but keeps buying.',
    ['Check each charge', 'You check the 4 invoices with the client and correct any error.'],
    ['Charges into price', 'You spread those charges inside the list price of the next invoices.'],
    ['Credit note', 'You issue credit notes for 3% of the 4 invoices and close the matter.'],
    ['Leave it open', 'You keep the dispute open and correct each charge only if the client insists.']],
  ['m11p', 'Year-end shifts', 'Year-end brings 30% more orders and people asking for vacation.',
    ['Rotating shifts', 'You rotate people with fair leave and a 3% bonus for hitting targets.'],
    ['Freeze leave', 'You freeze December leave and keep the 3 shifts at maximum.'],
    ['Grant the leave', 'You grant the leave asked and tolerate 2 weeks of delays, despite complaints.'],
    ['Shifts day by day', 'You set shifts day by day and watch how weekly demand evolves.']],
  ['m11e', 'Road blockade', 'A blockade of the main road halts your shipments for 3 weeks.',
    ['Detour', 'You arrange a detour with the client and keep talks open with neighbors.'],
    ['Bill the delay', 'You bill the client for the blockade cost and explain it if they complain.'],
    ['Escort and toll', 'You buy tolls and escorts to ship the 20 pending orders.'],
    ['Pause shipments', 'You hold the trucks and the client opens talks with the neighbors.']],
  ['m11s', 'Sales commissions', 'Your salespeople earn 3% on sales, even when the margin is low.',
    ['Pay on margin', 'You switch the commission base to margin and set a 1% floor for 6 months.'],
    ['Higher targets', "You raise everyone's sales target 15% and expect more volume right away."],
    ['4% commission', 'You lift the commission to 4% so your strongest sellers do not leave.'],
    ['Current scheme', 'You keep the current scheme and review it in the annual targets round.']],

  ['m12c', 'Fixed-price contract', 'A client offers to renew 3 years at a fixed price, no inflation clause.',
    ['Fixed with a limit', 'You accept 36 months and ask for a limit that follows input cost.'],
    ['Hike and sign', 'You sign at an opening price 3% higher, even if it sits above the market.'],
    ['Sign as asked', 'You sign the 3 years exactly as the client drafted, in its wording.'],
    ['Ask for time', 'You ask legal for more time and the offer expires in 30 days.']],
  ['m12p', 'Obsolete inventory', 'The year closes and 5% of inventory looks obsolete before valuation.',
    ['Count and sell', 'You count the inventory, sell the recoverable part and write off the rest.'],
    ['Book value', 'You keep the 5% obsolete at book value and defer the write-off.'],
    ['Write off extra', 'You write off 12% at once, as Audit insists, and carry the hit.'],
    ['Close on system', 'You use the system figures and do not delay the close beyond 3 days.']],
  ['m12e', 'Trucker strike', 'A trucker strike threatens December shipments, 18% of the year.',
    ['Ship early', 'You ship 40% of the dispatches early and book 3 alternative carriers.'],
    ['Surcharge', 'You apply a 5% surcharge for the strike and explain it after invoicing.'],
    ['Approve rates', 'You approve whatever rate each carrier quotes to meet the dates.'],
    ['Run as planned', 'You keep the plan with the trucks available and orders pile up.']],
  ['m12s', 'Year-end close', 'One month before the close and OI sits 1 point below plan.',
    ['Freeze hiring', 'You freeze 2 open positions for 90 days and pause training unrelated to sales.'],
    ['Pull invoices in', 'You pull January invoicing into December and land the year above plan.'],
    ['Reward the team', 'You award the full bonus to the team, even if the result falls short.'],
    ['See what comes', 'You close the year as it stands and analyze the gap to plan afterwards.']],
];

const entries = ROWS.flatMap(([id, title, scene, ...answers]) => [
  [`year.${id}.title`, title],
  [`year.${id}.scene`, scene],
  ...answers.flatMap(([name, desc], i) => [
    [`year.${id}.${ANSWERS[i]}.name`, name],
    [`year.${id}.${ANSWERS[i]}.desc`, desc],
  ]),
]);

module.exports = Object.freeze(Object.fromEntries(entries));
