'use strict';

// Year mode interface, English. Same keys and {placeholders} as year-ui.es.js.

module.exports = Object.freeze({
  // Mode menu
  'menu.title': 'CHOOSE A MODE',
  'menu.year': 'Full year',
  'menu.year.desc': '12 months of 4 problems. About 25 min.',
  'menu.tutorial': '5-floor tutorial',
  'menu.tutorial.desc': 'How the P&L moves. About 10 min.',
  'menu.endings': 'See the 6 endings',
  'menu.endings.desc': 'Simulates a year with a play style.',
  'menu.best': 'Best year: {result}',
  'menu.endings.title': 'CHOOSE A PLAY STYLE',
  'profile.expert': 'Expert',
  'profile.expert.desc': 'Reads every situation and balances.',
  'profile.careful': 'Careful',
  'profile.careful.desc': 'Right almost always, a few slips.',
  'profile.average': 'Average',
  'profile.average.desc': 'Hits and misses in equal parts.',
  'profile.weak': 'Weak',
  'profile.weak.desc': 'More misses than hits.',
  'profile.short': 'Always the shortcut',
  'profile.short.desc': 'OI today, the bill comes later.',
  'profile.pleaser': 'Always give in',
  'profile.pleaser.desc': 'Everyone happy, no margin.',
  'profile.passive': 'Do nothing',
  'profile.passive.desc': 'Lets every problem slide.',
  'profile.halfShort': 'Half shortcuts',
  'profile.halfShort.desc': 'Balances, but falls for the shortcut.',

  // Introduction
  'year.intro1': 'You run a business unit for 12 months. Each month brings 4 problems: client, plant, environment and strategy.',
  'year.intro2': 'Your goal is the OI margin: operating income as a % of sales (plan 15%). Also watch three meters: Client, Plant and Strategy.',
  'year.intro.hint': 'Type 4 digits to choose the code.',
  'year.intro.partial': 'Digits missing. Erase with Backspace.',
  'year.intro3': 'Balance wins. A 0 brings a rescue plan; a second one, bankruptcy. N: rules.',

  // Screen furniture
  'year.stage': 'Month {m} - {p}/4',
  'year.voice.cliente': 'CLIENT',
  'year.voice.planta': 'PLANT',
  'year.voice.entorno': 'ENVIRON.',
  'year.voice.estrategia': 'STRATEGY',
  'year.meterTag.C': 'CLI',
  'year.meterTag.P': 'PLT',
  'year.meterTag.E': 'STR',
  'year.meterName.C': 'Client',
  'year.meterName.P': 'Plant',
  'year.meterName.E': 'Strategy',
  'year.crisis.l1': 'Crisis {tag}!',
  'year.crisis.l2': 'Pays only 40%',
  'year.goal': 'Goal: OI {n}%',
  'year.review.on': 'REVIEWER',
  'year.tag.smart': 'BALANCED',
  'year.tag.temp': 'SHORTCUT',
  'year.tag.plac': 'GIVE IN',
  'year.tag.ign': 'PASSIVE',
  'ui.btn.rules': 'N rules',
  'ui.btn.quit': 'Enter: leave',
  'ui.btn.menu': 'Enter: menu',
  'ui.btn.report': 'Enter: report',
  'ui.btn.feedback': 'Enter: feedback',
  'year.quit.title': 'LEAVE TO MENU',
  'year.quit.body': 'You will lose the game in progress. Leave?',
  'year.quit.hint': 'N or X: keep playing',

  // After an answer
  'year.res.chose': 'You chose: {name}',
  'year.why.smart': 'You balanced: {meter} improved without giving up OI.',
  'year.why.temp': 'Shortcut: OI rises today and {meter} suffers; part of the bill arrives in 2 months.',
  'year.why.plac': 'You gave in to the voice in tension: {meter} rose and OI paid the bill.',
  'year.why.ign': 'Doing nothing also costs: {meter} fell and OI took a hit.',
  'year.note.crisis': '{meter} was in crisis: the balanced answer reached only 40%.',
  'year.note.recovery': 'Rescue plan: the balanced answer earned 5x OI.',
  'year.note.value': 'Value measured: your answer leaned on the documented savings.',
  'year.note.measured': 'Value measured! Your answers to clients will pay off more.',

  // Month close
  'year.close.title': 'MONTH {m} CLOSE',
  'year.close.decay': 'All three meters drop 1.8 from the month\'s wear.',
  'year.close.drag': '{meter} below 42: {line} {pts}',
  'year.close.bonus': '{meter} above 70: {line} {pts}',
  'year.close.fly': 'All three above 60: Sales {pts}',
  'year.close.bill': 'The bill for the {problem} shortcut arrives: {meter} {value}',
  'year.close.chart': 'OI % monthly',

  // Rescue plan
  'year.rescue.title': 'IN THE RED',
  'year.rescue.cause': 'Cause: {cause}',
  'year.rescue.body1': 'The board gives you one last chance: capital and a support team.',
  'year.rescue.body2': 'Goal: reach OI {goal}% before year-end. While below 15%, balanced answers earn 5x more.',
  'year.rescue.body3': 'It leaves a scar: the best possible is a fair year. Another zero is bankruptcy.',

  // Verdict
  'year.verdict.excellent': 'EXCELLENT YEAR',
  'year.verdict.good': 'GOOD YEAR',
  'year.verdict.fair': 'FAIR YEAR',
  'year.verdict.bad': 'BAD YEAR',
  'year.verdict.terrible': 'TERRIBLE YEAR',
  'year.verdict.bankrupt': 'BANKRUPT',
  'year.verdict.oi': 'OI {oi}%',
  'year.verdict.plan': 'plan {plan}%',
  'year.walk.title': 'OI margin bridge (pp)',
  'year.report.title': 'INCOME STATEMENT',
  'year.report.note': 'Annualized figures at year end. Var.: in brackets = unfavorable.',
  'year.fb.title': 'WHAT HAPPENED',
  'year.walk.plan': 'Plan',
  'year.walk.real': 'Real',
  'year.fb.cause.oi': 'OI reached zero',
  'year.fb.cause.C': 'the client left (Client at 0)',
  'year.fb.cause.P': 'the plant stopped (Plant at 0)',
  'year.fb.cause.E': 'you lost the market (Strategy at 0)',
  'year.fb.sum.excellent': 'Excellent year: OI {oi}% and the weakest meter ({meter}) at {value}. Result and health together.',
  'year.fb.sum.good': 'Good year: OI {oi}%; your weakest spot was {meter} ({value}).',
  'year.fb.sum.fair': 'Fair year: OI {oi}%. It held, but {meter} ended at {value}, with no room for error.',
  'year.fb.sum.bad': 'Bad year: OI {oi}%. {meter} ended at {value} and the business is fragile.',
  'year.fb.sum.terrible': 'Terrible year: OI {oi}%. {meter} ended at {value}: you survived, barely.',
  'year.fb.sum.bankrupt': 'Bankruptcy in month {month}: {cause}.',
  'year.fb.temp': 'You took {n} shortcuts. Costliest: {problem} (month {month}): {oiGain} pp of OI now, {meter} suffered.',
  'year.fb.plac': 'You gave in {n} times: the meters held, but OI paid {oiLost} pp.',
  'year.fb.ign': 'You did nothing {n} times: each one cost OI and let a meter fall.',
  'year.fb.clean': 'You chose the balanced answer {n} of 48 times: few mistakes and almost no shortcuts.',
  'year.fb.mixed': 'You got the balanced answer right {n} of 48 times; the rest were shortcuts, giving in or passivity.',
  'year.fb.tip.C': 'Next time: look after the client before it drops below 42; past that point everything costs more.',
  'year.fb.tip.P': 'Next time: keep the plant above 42; a tired plant makes everything dearer.',
  'year.fb.tip.E': 'Next time: protect strategy (measure value, invest in stages); without it price erodes.',
  'year.fb.tip.keep': 'Next time: keep it up and watch the weakest meter before it drops below 42.',
  'year.fb.rescued.yes': 'The month {month} rescue plan saved you: you hit the goal (OI {oi}%).',
  'year.fb.rescued.no': 'You went through the month {month} rescue plan and missed the OI {goal}% goal.',
  'year.fb.value': 'You measured the client\'s savings in month 1: your answers to clients paid off more.',
  'year.fb.noValue': 'You did not measure the client\'s savings: your answers to clients had no backing.',

  // Game over
  'year.over.restart': 'The game restarts...',
  'year.over.count': 'New game in {n}',

  // Rules overlay (N)
  'year.rules.title': 'RULES OF THE YEAR',
  'year.rules.l1': 'OI = operating income / sales. Plan: 15%. pp = percentage points.',
  'year.rules.l2': 'Client, Plant and Strategy start at 60 and drop almost 2 a month.',
  'year.rules.l3': 'Below 42 they cost OI; above 70 they add. Below 32: crisis, balanced answers reach 40%.',
  'year.rules.l4': 'A 0 in OI or a meter: rescue plan, once, up to month 9.',
  'year.rules.l5': 'The result is the lower of the OI grade and the weakest-meter grade.',
  'year.rules.hNote': 'Grade',
  'year.rules.hOi': 'OI from',
  'year.rules.hMeter': 'Meter from',
  'year.rules.below': 'lower',
  'year.grade.excellent': 'Excellent',
  'year.grade.good': 'Good',
  'year.grade.fair': 'Fair',
  'year.grade.bad': 'Bad',
  'year.grade.terrible': 'Terrible',
  'year.rules.hint': '< > switch page ({n}/2)',
  'year.assump.title': 'MODEL ASSUMPTIONS',
  'year.assump.a1': 'Everything is fictional. Figures in US$ millions; plan: sales 100 and OI 15%.',
  'year.assump.a2': 'Sales - Incentives - Cost = Contribution margin. Less Cost to serve = Gross Profit. Less SG&A = OI.',
  'year.assump.a3': 'Ratio = line / sales. Price moves sales and incentives; volume also moves cost and 60% of cost to serve. SG&A is fixed.',
  'year.assump.a4': 'Figures are annualized at the close of each month, not cumulative.',
  'year.assump.a5': 'Effects are game effects: they teach the logic, they do not predict any real company.',
});
