'use strict';

// The case of each problem, English: what the player reads before deciding and what happens after each answer.
//   [id, brief, 'fact|fact|fact', [smart story, temp story, plac story, ign story]]
// Every story opens with the kind of answer it was ("Balanced:", "Shortcut:", "Concession:", "Passivity:"); a red
// line opens with "Red line:". Same ids and same order as year-case.es.js.

const ANSWERS = ['smart', 'temp', 'plac', 'ign'];

const ROWS = [
  ['m01c', 'A chain of 6 hotels buys hygiene and laundry supplies for all its sites. Its contract expires in 20 days and a competitor has already quoted. Sales management wants to close fast.',
    'Client: chain of 6 hotels|Weight: 18% of your sales|Client margin: 38%',
    ['Balanced: the hotel signed for 2 years; a 1% rebate costs little and secures 18% of your sales.',
      'Shortcut: you took the 3% and recovered it on other products; OI rises now, the hotel will notice.',
      'Concession: you renewed by giving the full 3%. The client stayed, but that rebate is margin that never returns.',
      'Passivity: the contract expired in 20 days and the hotel quoted another supplier: you lost volume.']],
  ['m01p', 'January is high season: hotel chains double their laundry and hygiene use. Your key supplier delivers in 20 days and the warehouse holds supplies for 3 weeks.',
    'Client: hotels in high season|January orders: +40%|Supplies on hand: 3 weeks',
    ['Balanced: you bought in two lots and flagged the firm orders; no spot price and the warehouse under control.',
      'Shortcut: the plant ran at 110% and you avoided the costly purchase; the line wear is paid later.',
      'Concession: you bought 3 months at spot: everything served, a full warehouse and the highest cost.',
      'Passivity: you waited and in January supplies ran out; you lost high-season orders and bought in an emergency.']],
  ['m01e', 'An industrial plant buys under contracts that fix the price for 12 months, but 40% of your inputs are imported in dollars. The dollar is already 7% above budget.',
    'Client: industrial plants|Imported inputs: 40%|Dollar over budget: +7%',
    ['Balanced: you agreed the adjustment in writing and covered half the purchase; the margin stays protected.',
      'Red line: you raised a contract-fixed price. It is a breach: a fine and clients against you.',
      'Concession: you left prices and purchases as they were and the margin paid for the full rise of the dollar.',
      'Passivity: you waited for the close to analyze it and the dollar kept rising on an uncovered cost.']],
  ['m01s', 'Your hospital hygiene program reduces infections, but nobody has measured how much it saves each hospital. Corporate wants 6% more volume and purchasing committees ask for evidence.',
    'Client: hospital network|Corporate target: +6% volume|Savings measured: none',
    ['Balanced: you measured the savings at 3 hospitals and negotiate with data that backs your prices.',
      'Shortcut: the discount brings volume now, but unmeasured savings leave only price to compare.',
      'Concession: you ran the volume plan without measuring; sales rise but you cannot defend your price.',
      'Passivity: you postponed volume and measuring; no evidence, no extra sales, a slow start.']],

  ['m02c', 'A food processing plant changes its packaging line and asks for another sanitizer formula with only 2 weeks\' notice. Its food-safety auditor will review the change.',
    'Client: food plant|Weight: 12% of your sales|Notice: 2 weeks',
    ['Balanced: the 3-day test avoided a rejected batch and you agreed a realistic date with its auditor.',
      'Shortcut: you used warehouse stock and shipped on time; if the formula fails its audit, the claim comes later.',
      'Concession: you accepted the 2 weeks and absorbed the extra cost: the client is happy and the margin paid.',
      'Passivity: you took a week to answer and the plant quoted the formula with another supplier.']],
  ['m02p', 'The disinfectant line needs its major maintenance: 4 days stopped. Two hospitals placed urgent orders because of an outbreak and accept no delays.',
    'Client: hospitals in an outbreak|Urgent orders: 5|Line stopped: 4 days',
    ['Balanced: the shift-based maintenance covered the critical orders of the hospitals and avoided a major failure.',
      'Shortcut: you delayed the maintenance 8 weeks and served it all; the risk stays on the plant.',
      'Concession: you stopped 4 days and asked them to wait: maintenance is done, hospitals suffered.',
      'Passivity: you kept the original schedule and only 2 of 5 urgent orders got in; the other 3 were lost.']],
  ['m02e', 'A storm cuts the coastal roads and 14 shipments to beach hotels are pending in the middle of the season. A hotel without clean linen or hygiene supplies cannot operate.',
    'Client: coastal hotels|Pending shipments: 14|Road cut: 1 week',
    ['Balanced: the inland route costs freight, but you delivered the critical items and kept sales.',
      'Shortcut: you sent trucks over the damaged road and hit the date; risk and wear are paid later.',
      'Concession: the 4x4 trucks at triple rate met every date, with the most expensive freight of the year.',
      'Passivity: you halted shipments for a week: you saved freight, but lost the sales of those 14 orders.']],
  ['m02s', 'Corporate needs to raise the year forecast by 8% to present it to investors on Monday. Your base case is already demanding and several client plants cut production.',
    'Client: industrial plants|Increase asked: +8%|Meeting: on Monday',
    ['Balanced: you delivered a base case and an optimistic one, both explained; corporate plans with credible numbers.',
      'Red line: you inflated the forecast. It is misleading information: a fine, an audit and lost trust.',
      'Concession: you accepted +8% and spread it out; pressure raises selling costs and the meters fall.',
      'Passivity: you sent the forecast late, with old figures; corporate allocated resources without you.']],

  ['m03c', 'An industrial plant claims 40 tons of off-specification product that stopped one of its lines for a day. Its plant manager wants an answer today.',
    'Client: industrial plant|Batch claimed: 40 tons|Answer wanted: today',
    ['Balanced: you replaced the 40 tons and shared the analysis: it costs, but you avoid another claim.',
      'Shortcut: blaming transport and replacing half saves today; if disproved, you lose their trust.',
      'Concession: the 10% discount closed the claim the same day, but you gave away margin without fixing the cause.',
      'Passivity: you answered in 15 days and the formal claim added handling costs and an upset client.']],
  ['m03p', 'A pump on line 2 fails and only 5 days of a key raw material are left. The most critical orders are from hospitals that cannot run out of disinfectant.',
    'Client: hospitals (critical orders)|Raw material: 5 days|Line 2: stopped',
    ['Balanced: you prioritized critical orders with what was left and bought the pump without overpaying.',
      'Shortcut: the patch kept you at full load for 2 days; if it fails again, the line stops at the worst moment.',
      'Concession: you bought pump and material in 24 hours at any price: service held, at the highest cost.',
      'Passivity: you stopped the line to wait for spare parts: critical orders late and the costs of an idle plant.']],
  ['m03e', 'The health authority publishes a draft rule demanding more controls in hospitals and clinics. Three of your largest clients freeze purchases until they see the final text, in 2 months.',
    'Client: hospitals and clinics|Clients holding back: 3|Final rule: in 2 months',
    ['Balanced: you discussed scenarios with each client and gave discounts only to firm orders.',
      'Shortcut: you pulled sales forward with 5% off; the quarter improves, but those orders will not return.',
      'Concession: you froze prices for 12 months to reassure; clients stay firm and your margin gets no adjustment.',
      'Passivity: you waited for the final text and meanwhile the orders of the 3 clients stayed frozen.']],
  ['m03s', 'Five food plants asked about a program that cuts the water used in their washing and rinsing. It is a new service: there is demand, but nobody has tested it at a plant in your portfolio.',
    'Client: food plants|Interested plants: 5|Service: new, no pilots',
    ['Balanced: the 3-month pilot with a friendly client costs service today and leaves a measured result to scale.',
      'Shortcut: you sold all 5 plants on promised results: sales today, claims if they are not met.',
      'Concession: you drafted the proposal and await approval; commercial spend runs, sales do not yet.',
      'Passivity: you left the program for another chance and the 5 plants asked another supplier.']],

  ['m04c', 'A hospital network cuts its supplies budget 10% after a health-spending adjustment and asks for lower prices. It has other suppliers and its committee decides in 30 days.',
    'Client: hospital network|Weight: 10% of your sales|Client budget: -10%',
    ['Balanced: the hospital spends less and pays a service for the savings; it stays, your margin holds.',
      'Shortcut: you cut the product and raised services; the deal closes, but the client will see it.',
      'Concession: you cut 5% for 12 months and the client stayed; that discount is paid all year.',
      'Passivity: you held the terms and within 30 days the committee moved part of the volume elsewhere.']],
  ['m04p', 'Two of your 9 key operators quit for a competitor and the dosing line shifts are left incomplete. Replacing them takes months of training.',
    'Client: industrial plants|Operators leaving: 2 of 9|Replacement: 6 weeks of practice',
    ['Balanced: you trained two young operators and reorganized shifts; it costs today, but overtime ends.',
      'Shortcut: double shifts hold production for a quarter; the team wears out and others might leave.',
      'Concession: the 8% raise stopped the resignations, but the labor cost rises for good.',
      'Passivity: you left the positions empty: payroll fell, but production and quality suffered.']],
  ['m04e', 'A new green tax raises the energy cost of your industrial clients and all of them review their supply contracts to cut costs. Some have no other qualified supplier.',
    'Client: industrial plants|Clients renegotiating: 8|With no other supplier: 3',
    ['Balanced: contracts tied to the savings you create: the client pays for value and you protect margin.',
      'Shortcut: you raised captive clients 6%: OI rises today, and they leave once another supplier qualifies.',
      'Concession: you offered 3% before they asked: loyalty bought, but margin given away unprompted.',
      'Passivity: you renegotiated on the defensive, contract by contract, and clients dictated the prices.']],
  ['m04s', 'Corporate asks to cut the SG&A by 5% from next month to protect group margin. Your team is already stretched and client visits and value measuring depend on that budget.',
    'Client: industrial plants|Cut asked: 5% of SG&A|Deadline: from next month',
    ['Balanced: you cut travel and consulting and protected visits and measuring: less SG&A, same sales.',
      'Shortcut: you cut everything 5% evenly: you hit the target, but also cut what holds up sales.',
      'Concession: you asked for an exception and the SG&A does not fall; corporate notes you missed the cut.',
      'Passivity: you took the order to the quarter-end meeting and meanwhile the SG&A stayed the same.']],

  ['m05c', 'A large hospital asks for a weekly technical visit to audit dosing, without paying more. Each visit costs your team hours, and other hospitals might ask for the same.',
    'Client: large hospital|Weight: 9% of your sales|Visits asked: 4 per month',
    ['Balanced: remote monitoring avoids extra visits: the hospital is served and Direct Chg fall.',
      'Shortcut: a junior technician costs 40% less, but in a hospital a dosing error hits hard later.',
      'Concession: 4 visits a month at your cost: a happy hospital, but Direct Chg rise with no extra revenue.',
      'Passivity: you took 20 days to answer and the hospital felt its service did not matter.']],
  ['m05p', 'A product leak at your sanitizer plant leaves no injuries, but the procedure failed. In 10 days a food-industry client sends its safety auditors.',
    'Client: food industry|Audit: in 10 days|Orders in progress: 120',
    ['Balanced: you stopped the zone for 2 days and fixed the procedure; the audit finds you up to date.',
      'Red line: you closed as minor a real incident. Hiding it is serious: a sanction and a hostile audit.',
      'Concession: you stopped 7 days and redid everything: flawless safety, but late orders and a high cost.',
      'Passivity: you kept producing without investigating: the audit finds the broken procedure.']],
  ['m05e', 'A 15% drop in tourism lowers hotel occupancy. Chains freeze non-essential purchases and ask all their suppliers for better terms.',
    'Client: hotel chains|Tourism drop: -15%|Frozen purchases: non-essential',
    ['Balanced: the rebate only rewards volume above their minimum: it costs little and keeps the orders.',
      'Shortcut: you charged active buyers more and trimmed their rebate: OI rises now, they remember later.',
      'Concession: 3% rebate for all: purchases hold, but you give margin to those who would buy anyway.',
      'Passivity: you waited for tourism to rebound while hotels kept cutting orders.']],
  ['m05s', 'Remote monitoring replaces monthly visits to 6 client plants. The equipment is an investment: it depreciates over years, but installation and service cost this year.',
    'Client: 6 industrial plants|Total investment: US$ 0.8 M|Visits today: 1 per month',
    ['Balanced: you installed at 2 plants and measure the visit savings before committing the other 4.',
      'Shortcut: you canceled the investment and cut visits: margin improves today, but service suffers.',
      'Concession: you installed at all 6 untested; cost weighs now and the savings are uncertain.',
      'Passivity: you weighed 3 more months and visits kept costing the same; the savings were postponed.']],

  ['m06c', 'A competitor offers 8% less to a hotel chain that is 14% of your sales. The buyer values your service, but the general management pushes to cut supply costs.',
    'Client: hotel chain|Weight: 14% of your sales|Rival offer: 8% less',
    ['Balanced: you showed the measured savings and defended price with a 2-year rebate; the hotel stays.',
      'Shortcut: the 3-year contract with exit fines holds the client now, but resentful and tied down.',
      'Concession: you matched the 8% for the contract: you keep the hotel, and margin drops every month.',
      'Passivity: you took its loyalty for granted and the hotel moved part of the contract away.']],
  ['m06p', 'This week 4 of 10 disinfectant batches come out at the edge of specification. Hospitals demand a quality certificate per batch and a doubtful batch can cost an audit.',
    'Client: hospitals|Batches at the limit: 4 of 10|Certificate: for every batch',
    ['Balanced: you adjusted the process and reinforced controls: batches back in range with real certificates.',
      'Red line: you blended doubtful batches with good ones to pass. It is quality fraud: recall, sanction.',
      'Concession: you added tests to every batch and release takes 2 days more: firm quality, cost and delays.',
      'Passivity: you shipped 4 batches unchecked: when a hospital complains, it will be in writing.']],
  ['m06e', 'An environmental rule forces food plants to use 20% less water. Your clients need solutions now and every competitor is offering programs.',
    'Client: food plants|Required water cut: 20%|Deadline to comply: 6 months',
    ['Balanced: the reuse program paid per m3 saved ties your income to the savings of the client.',
      'Shortcut: you sold an untested turnkey package and signed 3 contracts; if it fails, the claim is yours.',
      'Concession: free diagnostics win trust, but unbilled service adds Direct Chg without sales.',
      'Passivity: you helped only those who asked and in 10 days several clients had hired another supplier.']],
  ['m06s', 'A foreign hotel chain asks you to quote hygiene supply for its hotels there. It is a new market: no distributor, no reference prices and local requirements.',
    'Client: foreign hotel chain|Time to quote: 30 days|Local presence: none',
    ['Balanced: you entered with a local distributor and limited the investment: new sales, bounded risk.',
      'Shortcut: you serve from afar at 15% higher prices: margin now, and a service the client sees as fragile.',
      'Concession: you took on all its requirements from the start: the SG&A begins before the sales.',
      'Passivity: you quoted at 45 days and the client had already chosen another supplier.']],

  ['m07c', 'An industrial plant that is 11% of your sales asks to audit your costs and margin before renewing. Its buyer suspects freight and service are inflated.',
    'Client: industrial plant|Weight: 11% of your sales|Request: audit costs and margin',
    ['Balanced: you opened freight and Direct Chg with clear rules; the client sees the value.',
      'Shortcut: you showed only the costs that favor you; if the client cross-checks, you lose its trust.',
      'Concession: you opened everything and agreed to cut 2 margin points without arguing the value you give.',
      'Passivity: you postponed the audit 6 months and the client assumed you were hiding something: it bought less.']],
  ['m07p', 'Your only supplier of an input that is 30% of cost announces a 3-week delay. A food plant is waiting on your orders and does not accept partial deliveries.',
    'Input: 30% of cost|Delay: 3 weeks|Qualified suppliers: 1',
    ['Balanced: you qualified a second supplier and covered the gap with stock: you depend less on one.',
      'Shortcut: the cheaper input saves the quarter; in food, swapping without telling invites a complaint.',
      'Concession: air freight saved the date at any rate and freight ate the margin of those orders.',
      'Passivity: you trusted the single supplier and the plant stopped 3 weeks: the orders did not ship.']],
  ['m07e', 'A snowstorm closes the mountain pass for 7 days. Three regional hospitals have disinfectant for 10 days and cannot run out of it.',
    'Client: regional hospitals|Pass closed: 7 days|Client stock: 10 days',
    ['Balanced: you pre-stocked the hospital and consolidated shipments: no stockouts, tidy freight.',
      'Shortcut: the calm window got you in before the closing; if it fails, the hospital is left without product.',
      'Concession: air shipping met every date, at a freight cost no price on those orders recovers.',
      'Passivity: you halted shipments for 7 days: you saved freight, but those sales did not ship.']],
  ['m07s', 'Corporate proposes reorganizing the team and cutting headcount 10%. Your 40 people serve hospitals with service visits, and each position has clients in its care.',
    'Headcount: 40 people|Target: 10% less (4 roles)|Deadline: this quarter',
    ['Balanced: you redesigned roles and automated before cutting 4 positions: less SG&A without dropping service.',
      'Shortcut: the even 10% meets the quarter target, but people who served clients also left.',
      'Concession: you kept the team on a promise of better productivity; the SG&A stays the same, and it shows.',
      'Passivity: you pushed the reorganization to the second half and the SG&A kept running in the meantime.']],

  ['m08c', 'The new head of purchasing of a hospital network (16% of your sales) wants to tender the entire supply. They came with a cost-cutting goal and do not know your track record.',
    'Client: hospital network|Weight: 16% of your sales|Process: open tender',
    ['Balanced: you brought measured results and a tiered 2-year rebate: the buyer sees value.',
      'Shortcut: you came in with a base price 6% lower and charged services apart; the final bill surprises.',
      'Concession: you offered the lowest price on 3-year contracts: you win the contract at minimum margin.',
      'Passivity: you waited for the formal invitation and quoted in 10 days; the buyer already had other prices.']],
  ['m08p', 'In peak season, hotels ask for 12% more than your plant can produce for 3 months. Producing more costs; turning orders down costs too.',
    'Client: hotels in peak season|Demand over capacity: +12%|Duration: 3 months',
    ['Balanced: you added a planned shift and prioritized by margin: the plant performs without breaking.',
      'Shortcut: running the plant nonstop covers demand, but skipping maintenance can cost a lot later.',
      'Concession: you took every order and negotiated deadlines later; delays and overtime raise the cost.',
      'Passivity: you kept the current plan and demand did not sort itself out: orders were lost.']],
  ['m08e', 'The dollar rises 10% and your imported inputs get as expensive. Food plants buy from you on price lists reviewed every 3 months.',
    'Client: food plants|Dollar: +10%|Price review: every 3 months',
    ['Balanced: you passed half of the rise through in steps, with 30 days notice; clients accept it.',
      'Shortcut: you repriced 10% at once: the month improves, but several clients start quoting elsewhere.',
      'Concession: you left prices alone to look after clients and the margin paid the whole 10%.',
      'Passivity: you watched the dollar every 30 days with the old list: cost rose and margin eroded.']],
  ['m08s', 'A distributor offers to serve your small clients (neighborhood hotels and hostels) for an 8% commission. You would cut visit costs, but give up the relationship with them.',
    'Small clients: 120|Distributor commission: 8%|Possible pilot: 10 clients',
    ['Balanced: you tested 6 months with 10 clients and compared service and margin before deciding.',
      'Shortcut: you handed over 120 clients to cut costs: the SG&A falls, but you lose the relationship.',
      'Concession: you accepted the 8% and the distributor terms: the margin on those clients drops.',
      'Passivity: you rejected the 8% by policy without seeing numbers: visits with no margin go on.']],

  ['m09c', 'A hotel chain (13% of your sales) promises 20% more volume if you cut 5%. The growth is possible, but the promise is unsigned and its margin is already low.',
    'Client: hotel chain|Promised volume: +20%|Cut asked: 5%',
    ['Balanced: you cut 5% only on new shipments and review at 3 months: more sales, margin looked after.',
      'Shortcut: you raised small clients, who do not negotiate, by 3%: OI rises today, they notice tomorrow.',
      'Concession: you gave 5% for the whole year trusting the promise: more sales, at a much lower margin.',
      'Passivity: you left the proposal 4 weeks in committee and the hotel split the volume among others.']],
  ['m09p', 'The electricity rate rises 12% at peak hours, just when your plant uses 40% of its energy. Moving production costs, and doing nothing costs too.',
    'Peak-hour rate: +12%|Energy used at peak: 40%|Rate review: in 3 months',
    ['Balanced: you moved 2 lines to the night shift: energy costs less and you keep the orders.',
      'Shortcut: you cut the afternoon shift 25%: you save energy, but small orders are late.',
      'Concession: you covered the full rise to avoid touching the routine: energy cost rises every month.',
      'Passivity: you kept 3 shifts until the review and paid the full rise for 3 months, moving nothing.']],
  ['m09e', 'Elections are coming and 4 hotel chains hold back orders because of uncertainty. They want to wait for the result before committing inventory.',
    'Client: hotel chains|Clients holding back: 4|Election: in 6 weeks',
    ['Balanced: bridge contracts of 6 months at a fixed price, with an option for 12: orders come back.',
      'Shortcut: you cut 8% for whoever signed this month; they already meant to buy: margin given away for nothing.',
      'Concession: you followed each client calendar and rescheduled the whole plant: you pay for the mess.',
      'Passivity: you paused offers and the 4 clients only ordered after the election: sales lost.']],
  ['m09s', 'Your key supplier (32% of cost) offers 6% less if you sign for 3 years. For a food plant the input is critical, but tying yourself that long has risks too.',
    'Input: 32% of cost|Discount offered: 6%|Contract: 3 years',
    ['Balanced: you signed 36 months with an exit at month 18 and indexed price: cost falls and you keep options.',
      'Shortcut: you accepted 5 years of exclusivity for 9% less: cost falls today and you have no alternative.',
      'Concession: you signed the supplier text as it came, with yearly rises: the savings melt in the readjustments.',
      'Passivity: you let the offer lapse and kept paying list price: the 6% saving was lost.']],

  ['m10c', 'A food plant asks for 3 dosing units on loan for its new lines. The units are yours and their upkeep is on you, even if it buys little.',
    'Units asked: 3 dosing units|Minimum purchase: not agreed|Upkeep: on you',
    ['Balanced: you supplied the units with a yearly minimum purchase and paid upkeep: clear return.',
      'Shortcut: you added 3% to input prices to pay for the units; the client will see the rise on its invoice.',
      'Concession: you handed over 3 units and took on upkeep even if it buys little: Direct Chg without sales.',
      'Passivity: you told it to buy its own units; the client went to someone who does lend them.']],
  ['m10p', 'Your plant union announces a 2-day partial strike if there is no year-end bonus. Holiday orders are in progress and a stopped line delays clients.',
    'Strike announced: 2 days|Year-end orders: in progress|Bonus demanded: fixed, annual',
    ['Balanced: you offered a bonus on plant and safety targets in 2 installments: no strike, variable cost.',
      'Shortcut: you covered the 2 days with supervisors and avoided the union; the conflict stays open.',
      'Concession: you paid the fixed bonus they demanded: no strike, but labor cost rises every year.',
      'Passivity: you ignored the announcement and the strike happened: no orders shipped those 2 days.']],
  ['m10e', 'A drought cuts the water your plant uses by 20% and it does not cover every order. Food plants wait on deliveries and not every order pays the same.',
    'Water available: 20% less|Orders not covered: 1 in 4|Client: food plants',
    ['Balanced: you gave water to the orders that pay best and warned the rest: less volume, more margin.',
      'Shortcut: the 10% surcharge lifts income today, but you also billed it on orders already quoted.',
      'Concession: water trucks supplied everyone: no sale was lost and the water cost soared.',
      'Passivity: you delivered in order of arrival: low-margin orders were covered and the best were lost.']],
  ['m10s', 'The annual hospital-sector fair costs US$ 0.5 M in booth and travel. Six of your most important clients already said they will not go this year.',
    'Fair cost: US$ 0.5 M|Clients not going: 6|Meetings already booked: 15',
    ['Balanced: you went with a small booth and 15 booked meetings: less SG&A and meetings worth having.',
      'Shortcut: you gave 5% to fair visitors who signed, though they already bought: margin given away.',
      'Concession: you booked the big booth Marketing asked for: the SG&A rises with no more clients to serve.',
      'Passivity: you repeated last year booth on the same budget, even though 6 clients will not go.']],

  ['m11c', 'An industrial plant disputes 3% of charges on 4 invoices, but keeps buying. Every disputed charge is money in limbo and the argument can wear the relationship down.',
    'Charges in dispute: 3%|Invoices disputed: 4|Client: industrial plant',
    ['Balanced: you reviewed the 4 invoices with the client and fixed only what was wrong: you are paid what is fair.',
      'Shortcut: you folded those charges into the list price of next invoices; the client will notice.',
      'Concession: you issued credit notes for the 3% on all 4 invoices: closed, but margin gives way.',
      'Passivity: you left the dispute open; the client held back payments and ended up demanding a bigger credit.']],
  ['m11p', 'Year-end brings 30% more hotel orders for the holidays, just when your people ask for vacation. Hands are short and the shifts are not enough.',
    'Year-end orders: +30%|Client: hotels in holidays|Leave requests: 12',
    ['Balanced: you rotated shifts with fair leave and a 3% bonus: it ships without burning out the team.',
      'Shortcut: you froze December leave and ran 3 shifts at full tilt: the team runs out of steam.',
      'Concession: you gave all the leave and tolerated 2 weeks of delay: some hotels did not wait.',
      'Passivity: you set shifts day by day and demand peaks caught you without people.']],
  ['m11e', 'A blockade of the main road halts your shipments for 3 weeks. There are 20 pending orders for industrial plants that depend on your deliveries.',
    'Pending orders: 20|Blockade: 3 weeks|Client: industrial plants',
    ['Balanced: you coordinated a detour with the client and talked to the neighbors: little extra cost.',
      'Shortcut: you billed the client for the blockade with a formal letter: income today, remembered tomorrow.',
      'Concession: you paid toll and escort to ship the 20 orders: you deliver, but freight eats the margin.',
      'Passivity: you paused shipments and waited for others to settle the blockade: 3 weeks without sales.']],
  ['m11s', 'Your sellers earn 3% on sales, whatever the margin. Some close big sales at very low prices and the commission eats what little is left.',
    'Current commission: 3% of sales|Sellers: 12|Margin on big sales: low',
    ['Balanced: you moved commission to margin with a 1% floor for 6 months: the margin rises.',
      'Shortcut: you raised everyone sales target 15%: volume moves today, but you push selling with no margin.',
      'Concession: you raised the commission to 4% to keep the best: the SG&A rises with no more margin.',
      'Passivity: you left the current scheme until the annual talks: they keep rewarding volume without margin.']],

  ['m12c', 'A large, loyal food plant offers a 3-year renewal, but at a fixed price with no inflation adjustment. Your input costs can rise; the price will not move.',
    'Contract: 36 months|Price: fixed, no adjustment|Client weight: 12% of your sales',
    ['Balanced: you accepted 36 months with a cap tied to input costs: sales and margin looked after.',
      'Shortcut: you signed at an initial price 3% above the market; the client can leave as soon as it can.',
      'Concession: you signed the 3 years as the client wrote them: sales secured, costs free to rise.',
      'Passivity: you let the offer lapse while legal reviewed; the client signed with another for 3 years.']],
  ['m12p', 'The year closes and 5% of the inventory looks obsolete before it is valued. A food plant has expiry dates and cannot wait to know what it is worth.',
    'Doubtful inventory: 5%|Year end: in 1 month|Client: food plants',
    ['Balanced: you counted, sold what is recoverable and wrote off the rest: a real write-off, on time.',
      'Red line: you left the obsolete stock at book value. It is misleading reporting: adjustment, fine and audit.',
      'Concession: you wrote off 12% at once, as Audit asked: the blow is bigger than needed.',
      'Passivity: you used the system figures and closed on time; the obsolete stock stayed unvalued.']],
  ['m12e', 'A truckers strike threatens your December shipments, 18% of the year sales. Hospitals cannot run out of supplies right in the holidays.',
    'December shipments: 18% of the year|Strike announced: 2 weeks|Client: hospitals',
    ['Balanced: you moved 40% of shipments ahead and booked 3 carriers: the strike did not reach you.',
      'Shortcut: you added 5% to shipments for the strike and explained after billing; clients complain.',
      'Concession: you approved whatever rate each carrier asked: everything shipped, at a steep freight.',
      'Passivity: you kept the plan with the trucks available and orders piled up and arrived late.']],
  ['m12s', 'One month to year end and your OI is 1 point below plan. Corporate watches the close and there are ways to improve the number that do not improve the business.',
    'Months left: 1|OI below plan: 1 point|Corporate goal: close on plan',
    ['Balanced: you froze 2 vacant positions and paused training unrelated to sales: the SG&A really falls.',
      'Red line: you booked January invoices in December. It is misleading accounting: fine and audit.',
      'Concession: you gave the team the full bonus although results fell short: more SG&A, no merit.',
      'Passivity: you closed as it came, touching nothing: the year ends 1 point below plan, unexplained.']],
];

const entries = ROWS.flatMap(([id, brief, facts, stories]) => [
  [`year.${id}.brief`, brief],
  [`year.${id}.facts`, facts],
  ...stories.map((story, i) => [`year.${id}.${ANSWERS[i]}.why`, story]),
]);

module.exports = Object.freeze(Object.fromEntries(entries));
