'use strict';

// Year mode, English. Same rows, same order and same answer order as year.es.js.

const ANSWERS = ['smart', 'temp', 'plac', 'ign'];

const ROWS = [
  ['m01c', 'Annual renewal', 'The mine demands a 3% rebate and 90-day payment to renew.',
    ['2-year contract', '1% rebate and 60-day payment, tied to savings we measure together.'],
    ['Accept and offset', 'You accept everything and quietly raise the price of other products.'],
    ['Give them all', '3% rebate and 90 days: the client leaves happy, you pay in margin.'],
    ['Wait for them', 'You do not answer until they decide; the contract is left hanging.']],
  ['m01p', 'Low inventory', 'The year starts with little stock of key inputs and big orders.',
    ['Staggered purchase', 'You buy in two lots and tell Sales which orders are certain.'],
    ['Run on what we have', 'You push the plant to the limit with tight inputs to save stock.'],
    ['Buy it all now', 'You buy the full inventory today: no risk, but at spot price.'],
    ['Watch and see', 'You do nothing until something runs out: we will see.']],
  ['m01e', 'Budget and the dollar', 'The dollar is volatile and the budget was set at one exchange rate.',
    ['Dollar adjustment', 'You agree a dollar adjustment with clients and buy some input forward.'],
    ['Raise prices now', 'You raise all prices 3% today, even if the contract does not allow it.'],
    ['Absorb the hit', 'You touch neither prices nor costs: the margin absorbs the volatility.'],
    ['Wait for the close', 'You leave it for the quarter close and see what happens.']],
  ['m01s', 'Measure or push', 'Corporate wants more volume; you could measure your clients\' savings.',
    ['Measure the savings', 'You document the client\'s water and reagent savings to negotiate later.'],
    ['Push volume', 'You sell more with discounts today; the client\'s savings stay unmeasured.'],
    ['Corporate\'s plan', 'You apply corporate\'s plan as asked, without questioning it.'],
    ['Leave it for later', 'You postpone both ideas: the year is already running.']],

  ['m02c', 'Spec change', 'The client asks to change the product spec with two weeks\' notice.',
    ['Pilot and timeline', 'You run a short trial and agree realistic dates with the client.'],
    ['Change untested', 'You change the formula with what is in the warehouse to meet the date.'],
    ['Say yes to all', 'You accept the date and the spec, and absorb the extra cost.'],
    ['Answer later', 'You leave the request unanswered and the client keeps waiting.']],
  ['m02p', 'Maintenance vs orders', 'The major line maintenance is due, but there are urgent orders.',
    ['Phased maintenance', 'You stop half the line at a time and split the urgent orders.'],
    ['Delay maintenance', 'You meet every order now and leave the maintenance for later.'],
    ['Stop the plant', 'You stop the whole line for 3 days: perfect plant, orders waiting.'],
    ['Carry on as is', 'You do not decide: maintenance slips and orders ship as they can.']],
  ['m02e', 'Altiplano rains', 'The rains cut the road to the site and shipments are pending.',
    ['Detour', 'You take a longer route, warn the client and prioritize what is critical.'],
    ['Ship anyway', 'You send the trucks on the risky road to hit the date.'],
    ['Air freight for all', 'You ship everything urgent: the client does not wait, you pay the freight.'],
    ['Wait for it to pass', 'You stop shipments until the road reopens.']],
  ['m02s', 'Aggressive forecast', 'Corporate asks to raise the yearly forecast by 8% for the meeting.',
    ['Ranged forecast', 'You give a base and an upside case, with the assumptions made clear.'],
    ['Inflate the number', 'You raise the number to look good today; we will see later.'],
    ['Accept the ask', 'You accept the 8% and commit the team without discussing assumptions.'],
    ['Do not answer', 'You delay the forecast until corporate insists.']],

  ['m03c', 'Off-spec batch', 'The client complains about a batch that came out off specification.',
    ['Own it and replace', 'You admit the error, replace the batch and share the root-cause analysis.'],
    ['Blame the freight', 'You say transport caused the damage to avoid paying the replacement.'],
    ['Big discount', 'You offer 10% off the next order without investigating.'],
    ['Wait for the claim', 'You do not answer until the claim arrives formally.']],
  ['m03p', 'Breakdown and shortage', 'A pump on the line fails and a key raw material runs short.',
    ['Prioritize orders', 'You rank orders by criticality and buy the pump from a local supplier.'],
    ['Patch it up', 'You make a temporary repair and keep producing so as not to stop.'],
    ['Pay for urgency', 'You buy everything urgent at any price so as not to fall behind.'],
    ['Wait for parts', 'You do nothing until the supplier shows up with spare parts.']],
  ['m03e', 'Tax reform', 'A mining tax reform is announced and clients turn cautious.',
    ['Map scenarios', 'You talk through each client\'s buying scenarios and adjust the plan.'],
    ['Pull sales forward', 'You push clients to buy today with discounts before the reform.'],
    ['Freeze prices', 'You freeze this year\'s prices to calm every client.'],
    ['Wait and see', 'You do nothing until the reform is approved.']],
  ['m03s', 'Water product', 'There is an opportunity: a water-saving program for mines.',
    ['Narrow pilot', 'You test it with a friendly client and measure results before scaling.'],
    ['Launch untested', 'You offer it to everyone right away to sell more this year.'],
    ['Wait for approval', 'You do not move until corporate approves the whole budget.'],
    ['Let it go', 'You prioritize the usual and the program stays in a drawer.']],

  ['m04c', 'Budget cut', 'The client cuts its input budget and asks for lower prices.',
    ['Lower their usage', 'You adjust dosing with the client to cut its cost without cutting your price.'],
    ['Hidden increases', 'You cut the main product price and raise the price of services.'],
    ['Cut the price', 'You discount the whole contract 5% so the client stays.'],
    ['Keep the offer', 'You change nothing and hope the client gets used to it.']],
  ['m04p', 'Operator turnover', 'Two key operators leave and the shifts are left short.',
    ['Relief plan', 'You train two juniors and reorganize shifts meanwhile.'],
    ['Overtime', 'You ask the remaining team for double shifts to avoid hiring.'],
    ['Raise wages', 'You raise the whole shift\'s pay so nobody else leaves.'],
    ['Leave the gaps', 'You replace no one and trust the shifts to sort themselves out.']],
  ['m04e', 'Mining royalty', 'A higher royalty passes and the mines review every contract.',
    ['Value-based deals', 'You propose contracts tied to the savings you create, not volume.'],
    ['Squeeze the captive', 'You raise prices on clients with no alternative supplier.'],
    ['Offer discounts', 'You give preventive discounts to all before they ask.'],
    ['Wait for the review', 'You do not move until each mine asks to renegotiate.']],
  ['m04s', 'SG&A cut', 'Corporate asks to cut SG&A by 5% right away.',
    ['Selective cut', 'You cut spend that does not touch clients and protect visits and data.'],
    ['Flat cut', 'You cut everything 5% evenly, including what holds up the service.'],
    ['Ask for exemption', 'You argue it cannot be done and ask to postpone the cut to next year.'],
    ['Do not execute', 'You leave the order on hold and keep spending as usual.']],

  ['m05c', 'Free visits', 'The client asks for weekly service visits at no extra charge.',
    ['Visits on demand', 'You offer remote monitoring and visits only when the data calls for them.'],
    ['Send a junior', 'You say yes but send an inexperienced junior technician.'],
    ['Every visit', 'You accept full weekly visits and absorb the service cost.'],
    ['Do not reply', 'You do not answer and the client complains to your boss.']],
  ['m05p', 'Safety incident', 'There is an incident without injuries at the plant and an audit is coming.',
    ['Investigate', 'You stop the area, find the cause and correct the procedure.'],
    ['Close it fast', 'You close the report with no changes to avoid losing output.'],
    ['Stop everything', 'You stop the plant for a week to review everything from scratch.'],
    ['Let it go', 'Since nobody was hurt, you keep working as usual.']],
  ['m05e', 'Copper falls', 'The copper price drops and mines freeze non-essential purchases.',
    ['Cut their cost', 'You offer a program that lowers your client\'s cost per ton.'],
    ['Charge the rest', 'You raise your prices for the clients that keep buying.'],
    ['Extend their terms', 'You give everyone longer payment terms to help them through the cycle.'],
    ['Wait it out', 'You change nothing and wait for copper to rise again.']],
  ['m05s', 'Remote monitoring', 'You can invest in remote monitoring for several sites.',
    ['Invest in stages', 'You install at the two biggest sites and measure the savings in visits.'],
    ['Cut the investment', 'You cancel the investment and trim visits to raise the margin.'],
    ['Invest everywhere', 'You install at every site at once, even if it is not proven.'],
    ['Think it over', 'You keep evaluating without deciding and visits keep costing the same.']],

  ['m06c', 'Competitor 8% lower', 'A competitor offers 8% less and threatens to take your contract.',
    ['Show the savings', 'You present the measured savings and propose a 2-year contract.'],
    ['Raise the exit bar', 'You lock the client in with a long contract with exit penalties.'],
    ['Match the price', 'You cut 8% and keep everything else to avoid losing the contract.'],
    ['Trust the bond', 'You do nothing: you assume they will stay loyal for years.']],
  ['m06p', 'Quality drift', 'Several batches come out at the edge of spec this week.',
    ['Tune the process', 'You adjust the process with the team and reinforce controls.'],
    ['Blend batches', 'You mix good batches with doubtful ones so the average passes.'],
    ['More testing', 'You add checks to every batch: slow and expensive.'],
    ['Look later', 'You wait to see whether any client complains.']],
  ['m06e', 'Water regulation', 'A new environmental rule limits water use at the sites.',
    ['Savings program', 'You propose a water-reuse program that helps the client comply.'],
    ['Sell compliance', 'You offer a turnkey package at a high price, untested.'],
    ['Free diagnostics', 'You run free diagnostics for everyone to win their trust.'],
    ['Let them handle it', 'You wait for each client to ask for help on its own.']],
  ['m06s', 'New country', 'A big client appears in another country, with new requirements.',
    ['Local partner', 'You enter with a local distributor and limit the first investment.'],
    ['Enter fast', 'You serve from here with high prices and no local presence.'],
    ['Whatever they ask', 'You accept all their requirements and contracts on day one.'],
    ['Do not reply', 'You do not answer the inquiry and the client goes elsewhere.']],

  ['m07c', 'Cost audit', 'The client asks to audit your costs to review your margin.',
    ['Open with rules', 'You show your service costs and agree on how they are compared.'],
    ['Show only part', 'You hand over only the part that suits you and hide the rest.'],
    ['Open everything', 'You hand over all your costs and agree to cut your margin.'],
    ['Postpone the audit', 'You answer that now is not possible and let it slide.']],
  ['m07p', 'Late supplier', 'Your only supplier is three weeks late on a critical input.',
    ['Second supplier', 'You qualify a second supplier and use stock to cover the gap.'],
    ['Swap the input', 'You switch to a cheaper input without telling the client.'],
    ['Air-freight it', 'You fly the input in at any price.'],
    ['Wait and see', 'There is no plan B: you wait for the supplier to deliver.']],
  ['m07e', 'Snowstorm', 'A snowstorm closes the pass to the sites for a week.',
    ['Stock on site', 'You move stock into the client\'s warehouse and reschedule shipments.'],
    ['Send it anyway', 'You send trucks in the calm window even if it is risky.'],
    ['Helicopter', 'You cover the critical items with very costly air deliveries.'],
    ['Wait for the thaw', 'You stop everything and wait for the pass to open.']],
  ['m07s', 'Reorganization', 'Corporate proposes reorganizing the team and cutting headcount 10%.',
    ['Redesign roles', 'You reassign duties and automate tasks before cutting people.'],
    ['Flat headcount cut', 'You cut 10% evenly and assume the service will cope.'],
    ['Keep everyone', 'You keep the headcount and ask for time to improve.'],
    ['Do not decide', 'You leave the reorganization with no owner and no date.']],

  ['m08c', 'New buyer', 'A new procurement head arrives and wants to tender everything.',
    ['Value meeting', 'You present measured results and propose a joint improvement.'],
    ['Pay upfront', 'You ask for payment in advance to cut your risk.'],
    ['Bid the lowest', 'You enter the tender with the lowest price possible.'],
    ['Wait for the tender', 'You do nothing until the invitation arrives.']],
  ['m08p', 'Capacity at the limit', 'Demand exceeds plant capacity for three months.',
    ['Extra shift', 'You add a planned shift and prioritize by margin.'],
    ['Nonstop running', 'You run with no maintenance breaks to squeeze out more.'],
    ['Accept every order', 'You accept all orders even if they arrive late.'],
    ['See what happens', 'You change nothing and orders pile up.']],
  ['m08e', 'Dollar jumps', 'The dollar rises 10% and so does your imported input cost.',
    ['Phased pass-through', 'You pass part of the rise on with notice and buy the rest forward.'],
    ['Raise it all now', 'You raise prices 10% for everyone without notice.'],
    ['Absorb the rise', 'You hold prices and absorb the whole increase.'],
    ['Watch the dollar', 'You wait to see if the dollar falls by itself.']],
  ['m08s', 'Distributor deal', 'A distributor offers to cover small clients for a commission.',
    ['6-month pilot', 'You test with 10 small clients and measure service and margin.'],
    ['Hand over all', 'You hand over every small client to cut your costs.'],
    ['Accept their terms', 'You accept the commission they ask without negotiating.'],
    ['Reject the offer', 'You say no without looking at the numbers.']],

  ['m09c', '120-day terms', 'The client asks for 120-day payment and your cash is tight.',
    ['Terms with discount', 'You offer 90 days with a small discount for early payment.'],
    ['Raise the price', 'You accept 120 days and raise the price to cover the cost.'],
    ['Give the 120 days', 'You accept the requested terms with no conditions.'],
    ['Do not reply', 'You do not answer and the order is paused.']],
  ['m09p', 'Regulatory audit', 'A regulatory audit arrives, focused on your storage.',
    ['Prepare in time', 'You prepare the paperwork and fix the minor items before the visit.'],
    ['Dress up the store', 'You tidy only what is visible to pass the audit.'],
    ['Stop and redo', 'You stop everything to rebuild the warehouse completely.'],
    ['Trust luck', 'You prepare nothing: it always goes fine.']],
  ['m09e', 'Elections', 'Elections are coming and clients freeze investment out of uncertainty.',
    ['Flexible contracts', 'You offer contracts with clear exits to give peace of mind.'],
    ['Push closings', 'You press clients to sign now with heavy discounts.'],
    ['Follow their pace', 'You accept any timing they ask for without proposing anything.'],
    ['Wait for the vote', 'You leave everything on hold until the result.']],
  ['m09s', 'Buy the supplier', 'You could buy your key supplier to secure inputs.',
    ['3-year contract', 'You negotiate supply and price for 3 years without buying the firm.'],
    ['Buy it with debt', 'You buy with debt to cut costs quickly.'],
    ['Buy nothing', 'You avoid the risk and stay with a single supplier.'],
    ['Keep evaluating', 'You postpone a decision that is already a year old.']],

  ['m10c', 'Consignment', 'The client asks for stock on consignment inside its site.',
    ['Capped consignment', 'You accept a capped volume with replenishment and monthly reports.'],
    ['Bill on arrival', 'You invoice the stock as it arrives and leave the risk with the client.'],
    ['Consign it all', 'You leave all the stock they ask for, uncontrolled.'],
    ['Refuse', 'You say it cannot be done and offer no alternative.']],
  ['m10p', 'Partial strike', 'The union announces a partial strike over the year-end bonus.',
    ['Negotiate with data', 'You show the real results and agree a bonus tied to targets.'],
    ['Hire replacements', 'You hire temporary replacements to break the strike.'],
    ['Pay the bonus', 'You pay the full bonus asked for to avoid the strike.'],
    ['Wait for the strike', 'You do not reply and let the strike move forward.']],
  ['m10e', 'Drought', 'A drought forces the mine to cut its water use.',
    ['Water program', 'You propose a reuse program with measured savings and pay for results.'],
    ['Charge the urgency', 'You raise prices taking advantage of the client\'s urgency.'],
    ['Give it away', 'You hand over the program for free to win their trust.'],
    ['Not our topic', 'You say it is the client\'s issue and offer no help.']],
  ['m10s', 'Next year\'s budget', 'Corporate asks for next year\'s budget with high growth.',
    ['A real budget', 'You present growth with the concrete levers that sustain it.'],
    ['Inflate the plan', 'You deliver the growth asked for with no support.'],
    ['Safe plan', 'You present a low budget to stay comfortable.'],
    ['Copy last year\'s', 'You repeat last year\'s budget with an inflation adjustment.']],

  ['m11c', 'Late payments', 'The client pays late due to cash problems and asks to keep buying.',
    ['Payment schedule', 'You agree a payment calendar and cap the credit meanwhile.'],
    ['Cut the shipments', 'You stop shipments at once without talking to the client.'],
    ['Keep shipping', 'You ship anyway and hope they pay someday.'],
    ['Do not chase', 'You do not follow up and the debt grows.']],
  ['m11p', 'Year-end shifts', 'Year-end brings high orders and people who want holidays.',
    ['Rotating shifts', 'You build rotating shifts with fair leave and a small bonus.'],
    ['Cancel holidays', 'You cancel all holidays to meet the orders.'],
    ['Grant all holidays', 'You grant every leave asked for and accept delays.'],
    ['No plan', 'You do not plan and shifts are built on the day.']],
  ['m11e', 'Road blockade', 'Communities block the road and sales stop for three weeks.',
    ['Joint plan', 'You coordinate routes and hours with the client, plus a community table.'],
    ['Charge the delay', 'You bill the client the blockade costs without talking first.'],
    ['Pay to pass', 'You pay for passage and escort to fill every order.'],
    ['Wait for dialogue', 'You stop everything until others resolve the conflict.']],
  ['m11s', 'Big deal abroad', 'A big contract is offered abroad, but your plant is at its limit.',
    ['Phased delivery', 'You accept with phased deliveries and an agreed expansion.'],
    ['Promise it all', 'You accept the whole volume and figure out how to deliver.'],
    ['Turn it down', 'You say no to protect your current clients.'],
    ['No answer', 'You leave the offer unanswered until January.']],

  ['m12c', 'Fixed-price contract', 'The client offers a 3-year contract at a fixed price, no adjustment.',
    ['Fixed with a floor', 'You accept the term with a minimal adjustment tied to costs.'],
    ['Raise, then sign', 'You raise the base price before signing the fixed contract.'],
    ['Sign as is', 'You sign the fixed contract exactly as the client asks.'],
    ['Take no stance', 'You leave the offer unanswered and it expires.']],
  ['m12p', 'Inventory close', 'The year ends: you must decide how to value and close inventory.',
    ['Count and adjust', 'You do a physical count and write off what does not exist.'],
    ['Postpone write-offs', 'You leave the bad adjustments for next year.'],
    ['Write off it all', 'You write off everything doubtful at once, even too much.'],
    ['Close uncounted', 'You close with the system numbers, with no review.']],
  ['m12e', 'Truckers\' strike', 'A truckers\' strike threatens December shipments.',
    ['Ship early', 'You move shipments forward and coordinate routes with other carriers.'],
    ['Charge a surcharge', 'You bill clients high surcharges without notice.'],
    ['Pay what they ask', 'You accept the cost of any carrier that is available.'],
    ['Wait out the strike', 'You do nothing and orders pile up.']],
  ['m12s', 'Year-end close', 'The close is near: push the numbers or close clean?',
    ['Close clean', 'You close with the real numbers and present a clear plan for January.'],
    ['Dress up the close', 'You pull invoices forward and defer costs to hit the number.'],
    ['Lower the target', 'You ask to lower the target so you can reach it comfortably.'],
    ['See what comes out', 'You do nothing special and look at the result.']],
];

const entries = ROWS.flatMap(([id, title, scene, ...answers]) => [
  [`year.${id}.title`, title],
  [`year.${id}.scene`, scene],
  ...answers.flatMap(([name, desc], i) => [
    [`year.${id}.${ANSWERS[i]}.name`, name],
    [`year.${id}.${ANSWERS[i]}.desc`, desc],
  ]),
]);

module.exports = Object.freeze(Object.fromEntries(entries));
