'use strict';

// The case of each problem, Spanish: what the player reads before deciding and what happens after each answer.
//   [id, brief, 'fact|fact|fact', [smart story, temp story, plac story, ign story]]
// Every story opens with the kind of answer it was ("Equilibrada:", "Atajo:", "Cesión:", "Pasividad:"); a red line
// opens with "Línea roja:". tests/year-case.test.js keeps the lengths and the openings honest.

const ANSWERS = ['smart', 'temp', 'plac', 'ign'];

const ROWS = [
  ['m01c', 'Una cadena de 6 hoteles te compra higiene y lavandería en todas sus sedes. Su contrato vence en 20 días y un competidor ya les cotizó. Gerencia comercial quiere cerrar rápido.',
    'Cliente: cadena de 6 hoteles|Peso: 18% de tus ventas|Margen del cliente: 38%',
    ['Equilibrada: el hotel firmó 2 años; el rebate de 1% cuesta poco y asegura 18% de tus ventas.',
      'Atajo: aceptaste el 3% y lo cobraste en otros productos; el OI sube hoy y el hotel lo notará.',
      'Cesión: renovaste cediendo el 3% completo. Quedó el cliente, pero ese rebate es margen que no vuelve.',
      'Pasividad: el contrato venció en 20 días y el hotel cotizó con otro proveedor: perdiste volumen.']],
  ['m01p', 'Enero es temporada alta: las cadenas hoteleras duplican su consumo de lavandería e higiene. Tu proveedor clave entrega en 20 días y la bodega tiene insumo para 3 semanas.',
    'Cliente: hoteles en temporada alta|Pedidos de enero: +40%|Insumo en bodega: 3 semanas',
    ['Equilibrada: compraste en dos lotes y avisaste los pedidos firmes; sin precio spot ni bodega llena.',
      'Atajo: la planta rindió 110% y evitaste la compra cara; el desgaste de las líneas se paga después.',
      'Cesión: compraste 3 meses a precio spot. Atendiste todo, con la bodega llena y el costo más alto del año.',
      'Pasividad: esperaste y en enero faltó insumo; perdiste pedidos de temporada alta y compraste de emergencia.']],
  ['m01e', 'Una planta industrial compra con contratos que fijan el precio por 12 meses, pero 40% de tus insumos se importan en dólares. El dólar ya está 7% sobre el presupuesto.',
    'Cliente: plantas industriales|Insumos importados: 40%|Dólar sobre presupuesto: +7%',
    ['Equilibrada: pactaste el reajuste por escrito y cubriste la mitad de la compra; el margen queda protegido.',
      'Línea roja: subiste un precio fijado por contrato. Es incumplimiento: multa y clientes en contra.',
      'Cesión: dejaste precios y compras como estaban y el margen pagó el alza del dólar completa.',
      'Pasividad: esperaste el cierre para analizar y el dólar siguió subiendo sobre un costo sin cubrir.']],
  ['m01s', 'Tu programa de higiene hospitalaria reduce infecciones, pero nadie ha medido cuánto ahorra a cada hospital. Corporativo quiere 6% más de volumen y los comités de compras piden evidencia.',
    'Cliente: red de hospitales|Meta de corporativo: +6% volumen|Ahorro medido: ninguno',
    ['Equilibrada: mediste el ahorro en 3 hospitales y ahora negocias con datos; esa evidencia sostiene tus precios.',
      'Atajo: el descuento da volumen hoy, pero sin ahorro medido solo se compara precio; la cuenta llega.',
      'Cesión: ejecutaste el plan de volumen sin medir nada; empujas ventas sin poder defender tu precio.',
      'Pasividad: postergaste el volumen y la medición; sin evidencia ni ventas extra, el año parte sin ritmo.']],

  ['m02c', 'Una planta procesadora de alimentos cambia su línea de envasado y pide otra fórmula de sanitizante con solo 2 semanas de aviso. Su auditor de inocuidad revisará el cambio.',
    'Cliente: planta de alimentos|Peso: 12% de tus ventas|Aviso: 2 semanas',
    ['Equilibrada: la prueba de 3 días evitó un lote rechazado y acordaste una fecha realista con su auditor.',
      'Atajo: usaste stock de bodega y despachaste a tiempo; si la fórmula no pasa su auditoría, hay reclamo.',
      'Cesión: aceptaste las 2 semanas y absorbiste el costo extra: el cliente quedó contento y el margen pagó.',
      'Pasividad: tardaste una semana en responder y la planta cotizó la fórmula con otro proveedor.']],
  ['m02p', 'La línea de desinfectantes necesita su mantención mayor: 4 días parada. Dos hospitales pidieron despachos urgentes por un brote y no aceptan atrasos.',
    'Cliente: hospitales con brote|Pedidos urgentes: 5|Línea parada: 4 días',
    ['Equilibrada: la mantención por turnos cubrió los pedidos críticos de los hospitales y evitó una falla mayor.',
      'Atajo: postergaste la mantención 8 semanas y atendiste todo este mes; el riesgo de falla queda sobre la planta.',
      'Cesión: paraste 4 días y pediste esperar: mantención al día, pero los hospitales sufrieron atrasos.',
      'Pasividad: respetaste el calendario y solo entraron 2 de 5 pedidos urgentes; los otros 3 se perdieron.']],
  ['m02e', 'Un temporal corta los caminos del litoral y 14 despachos a hoteles de playa están pendientes en plena temporada. Un hotel sin ropa limpia ni insumos de higiene no puede operar.',
    'Cliente: hoteles de la costa|Despachos pendientes: 14|Camino cortado: 1 semana',
    ['Equilibrada: la ruta interior cuesta más flete, pero entregaste lo crítico y no perdiste ventas.',
      'Atajo: mandaste los camiones por el camino dañado y llegaste; el riesgo y el desgaste se pagan después.',
      'Cesión: los camiones 4x4 a triple tarifa cumplieron todas las fechas, con el flete más caro del año.',
      'Pasividad: detuviste los despachos una semana: ahorraste flete, pero perdiste las ventas de esos 14 pedidos.']],
  ['m02s', 'Corporativo necesita subir 8% el pronóstico del año para presentarlo a los inversionistas el lunes. Tu caso base ya es exigente y varias plantas clientes recortaron producción.',
    'Cliente: plantas industriales|Aumento pedido: +8%|Reunión: el lunes',
    ['Equilibrada: diste un caso base y uno optimista, explicados: corporativo planifica con datos creíbles.',
      'Línea roja: inflaste el pronóstico. Es información engañosa: multa, auditoría y pérdida de confianza.',
      'Cesión: aceptaste el +8% y lo repartiste; la presión sube el gasto de venta y bajan los medidores.',
      'Pasividad: enviaste el pronóstico tarde, con cifras viejas; corporativo asignó recursos sin ti.']],

  ['m03c', 'Una planta industrial reclama 40 toneladas de producto fuera de especificación, que detuvieron una de sus líneas por un día. Su gerente de planta pide una respuesta hoy.',
    'Cliente: planta industrial|Lote reclamado: 40 toneladas|Respuesta pedida: hoy',
    ['Equilibrada: repusiste las 40 toneladas y compartiste el análisis: cuesta, pero evitas otro reclamo.',
      'Atajo: culpar al transporte y reponer a medias ahorra hoy; si lo desmienten, pierdes su confianza.',
      'Cesión: el descuento de 10% cerró el reclamo en el día, pero regalaste margen sin corregir la causa.',
      'Pasividad: respondiste en 15 días y el reclamo formal sumó costos de gestión y un cliente molesto.']],
  ['m03p', 'Falla una bomba de la línea 2 y solo quedan 5 días de una materia prima clave. Los pedidos más críticos son de hospitales que no pueden quedarse sin desinfectante.',
    'Cliente: hospitales (pedidos críticos)|Materia prima: 5 días|Línea 2: detenida',
    ['Equilibrada: priorizaste pedidos críticos con lo que quedaba y compraste la bomba sin pagar de más.',
      'Atajo: el parche te mantuvo a plena carga 2 días; si vuelve a fallar, la línea se detiene en el peor momento.',
      'Cesión: compraste bomba y materia prima en 24 horas a cualquier precio: servicio al costo más alto.',
      'Pasividad: paraste la línea a esperar repuestos: pedidos críticos atrasados y costos de planta detenida.']],
  ['m03e', 'La autoridad sanitaria publica un borrador de norma con más controles en hospitales. Tres de tus mayores clientes congelan compras hasta ver el texto final, en 2 meses.',
    'Cliente: hospitales y clínicas|Clientes que frenan: 3|Norma final: en 2 meses',
    ['Equilibrada: conversaste con cada cliente sus escenarios y diste descuento solo a pedidos firmes.',
      'Atajo: adelantaste ventas con 5% de descuento; el trimestre mejora, pero esos pedidos ya no llegan después.',
      'Cesión: congelaste precios 12 meses para tranquilizar; los clientes siguen firmes y tu margen queda sin reajuste.',
      'Pasividad: esperaste el texto final y mientras tanto los pedidos de los 3 clientes siguieron frenados.']],
  ['m03s', 'Cinco plantas de alimentos preguntaron por un programa que reduce el agua de sus lavados y enjuagues. Es un servicio nuevo: hay demanda, pero nadie lo ha probado en una planta de tu cartera.',
    'Cliente: plantas de alimentos|Plantas interesadas: 5|Servicio: nuevo, sin pilotos',
    ['Equilibrada: el piloto de 3 meses con un cliente amigo cuesta servicio hoy y deja un resultado medido para escalar.',
      'Atajo: vendiste a las 5 plantas prometiendo resultados: ventas hoy, reclamos si no se cumplen.',
      'Cesión: armaste la propuesta y esperas aprobación; el gasto comercial corre y las ventas aún no.',
      'Pasividad: dejaste el programa para otra oportunidad y las 5 plantas preguntaron a otro proveedor.']],

  ['m04c', 'Una red de hospitales recorta 10% su presupuesto de insumos por un ajuste de salud y pide bajar los precios. Tiene otros proveedores a mano y su comité decide en 30 días.',
    'Cliente: red de hospitales|Peso: 10% de tus ventas|Presupuesto del cliente: -10%',
    ['Equilibrada: el hospital gasta menos y paga un servicio por el ahorro; se queda y tu margen se cuida.',
      'Atajo: bajaste el producto y subiste los servicios; el trato cierra, pero el cliente verá el recargo.',
      'Cesión: rebajaste 5% por 12 meses y el cliente se quedó; ese descuento se paga todo el año.',
      'Pasividad: mantuviste los términos y en 30 días el comité movió parte del volumen a otro proveedor.']],
  ['m04p', 'Dos de tus 9 operadores clave renunciaron para irse a la competencia y los turnos de la línea de dosificación quedan incompletos. Reemplazarlos toma meses de capacitación.',
    'Cliente: plantas industriales|Operadores que se van: 2 de 9|Reemplazo: 6 semanas de práctica',
    ['Equilibrada: capacitaste a dos jóvenes y reordenaste turnos; cuesta hoy, pero se acaban las horas extra.',
      'Atajo: los turnos dobles sostienen la producción un trimestre; el equipo se desgasta y otros pueden irse.',
      'Cesión: el alza de 8% frenó las renuncias, pero el costo de mano de obra sube para siempre.',
      'Pasividad: dejaste los cupos vacantes: bajó la nómina, pero la producción y la calidad se resintieron.']],
  ['m04e', 'Un nuevo impuesto verde encarece la energía de tus clientes industriales y todos revisan sus contratos de insumos para recortar costos. Algunos no tienen otro proveedor calificado.',
    'Cliente: plantas industriales|Clientes que renegocian: 8|Sin otro proveedor calificado: 3',
    ['Equilibrada: contratos atados al ahorro que generas: el cliente paga por valor y tú proteges el margen.',
      'Atajo: subiste 6% a los cautivos y el OI sube hoy; en cuanto califiquen a otro proveedor, se irán.',
      'Cesión: ofreciste 3% antes de que lo pidieran: fidelizaste, pero regalaste margen que no te exigían.',
      'Pasividad: renegociaste a la defensiva, contrato por contrato, y los clientes impusieron sus precios.']],
  ['m04s', 'Corporativo pide bajar 5% el SG&A desde el próximo mes para proteger el margen del grupo. Tu equipo ya viene justo y las visitas a clientes y la medición del valor dependen de ese presupuesto.',
    'Cliente: plantas industriales|Recorte pedido: 5% del SG&A|Plazo: desde el próximo mes',
    ['Equilibrada: recortaste viajes y consultorías y protegiste visitas y medición: menos SG&A, mismas ventas.',
      'Atajo: recortaste todo 5% parejo: cumples la meta, pero también cortaste lo que sostiene las ventas.',
      'Cesión: pediste una excepción y el SG&A no baja; corporativo anota que no cumpliste el recorte.',
      'Pasividad: llevaste la orden a la reunión de fin de trimestre y mientras tanto el SG&A siguió igual.']],

  ['m05c', 'Un hospital grande pide una visita técnica semanal para auditar la dosificación, sin pagar más. Cada visita cuesta horas de tu equipo y otros hospitales podrían pedir lo mismo.',
    'Cliente: hospital grande|Peso: 9% de tus ventas|Visitas pedidas: 4 por mes',
    ['Equilibrada: el monitoreo evita visitas de más: hospital atendido y menos Direct Chg.',
      'Atajo: un técnico junior cuesta 40% menos, pero en un hospital un error de dosis pega fuerte después.',
      'Cesión: 4 visitas por mes a tu cuenta: hospital contento, y los Direct Chg suben sin ingreso a cambio.',
      'Pasividad: tardaste 20 días en responder y el hospital sintió que su servicio no importaba.']],
  ['m05p', 'Hay una fuga de producto en tu planta de sanitizantes: sin heridos, pero el procedimiento falló. En 10 días llega la auditoría de seguridad de un cliente de alimentos.',
    'Cliente: industria de alimentos|Auditoría: en 10 días|Pedidos en curso: 120',
    ['Equilibrada: paraste la zona 2 días y corregiste el procedimiento; la auditoría te encuentra al día.',
      'Línea roja: cerraste como menor un incidente real. Ocultarlo es grave: sanción y auditoría en contra.',
      'Cesión: paraste 7 días y rehiciste todo: seguridad impecable, pero con pedidos atrasados y costo alto.',
      'Pasividad: seguiste produciendo sin investigar: la auditoría encuentra el procedimiento roto.']],
  ['m05e', 'Una caída de 15% en el turismo baja la ocupación de los hoteles. Las cadenas congelan las compras que no son esenciales y piden mejores condiciones a todos sus proveedores.',
    'Cliente: cadenas hoteleras|Caída del turismo: -15%|Compras congeladas: no esenciales',
    ['Equilibrada: el rebate solo premia el volumen sobre su mínimo: cuesta poco y mantiene los pedidos.',
      'Atajo: cobraste más a quien sigue comprando y recortaste su rebate; hoy sube el OI, mañana lo recuerdan.',
      'Cesión: 3% de rebate a todos: no frenan compras, pero regalas margen también a quien compraba igual.',
      'Pasividad: esperaste el rebote del turismo mientras los hoteles seguían recortando pedidos.']],
  ['m05s', 'El monitoreo remoto reemplaza las visitas mensuales a 6 plantas clientes. El equipo es una inversión: se deprecia en años, pero la instalación y el servicio cuestan este año.',
    'Cliente: 6 plantas industriales|Inversión total: US$ 0,8 M|Visitas hoy: 1 por mes',
    ['Equilibrada: instalaste en 2 plantas y mides el ahorro en visitas antes de comprometer las otras 4.',
      'Atajo: cancelaste la inversión y recortaste visitas: el margen mejora hoy, pero el servicio se resiente.',
      'Cesión: instalaste en las 6 sin probar; el costo pesa ahora y el ahorro es incierto.',
      'Pasividad: evaluaste 3 meses más y las visitas siguieron costando lo mismo; el ahorro se pospuso.']],

  ['m06c', 'Un competidor ofrece 8% menos a una cadena hotelera que pesa 14% de tus ventas. El comprador valora tu servicio, pero la gerencia general presiona por bajar el costo de los insumos.',
    'Cliente: cadena hotelera|Peso: 14% de tus ventas|Oferta rival: 8% menos',
    ['Equilibrada: mostraste el ahorro medido y defendiste el precio con un rebate a 2 años; el hotel se queda.',
      'Atajo: el contrato de 3 años con multas de salida retiene al cliente hoy, pero resentido y atado.',
      'Cesión: igualaste el 8% menos todo el contrato: conservas al hotel y el margen cae cada mes.',
      'Pasividad: diste por segura su lealtad y el hotel movió parte del contrato al competidor.']],
  ['m06p', 'Esta semana 4 de 10 lotes de desinfectante salen al límite de la especificación. Los hospitales exigen certificado de calidad por lote y un lote dudoso puede costar una auditoría.',
    'Cliente: hospitales|Lotes al límite: 4 de 10|Certificado: por cada lote',
    ['Equilibrada: ajustaste el proceso y reforzaste controles: lotes en rango y certificados reales.',
      'Línea roja: mezclaste lotes dudosos con buenos para que pasen. Es fraude de calidad: retiro y sanción.',
      'Cesión: agregaste pruebas a cada lote y la liberación tarda 2 días más: calidad firme, costo y atrasos.',
      'Pasividad: despachaste los 4 lotes sin reforzar nada: cuando un hospital reclame, será por escrito.']],
  ['m06e', 'Una norma ambiental obliga a las plantas de alimentos a usar 20% menos agua. Tus clientes necesitan soluciones ya y todos los competidores están ofreciendo programas.',
    'Cliente: plantas de alimentos|Recorte de agua exigido: 20%|Plazo para cumplir: 6 meses',
    ['Equilibrada: el programa de reuso con pago por m3 ahorrado alinea tu ingreso con el ahorro del cliente.',
      'Atajo: vendiste un paquete sin probar y firmaste 3 contratos; si falla, el reclamo es tuyo.',
      'Cesión: los diagnósticos gratis ganan confianza, pero el servicio sin cobrar suma Direct Chg sin ventas.',
      'Pasividad: ayudaste solo a quien pidió y en 10 días varios clientes ya habían contratado a otro.']],
  ['m06s', 'Una cadena hotelera con sedes en otro país te pide cotizar higiene para sus hoteles allá. Mercado nuevo: sin distribuidor, sin precios de referencia y con requisitos locales.',
    'Cliente: cadena hotelera extranjera|Plazo para cotizar: 30 días|Presencia local: ninguna',
    ['Equilibrada: entraste con distribuidor local y acotaste la inversión: ventas nuevas, riesgo bajo.',
      'Atajo: atiendes a distancia con precios 15% altos: ganas margen hoy y el cliente verá un servicio frágil.',
      'Cesión: asumiste todos sus requisitos desde el inicio: el SG&A parte antes que las ventas.',
      'Pasividad: cotizaste a los 45 días y el cliente ya había elegido a otro proveedor.']],

  ['m07c', 'Una planta industrial que pesa 11% de tus ventas pide auditar tus costos y tu margen antes de renovar. Su comprador sospecha que el flete y el servicio vienen inflados.',
    'Cliente: planta industrial|Peso: 11% de tus ventas|Pedido: auditar costos y margen',
    ['Equilibrada: abriste flete y Direct Chg con reglas claras; el cliente ve el valor y no pide más rebaja.',
      'Atajo: mostraste solo los costos que te favorecen; si el cliente cruza datos, pierdes su confianza.',
      'Cesión: abriste todo y aceptaste bajar 2 puntos de margen sin discutir el valor que entregas.',
      'Pasividad: postergaste la auditoría 6 meses y el cliente asumió que escondías algo: compró menos.']],
  ['m07p', 'Tu único proveedor de un insumo que pesa 30% del costo avisa un atraso de 3 semanas. Una planta de alimentos espera tus pedidos y no acepta entregas incompletas.',
    'Insumo: 30% del costo|Atraso: 3 semanas|Proveedores calificados: 1',
    ['Equilibrada: calificaste un segundo proveedor y cubriste el hueco con stock: dependes menos de uno solo.',
      'Atajo: el insumo más barato salva el trimestre; en alimentos, cambiar sin avisar abre un reclamo.',
      'Cesión: el avión salvó la fecha a cualquier tarifa y el flete se comió el margen de esos pedidos.',
      'Pasividad: confiaste en el proveedor único y la planta paró 3 semanas: los pedidos no salieron.']],
  ['m07e', 'Un temporal de nieve cierra el paso a la cordillera por 7 días. Tres hospitales regionales tienen desinfectantes para 10 días y no pueden quedarse sin ellos.',
    'Cliente: hospitales regionales|Paso cerrado: 7 días|Stock del cliente: 10 días',
    ['Equilibrada: adelantaste stock a la bodega del hospital y consolidaste despachos: cero quiebres.',
      'Atajo: la ventana de calma te dejó llegar antes del cierre; si falla, el hospital queda sin producto.',
      'Cesión: el envío aéreo cumplió todo, con un flete que ningún precio de esos pedidos recupera.',
      'Pasividad: detuviste los despachos 7 días: ahorraste flete, pero esas ventas no salieron.']],
  ['m07s', 'Corporativo propone reorganizar el equipo y bajar 10% la dotación. Tus 40 personas atienden hospitales con visitas de servicio y cada cargo tiene clientes a su cargo.',
    'Dotación: 40 personas|Meta: 10% menos (4 cargos)|Plazo: este trimestre',
    ['Equilibrada: rediseñaste roles y automatizaste antes de bajar 4 cargos: menos SG&A sin soltar el servicio.',
      'Atajo: el 10% parejo cumple la meta del trimestre, pero también salió gente que atendía clientes.',
      'Cesión: mantuviste al equipo con la promesa de ganar productividad; el SG&A sigue igual y se nota.',
      'Pasividad: aplazaste la reorganización al segundo semestre y el SG&A siguió corriendo mientras tanto.']],

  ['m08c', 'El nuevo jefe de compras de una red de hospitales (16% de tus ventas) quiere licitar todo el suministro. Llegó con la meta de bajar costos y no conoce tu historial.',
    'Cliente: red de hospitales|Peso: 16% de tus ventas|Proceso: licitación abierta',
    ['Equilibrada: llevaste resultados medidos y un rebate escalonado a 2 años: el comprador ve valor.',
      'Atajo: entraste con un precio base 6% menor y cobraste los servicios aparte; la factura final sorprende.',
      'Cesión: ofreciste el precio más bajo en contratos de 3 años: ganas el contrato con margen mínimo.',
      'Pasividad: esperaste la invitación formal y cotizaste en 10 días; el comprador ya manejaba otros precios.']],
  ['m08p', 'En plena temporada alta, los hoteles piden 12% más de lo que tu planta puede producir durante 3 meses. Producir más cuesta; rechazar pedidos también.',
    'Cliente: hoteles en temporada alta|Demanda sobre capacidad: +12%|Duración: 3 meses',
    ['Equilibrada: sumaste un turno planificado y priorizaste por margen: la planta rinde sin romperse.',
      'Atajo: la planta sin pausa cubre la demanda, pero postergar mantenciones puede salir muy caro después.',
      'Cesión: tomaste todos los pedidos y negociaste plazos después; atrasos y horas extra suben el costo.',
      'Pasividad: seguiste con el plan vigente y la demanda no se ordenó sola: se perdieron pedidos.']],
  ['m08e', 'El dólar sube 10% y tus insumos importados se encarecen igual. Las plantas de alimentos te compran con listas de precio que se revisan cada 3 meses.',
    'Cliente: plantas de alimentos|Dólar: +10%|Revisión de precios: cada 3 meses',
    ['Equilibrada: traspasaste la mitad del alza por etapas, con aviso de 30 días; los clientes lo aceptan.',
      'Atajo: reajustaste 10% de una vez: el mes mejora, pero varios clientes empiezan a cotizar afuera.',
      'Cesión: dejaste los precios igual para cuidar a los clientes y el margen pagó el 10% completo.',
      'Pasividad: miraste el dólar cada 30 días con la lista vieja: el costo subió y el margen se erosionó.']],
  ['m08s', 'Un distribuidor se ofrece a atender a tus clientes pequeños (hoteles de barrio y hostales) por una comisión de 8%. Bajarías costos de visitas, pero cedes la relación con ellos.',
    'Clientes pequeños: 120|Comisión del distribuidor: 8%|Piloto posible: 10 clientes',
    ['Equilibrada: probaste 6 meses con 10 clientes y comparaste servicio y margen antes de decidir.',
      'Atajo: cediste la cartera de 120 clientes para bajar costos: el SG&A baja, pero pierdes la relación.',
      'Cesión: aceptaste el 8% y las condiciones del distribuidor: el margen de esos clientes baja.',
      'Pasividad: rechazaste el 8% por política, sin ver números: sigues pagando visitas que no dan margen.']],

  ['m09c', 'Una cadena de hoteles (13% de tus ventas) promete 20% más volumen si le bajas 5%. Es crecimiento posible, pero la promesa no está firmada y su margen ya es bajo.',
    'Cliente: cadena de hoteles|Volumen prometido: +20%|Rebaja pedida: 5%',
    ['Equilibrada: rebajaste 5% solo a los embarques nuevos y revisas a los 3 meses: más ventas, con margen cuidado.',
      'Atajo: subiste 3% la lista de los clientes chicos, que no negocian: hoy sube el OI, mañana lo notan.',
      'Cesión: diste 5% por todo el año y confiaste en la promesa: más ventas, con un margen mucho menor.',
      'Pasividad: dejaste la propuesta 4 semanas en el comité y el hotel repartió el volumen entre otros.']],
  ['m09p', 'La tarifa eléctrica sube 12% en horario punta, justo cuando tu planta gasta 40% de su energía. Mover la producción tiene costo, y no hacer nada también.',
    'Tarifa en horario punta: +12%|Gasto de energía en punta: 40%|Revisión de tarifa: en 3 meses',
    ['Equilibrada: pasaste 2 líneas a la noche: la energía cuesta menos y mantienes los pedidos.',
      'Atajo: acortaste el turno de tarde 25%: ahorras energía, pero los pedidos chicos se atrasan.',
      'Cesión: cubriste el alza completa por no tocar la rutina: el costo de energía sube todos los meses.',
      'Pasividad: seguiste con 3 turnos hasta la revisión y pagaste el alza completa 3 meses sin mover nada.']],
  ['m09e', 'Vienen elecciones y 4 cadenas hoteleras frenan pedidos por la incertidumbre. Quieren esperar el resultado antes de comprometer inventario.',
    'Cliente: cadenas hoteleras|Clientes que frenan: 4|Elección: en 6 semanas',
    ['Equilibrada: contratos puente de 6 meses a precio fijo, con opción a 12: vuelven los pedidos.',
      'Atajo: rebajaste 8% a quien firmara este mes; ya pensaban comprar: regalaste margen por nada.',
      'Cesión: adoptaste el calendario de cada cliente y reprogramaste la planta entera: el desorden lo pagas tú.',
      'Pasividad: pausaste las ofertas y los 4 clientes pidieron recién tras la elección: ventas perdidas.']],
  ['m09s', 'Tu proveedor clave (32% del costo) ofrece 6% menos si firmas por 3 años. Para una planta de alimentos el insumo es crítico, pero atarte tanto tiempo también tiene riesgos.',
    'Insumo: 32% del costo|Descuento ofrecido: 6%|Contrato: 3 años',
    ['Equilibrada: firmaste 36 meses con salida al mes 18 y precio indexado: el costo baja y conservas opciones.',
      'Atajo: aceptaste 5 años de exclusividad por 9% menos: el costo baja hoy y te quedas sin alternativa.',
      'Cesión: firmaste el texto del proveedor tal cual, con alzas anuales: el ahorro se come con los reajustes.',
      'Pasividad: dejaste caducar la oferta y seguiste a precio de lista: el 6% de ahorro se perdió.']],

  ['m10c', 'Una planta de alimentos pide 3 dosificadores en comodato para sus líneas nuevas. Los equipos son tuyos y su mantención corre por tu cuenta, aunque compre poco.',
    'Equipos pedidos: 3 dosificadores|Compra mínima: sin acordar|Mantención: por tu cuenta',
    ['Equilibrada: entregaste los equipos con compra mínima anual y mantención pagada: instalas con retorno claro.',
      'Atajo: recargaste 3% al precio de los insumos para costear los equipos; el cliente verá el alza en su factura.',
      'Cesión: entregaste los 3 equipos y asumiste la mantención aunque compre poco: Direct Chg sin ventas.',
      'Pasividad: le dijiste que comprara sus propios equipos; el cliente se fue con quien sí los presta.']],
  ['m10p', 'El sindicato de tu planta anuncia 2 días de paro parcial si no hay bono de fin de año. Los pedidos de las fiestas están en curso y una línea detenida atrasa a los clientes.',
    'Paro anunciado: 2 días|Pedidos de fin de año: en curso|Bono exigido: fijo y anual',
    ['Equilibrada: ofreciste un bono por metas de planta y seguridad en 2 cuotas: sin paro y con costo variable.',
      'Atajo: cubriste los 2 días con supervisores y evitaste hablar con el sindicato; el conflicto sigue abierto.',
      'Cesión: pagaste el bono fijo que exigían: sin paro, pero el costo de mano de obra sube cada año.',
      'Pasividad: ignoraste el anuncio y el paro ocurrió: esos 2 días no salieron pedidos.']],
  ['m10e', 'Una sequía recorta 20% el agua que usa tu planta y no alcanza para todos los pedidos. Las plantas de alimentos esperan sus entregas y no todos los pedidos rinden igual.',
    'Agua disponible: 20% menos|Pedidos sin cubrir: 1 de 4|Cliente: plantas de alimentos',
    ['Equilibrada: asignaste el agua a los pedidos que más rinden y avisaste al resto: menos volumen, más margen.',
      'Atajo: el recargo de 10% sube el ingreso hoy, pero lo cobraste también a pedidos ya cotizados.',
      'Cesión: los camiones aljibe abastecieron a todos: ninguna venta se perdió y el costo del agua se disparó.',
      'Pasividad: entregaste por orden de llegada: se cubrieron pedidos de poco margen y se perdieron los mejores.']],
  ['m10s', 'La feria anual del sector hospitalario cuesta US$ 0,5 M en stand y viajes. Seis de tus clientes más importantes ya avisaron que no irán este año.',
    'Costo de la feria: US$ 0,5 M|Clientes que no irán: 6|Citas ya agendadas: 15',
    ['Equilibrada: fuiste con stand pequeño y 15 citas agendadas: menos SG&A y reuniones que valen la pena.',
      'Atajo: diste 5% a visitantes que firmaron en la feria aunque ya compraban: regalaste margen seguro.',
      'Cesión: reservaste el stand grande que pedía Marketing: el SG&A sube sin más clientes que atender.',
      'Pasividad: repetiste el stand del año pasado con el mismo presupuesto, aunque 6 clientes no irán.']],

  ['m11c', 'Una planta industrial objeta 3% de cargos en 4 facturas, pero sigue comprando. Cada cargo discutido es plata en suspenso y la discusión puede desgastar la relación.',
    'Cargos en disputa: 3%|Facturas objetadas: 4|Cliente: planta industrial',
    ['Equilibrada: revisaste las 4 facturas con el cliente y corregiste solo lo que estaba mal: se paga lo justo.',
      'Atajo: prorrateaste esos cargos en el precio de lista de las próximas facturas; el cliente lo verá después.',
      'Cesión: emitiste notas de crédito por el 3% de las 4 facturas: cierras el tema y el margen cede por completo.',
      'Pasividad: dejaste la disputa abierta; el cliente retuvo pagos y terminó exigiendo un crédito mayor.']],
  ['m11p', 'Llega fin de año con 30% más de pedidos de hoteles por las fiestas, justo cuando tu gente pide vacaciones. Faltan manos y los turnos no alcanzan.',
    'Pedidos de fin de año: +30%|Cliente: hoteles en fiestas|Permisos pedidos: 12',
    ['Equilibrada: rotaste turnos con permisos justos y un bono de 3%: se despacha sin quemar al equipo.',
      'Atajo: congelaste los permisos de diciembre y mantuviste 3 turnos al máximo: el equipo se agota.',
      'Cesión: diste todos los permisos y toleraste 2 semanas de atraso: algunos hoteles no esperaron.',
      'Pasividad: armaste turnos día a día y los picos de demanda te encontraron sin gente.']],
  ['m11e', 'Un bloqueo de la ruta principal detiene tus despachos por 3 semanas. Hay 20 pedidos pendientes para plantas industriales que dependen de tus entregas.',
    'Pedidos pendientes: 20|Bloqueo: 3 semanas|Cliente: plantas industriales',
    ['Equilibrada: coordinaste un desvío con el cliente y conversaste con los vecinos: poco costo extra.',
      'Atajo: cobraste al cliente el costo del bloqueo con una carta formal: hoy sube el ingreso, mañana lo recuerda.',
      'Cesión: pagaste peaje y escolta para despachar los 20 pedidos: cumples, pero el flete se come el margen.',
      'Pasividad: pausaste los despachos y esperaste a que otros resolvieran el bloqueo: 3 semanas sin ventas.']],
  ['m11s', 'Tus vendedores cobran 3% sobre la venta, sin importar el margen. Algunos cierran grandes ventas a precio muy bajo y la comisión se come lo poco que queda.',
    'Comisión actual: 3% de la venta|Vendedores: 12|Margen en ventas grandes: bajo',
    ['Equilibrada: pasaste la comisión a margen con piso de 1% por 6 meses: el margen sube.',
      'Atajo: subiste 15% la meta de ventas de todos: el volumen se mueve hoy, pero presionas a vender sin margen.',
      'Cesión: subiste la comisión a 4% para no perder a los mejores: el SG&A sube sin más margen.',
      'Pasividad: dejaste el esquema actual hasta la negociación anual: siguen premiando volumen sin margen.']],

  ['m12c', 'Una planta de alimentos grande y fiel ofrece renovar 3 años, pero a precio fijo y sin reajuste por inflación. Tus costos de insumos pueden subir; el precio no se mueve.',
    'Contrato: 36 meses|Precio: fijo, sin reajuste|Peso del cliente: 12% de tus ventas',
    ['Equilibrada: aceptaste 36 meses con un tope atado al costo de insumos: ventas y margen cuidados.',
      'Atajo: firmaste con un precio inicial 3% más alto que el mercado; el cliente puede irse apenas pueda.',
      'Cesión: firmaste los 3 años como los redactó el cliente: ventas aseguradas, costos libres de subir.',
      'Pasividad: dejaste caducar la oferta mientras legal revisaba; el cliente firmó con otro por 3 años.']],
  ['m12p', 'Cierra el año y 5% del inventario parece obsoleto antes de valorarlo. En una planta de alimentos hay fechas de vencimiento y no se puede esperar para saber lo que vale.',
    'Inventario dudoso: 5%|Cierre del año: en 1 mes|Cliente: plantas de alimentos',
    ['Equilibrada: contaste, vendiste lo recuperable y diste de baja el resto: castigo real y a tiempo.',
      'Línea roja: dejaste lo obsoleto a valor de libro. Es información engañosa: ajuste, multa y auditoría.',
      'Cesión: castigaste el 12% de una vez, como pedía Auditoría: el golpe es mayor que lo necesario.',
      'Pasividad: usaste las cifras del sistema y cerraste a tiempo; el inventario obsoleto quedó sin valorar.']],
  ['m12e', 'Un paro de camioneros amenaza tus despachos de diciembre, 18% de las ventas del año. Los hospitales no pueden quedarse sin insumos justo en las fiestas.',
    'Despachos de diciembre: 18% del año|Paro anunciado: 2 semanas|Cliente: hospitales',
    ['Equilibrada: adelantaste 40% de los despachos y reservaste 3 transportistas: el paro no te tocó.',
      'Atajo: cargaste 5% a los despachos por el paro y lo explicaste después de facturar; los clientes lo reclaman.',
      'Cesión: autorizaste la tarifa que pidiera cada transportista: se despachó todo, con un flete carísimo.',
      'Pasividad: seguiste el plan con los camiones disponibles y los pedidos se acumularon sin llegar a tiempo.']],
  ['m12s', 'Falta un mes para cerrar el año y tu OI está 1 punto bajo el plan. Corporativo mira el cierre y hay formas de mejorar el número que no mejoran el negocio.',
    'Meses que faltan: 1|OI bajo el plan: 1 punto|Meta de corporativo: cierre en plan',
    ['Equilibrada: congelaste 2 cargos vacantes y pausaste capacitaciones ajenas a ventas: baja el SG&A.',
      'Línea roja: adelantaste facturación de enero a diciembre. Es contabilidad engañosa: ajuste, multa y auditoría.',
      'Cesión: otorgaste el bono completo al equipo aunque el resultado quedó lejos: más SG&A, sin mérito.',
      'Pasividad: cerraste como venía, sin tocar nada: el año termina 1 punto bajo el plan y sin explicación.']],
];

const entries = ROWS.flatMap(([id, brief, facts, stories]) => [
  [`year.${id}.brief`, brief],
  [`year.${id}.facts`, facts],
  ...stories.map((story, i) => [`year.${id}.${ANSWERS[i]}.why`, story]),
]);

module.exports = Object.freeze(Object.fromEntries(entries));
