'use strict';

// Year mode, Spanish. One row per problem:
//   [id, title, scene, [smart name, desc], [temp name, desc], [plac name, desc], [ign name, desc]]
// The four answers are always written in that order; the game shuffles what the player sees.

const ANSWERS = ['smart', 'temp', 'plac', 'ign'];

const ROWS = [
  ['m01c', 'Renovación anual', 'La minera, 18% de tus ventas, pide 3% de rebate para renovar el contrato.',
    ['Contrato a 2 años', 'Ofreces 1% de rebate y subes a 2% sobre el plan para que firmen 2 años.'],
    ['Aceptar y compensar', 'Aceptas el 3% y compensas con un alza de 2% en sus otros productos.'],
    ['Ceder el 3%', 'Otorgas el 3% sobre el contrato y cierras la renovación esta semana.'],
    ['Pedir más plazo', 'Pides 30 días y estudias el planteo, aunque el contrato vence en 20.']],
  ['m01p', 'Inventario bajo', 'Quedan 3 semanas de insumos clave y en enero entran pedidos grandes.',
    ['Compra escalonada', 'Compras en 2 lotes, el segundo a 20 días, y avisas qué pedidos son firmes.'],
    ['Producir al límite', 'Pides 110% de capacidad a la planta este mes en vez de comprar caro.'],
    ['Compra masiva', 'Compras 3 meses de insumos a precio spot y atiendes cualquier demanda.'],
    ['Posponer compra', 'Pospones la compra a la revisión de inventario de fin de ciclo.']],
  ['m01e', 'Presupuesto y dólar', 'El dólar está 7% sobre el presupuesto y 40% de tus insumos son importados.',
    ['Reajuste por dólar', 'Pactas por escrito un reajuste según el dólar y compras a plazo la mitad.'],
    ['Alza de precios', 'Aplicas un alza de 3% desde mañana, también a los contratos vigentes.'],
    ['Absorber el golpe', 'Dejas precios y compras igual para que el margen pague el alza de 7%.'],
    ['Analizar al cierre', 'Analizas el efecto del dólar con los números del cierre, a 3 meses.']],
  ['m01s', 'Medir o empujar', 'Corporativo pide 6% más de volumen; el ahorro de tus clientes sigue sin medir.',
    ['Medir el ahorro', 'Documentas el ahorro del agua de 3 clientes y negocias después con datos.'],
    ['Empujar volumen', 'Ofreces 4% de descuento en pedidos extra para llegar al 6% de corporativo.'],
    ['Plan de corporativo', 'Aplicas con rigor el plan de volumen de corporativo; la medición queda en pausa.'],
    ['Posponer ambas', 'Postergas ambas ideas por 3 meses, hasta que el año tome ritmo.']],

  ['m02c', 'Cambio de especificación', 'Un cliente, 12% de tus ventas, pide otra especificación con 2 semanas de aviso.',
    ['Prueba corta', 'Haces una prueba de 3 días y pides al cliente acordar una fecha realista.'],
    ['Cambiar la fórmula', 'Cambias la fórmula con el stock de bodega y despachas en 2 semanas.'],
    ['Aceptar lo pedido', 'Aceptas la fecha de 2 semanas y absorbes el costo extra de planta.'],
    ['Responder el lunes', 'Lo llevas a la reunión comercial del lunes y respondes en una semana.']],
  ['m02p', 'Mantención vs pedidos', 'Toca la mantención mayor, con 4 días de línea parada, y hay pedidos urgentes.',
    ['Mantención parcial', 'Paras media línea en turnos, con 2 semanas de plazo, y repartes lo urgente.'],
    ['Aplazar mantención', 'Mueves la mantención por 8 semanas y atiendes los pedidos del mes.'],
    ['Parar la línea', 'Detienes la línea 4 días y pides al cliente que espere sus despachos.'],
    ['Calendario original', 'Respetas el calendario original; solo 2 de 5 urgentes entran.']],
  ['m02e', 'Lluvias altiplánicas', 'Las lluvias cortan el camino a la faena: hay 14 despachos pendientes.',
    ['Ruta alterna', 'Tomas la ruta sur, 120 km más larga, y priorizas lo crítico.'],
    ['Despachar igual', 'Mandas los 14 camiones igual y llegas a las fechas pese al camino dañado.'],
    ['Camiones 4x4', 'Alquilas 14 camiones 4x4 para llegar a tiempo, a triple tarifa de flete.'],
    ['Camino cortado', 'Detienes los despachos con el camino cortado, una semana más o menos.']],
  ['m02s', 'Pronóstico agresivo', 'Corporativo pide subir 8% el pronóstico del año para la reunión del lunes.',
    ['Pronóstico en rango', 'Entregas un caso base y otro optimista de +8%, ambos explicados.'],
    ['Inflar el número', 'Inflas 8% el pronóstico para cumplir y lo ajustas en el próximo reporte.'],
    ['Aceptar el 8%', 'Aceptas con gusto la meta de +8% y la repartes entre los equipos.'],
    ['Enviarlo después', 'Envías el pronóstico por correo en 7 días, con las cifras del mes pasado.']],

  ['m03c', 'Lote fuera de norma', 'Un cliente reclama 40 toneladas que salieron fuera de especificación.',
    ['Reponer el lote', 'Repones hoy las 40 toneladas y compartes el análisis para evitar otro reclamo.'],
    ['Apuntar al flete', 'Atribuyes el daño al transporte y respondes con media reposición.'],
    ['Descuento de 10%', 'Reconoces 10% sobre la siguiente compra del cliente y cierras el reclamo hoy.'],
    ['Reclamo formal', 'Contestas el reclamo formal cuando llega, en 15 días, y revisas el lote.']],
  ['m03p', 'Falla y materia prima', 'Falla una bomba de la línea 2 y quedan 5 días de una materia prima clave.',
    ['Priorizar pedidos', 'Priorizas los críticos con lo que queda y compras la bomba a un local.'],
    ['Parche provisorio', 'Haces una reparación provisoria por 2 días y sigues a plena carga.'],
    ['Comprar urgente', 'Compras la bomba y la materia prima en 24 horas y pagas lo que pidan.'],
    ['Detener la línea', 'Paras la línea 2 hoy para que el proveedor entregue los repuestos.']],
  ['m03e', 'Reforma tributaria', 'Se anuncia una reforma tributaria minera y 3 clientes grandes frenan compras.',
    ['Ver escenarios', 'Conversas por cliente sus escenarios y ofreces descuento solo a pedidos firmes.'],
    ['Adelantar ventas', 'Das 5% de descuento a quien compre antes de que se apruebe la reforma.'],
    ['Congelar precios', 'Congelas los precios por 12 meses para tranquilizar a los 3 clientes.'],
    ['Votación primero', 'Esperas la votación de la reforma, en 2 meses, antes de mover el plan.']],
  ['m03s', 'Producto de agua', 'Una oportunidad: un programa de ahorro de agua que 5 mineras preguntaron.',
    ['Piloto acotado', 'Lo pruebas 3 meses en un cliente amigo y mides el efecto antes de escalar.'],
    ['Lanzar a todos', 'Lo ofreces ya a las 5 mineras, con resultados que prometes lograr.'],
    ['Armar propuesta', 'Preparas una propuesta con presupuesto y partes cuando la aprueben.'],
    ['Otra oportunidad', 'Priorizas los 4 proyectos del año y el programa queda para otra oportunidad.']],

  ['m04c', 'Recorte de presupuesto', 'Un cliente recorta 10% su presupuesto de insumos y pide bajar los precios.',
    ['Bajar su consumo', 'Ajustas la dosis para que gaste 10% menos; tú mantienes los precios.'],
    ['Cambiar el mix', 'Rebajas 5% el producto principal y subes 5% los servicios del contrato.'],
    ['Rebajar el contrato', 'Rebajas 5% por 12 meses el precio del contrato, y el cliente se queda.'],
    ['Sostener términos', 'Mantienes los términos vigentes y el cliente decide en 30 días si se queda.']],
  ['m04p', 'Rotación de operadores', 'Se van 2 de 9 operadores clave y los turnos quedan incompletos.',
    ['Plan de relevo', 'Capacitas a dos jóvenes con 6 semanas de práctica y reorganizas los turnos.'],
    ['Horas extra', 'Pides turnos dobles por un trimestre al equipo que queda.'],
    ['Subir sueldos', 'Subes 8% el sueldo de cada operador del turno y nadie más se va.'],
    ['Cupos vacantes', 'Reasignas tareas durante el trimestre y los 2 cupos siguen vacantes.']],
  ['m04e', 'Royalty minero', 'Sube el royalty minero y los clientes revisan todos sus contratos de insumos.',
    ['Contratos por valor', 'Propones contratos atados al ahorro que generas, no solo al volumen.'],
    ['Precio a cautivos', 'Subes 6% el precio a los clientes que no tienen otro proveedor calificado.'],
    ['Ofrecer rebaja', 'Ofreces 3% de rebaja a los clientes para fidelizarlos antes de que pidan.'],
    ['Contestar pedidos', 'Contestas las peticiones de renegociar a medida que llegan de las mineras.']],
  ['m04s', 'Recorte de SG&A', 'Corporativo pide bajar 5% el SG&A desde el próximo mes.',
    ['Recorte selectivo', 'Recortas viajes y consultorías y proteges visitas a clientes y medición.'],
    ['Recorte parejo', 'Recortas cada partida 5% parejo para llegar a la meta de corporativo.'],
    ['Pedir excepción', 'Pides una excepción con el argumento del plan comercial de este semestre.'],
    ['Agendar revisión', 'Llevas la orden a la reunión de presupuesto de fin de trimestre.']],

  ['m05c', 'Visitas sin costo', 'Un cliente (9% de tus ventas) pide visitas semanales sin pagar más.',
    ['Visitas por demanda', 'Ofreces monitoreo remoto para que se visite solo si el dato lo pide.'],
    ['Técnico junior', 'Aceptas las visitas semanales con un técnico junior y reduces el gasto 40%.'],
    ['Visitas semanales', 'Concedes 4 visitas por mes por cuenta tuya y absorbes el costo del servicio.'],
    ['Pasar a Operaciones', 'Pasas la solicitud a Operaciones y ofreces respuesta con fecha en 20 días.']],
  ['m05p', 'Incidente de seguridad', 'Hay un incidente sin heridos en la planta y en 10 días llega una auditoría.',
    ['Investigar causa', 'Detienes la zona 2 días con el equipo y corriges el procedimiento.'],
    ['Cerrar el informe', 'Cierras el informe como incidente menor, por los 7 días que costaría parar.'],
    ['Parar la planta', 'Detienes la planta 7 días y rehaces los procedimientos de cero.'],
    ['Producir igual', 'Continúas produciendo para cumplir 120 pedidos, pues nadie resultó herido.']],
  ['m05e', 'Cae el cobre', 'El cobre baja 15% y las mineras congelan las compras no esenciales.',
    ['Rebate por volumen', 'Pactas un rebate de 1% por los volúmenes sobre su compra mínima.'],
    ['Cobro a activos', 'Cobras 4% más a quienes siguen comprando y recortas su rebate.'],
    ['Rebate general', 'Otorgas 3% de rebate a los clientes mineros para que no frenen más compras.'],
    ['Mirar el ciclo', 'Conservas precios y el rebate actual a la espera de un rebote del cobre.']],
  ['m05s', 'Monitoreo remoto', 'Puedes invertir en monitoreo remoto para 6 faenas con visitas mensuales.',
    ['Invertir por etapas', 'Instalas en 2 faenas mayores y calculas el ahorro en visitas por 6 meses.'],
    ['Cancelar el plan', 'Cancelas la inversión para mejorar el margen del año y recortas visitas.'],
    ['Instalar en las 6', 'Instalas el sistema en las 6 faenas con un presupuesto de 0,8.'],
    ['Decidir después', 'Evalúas el ahorro otros 3 meses mientras las visitas cuestan igual.']],

  ['m06c', 'Competidor 8% menor', 'Un competidor ofrece 8% menos y amenaza un contrato de 14% de ventas.',
    ['Mostrar el ahorro', 'Presentas el ahorro medido y sostienes el precio con un rebate a 2 años.'],
    ['Amarrar al cliente', 'Firmas un contrato de 3 años con multas de salida de 20%.'],
    ['Igualar el precio', 'Bajas 8% el precio por la duración del contrato y conservas el resto.'],
    ['Confiar en el lazo', 'Cuidas la relación con los clientes y das por seguro su lealtad por 3 años.']],
  ['m06p', 'Deriva de calidad', 'Esta semana 4 lotes de 10 salen al límite de la especificación.',
    ['Ajustar el proceso', 'Ajustas el proceso con calidad y refuerzas los controles del lote.'],
    ['Mezclar lotes', 'Mezclas lotes dudosos por partes con lotes buenos para que el promedio pase.'],
    ['Controles extra', 'Agregas pruebas a cada lote y la liberación se demora 2 días.'],
    ['Esperar un reclamo', 'Despachas 4 lotes y archivas las pruebas hasta que algún cliente reclame.']],
  ['m06e', 'Norma de agua', 'Una norma ambiental limita 20% el uso de agua en las faenas.',
    ['Programa de reuso', 'Propones un programa de reuso de agua con pago por m3 ahorrado.'],
    ['Paquete cerrado', 'Vendes un paquete llave en mano aún no probado y firmas 3 contratos.'],
    ['Diagnóstico gratis', 'Haces diagnósticos de ahorro gratis a los clientes para ganarte su confianza.'],
    ['Que pidan ayuda', 'Ayudas solo a quien lo pide, con una respuesta en 10 días.']],
  ['m06s', 'Nuevo país', 'Un cliente grande de otro país pide cotización en 30 días.',
    ['Entrar con socio', 'Eliges un distribuidor local y limitas la inversión del primer año.'],
    ['Atender de lejos', 'Atiendes a distancia con precios 15% altos para cubrir el riesgo inicial.'],
    ['Asumir requisitos', 'Asumes los requisitos del cliente con sus contratos al partir.'],
    ['Cotización tardía', 'Envías la cotización por correo en 45 días, con los requisitos revisados.']],

  ['m07c', 'Auditoría de costos', 'Un cliente (11% de tus ventas) pide auditar tus costos y tu margen.',
    ['Abrir con reglas', 'Aceptas auditar y muestras flete y Direct Chg para acordar cómo comparar.'],
    ['Mostrar a medias', 'Muestras los costos que te favorecen con el resto en resumen.'],
    ['Libro abierto', 'Abres los costos por línea y aceptas bajar tu margen 2 puntos.'],
    ['Auditoría después', 'Postergas la auditoría por falta de tiempo, hasta 6 meses.']],
  ['m07p', 'Proveedor atrasado', 'Tu único proveedor se atrasa 3 semanas con un insumo que pesa 30% del costo.',
    ['Segundo proveedor', 'Calificas un segundo proveedor con 2 pruebas y cubres el hueco con stock.'],
    ['Insumo alternativo', 'Cambias a un insumo más barato por 3 meses y lo informas después.'],
    ['Flete urgente', 'Traes el insumo en avión a cualquier tarifa y evitas la espera.'],
    ['Plan único', 'Conservas al proveedor único y confías en recuperar el atraso solo.']],
  ['m07e', 'Temporal de nieve', 'Un temporal de nieve cierra el paso a las faenas por 7 días.',
    ['Stock en la faena', 'Adelantas stock a la bodega del cliente por 10 días y reprogramas despachos.'],
    ['Ventana de calma', 'Envías camiones en la ventana de calma y llegas antes del cierre.'],
    ['Envío aéreo', 'Llevas lo crítico con envíos aéreos para que nada se atrase.'],
    ['Paso bloqueado', 'Detienes despachos con el paso bloqueado, 7 días.']],
  ['m07s', 'Reorganización', 'Corporativo propone reorganizar el equipo y bajar 10% la dotación.',
    ['Rediseñar roles', 'Reasignas funciones y automatizas los procesos antes de bajar 4 cargos.'],
    ['Bajar 10% parejo', 'Reduces la dotación 10% en cada área para cumplir la meta del trimestre.'],
    ['Mantener equipo', 'Conservas la dotación con la promesa de mejorar la productividad en 6 meses.'],
    ['Aplazar el tema', 'Aplazas la reorganización y la retomas en el segundo semestre.']],

  ['m08c', 'Nuevo comprador', 'El nuevo jefe de compras de un cliente (16% de ventas) quiere licitar.',
    ['Reunión de valor', 'Presentas resultados medidos para proponer un rebate escalonado a 2 años.'],
    ['Precio base bajo', 'Entras con un precio base 6% menor y cobras los servicios aparte.'],
    ['Licitar al mínimo', 'Ofreces el precio más bajo posible por contratos de 3 años.'],
    ['Invitación formal', 'Recibes la invitación formal y preparas tu cotización en 10 días.']],
  ['m08p', 'Capacidad al límite', 'La demanda supera 12% la capacidad de la planta por 3 meses.',
    ['Turno adicional', 'Agregas un turno planificado y mantienes la prioridad por margen en producción.'],
    ['Planta sin pausa', 'Operas la línea 24 horas por 3 meses y postergas las mantenciones.'],
    ['Tomar los pedidos', 'Tomas los pedidos de los 3 meses y negocias los plazos después.'],
    ['Mantener la rutina', 'Operas con el plan vigente y la demanda se ordena sola.']],
  ['m08e', 'Sube el dólar', 'El dólar sube 10% y tu costo de insumos importados también.',
    ['Traspaso gradual', 'Subes por etapas la mitad del alza en los precios con aviso de 30 días.'],
    ['Alza inmediata', 'Reajustas los precios 10% de una vez y compensas el alza del mes.'],
    ['Absorber el alza', 'Dejas los precios igual para cuidar a los clientes y el margen paga 10%.'],
    ['Mirar el dólar', 'Usas la lista de precios actual y evalúas el dólar cada 30 días.']],
  ['m08s', 'Alianza con distribuidor', 'Un distribuidor atendería a tus clientes pequeños por 8% de comisión.',
    ['Piloto de 6 meses', 'Pruebas con 10 clientes pequeños y comparas el servicio y el margen.'],
    ['Ceder la cartera', 'Cedes la cartera de 120 clientes pequeños para bajar tus costos.'],
    ['Pagar la comisión', 'Pagas la comisión de 8% con las condiciones que pida el distribuidor.'],
    ['Rechazar el trato', 'Rechazas el 8% de comisión por política interna, antes de ver los números.']],

  ['m09c', 'Volumen por precio', 'Un cliente (13% de tus ventas) promete 20% más volumen si le bajas 5%.',
    ['Descuento por tramo', 'Rebajas 5% en los embarques nuevos y revisas el resultado a los 3 meses.'],
    ['Subir al resto', 'Aumentas 3% la lista a los clientes chicos, que no negocian, y costeas esto.'],
    ['Dar el 5% a todo', 'Concedes 5% de descuento por todo el año y confías en su promesa de crecer.'],
    ['Pasar al comité', 'Dejas la propuesta en el comité de precios, que sesiona en 4 semanas.']],
  ['m09p', 'Energía en horario punta', 'La tarifa eléctrica sube 12% en horario punta, donde la planta gasta 40%.',
    ['Mover la carga', 'Pasas 2 líneas de la planta al turno de noche y mantienes los pedidos.'],
    ['Turno corto', 'Acortas el turno de tarde en un 25%, con lo que los pedidos chicos se atrasan.'],
    ['Cubrir el alza', 'Cubres el alza completa y mantienes los 3 turnos por no tocar la rutina.'],
    ['Plan sin cambios', 'Sigues con los 3 turnos actuales y la tarifa se revisa dentro de 3 meses.']],
  ['m09e', 'Elecciones', 'Vienen elecciones y 4 clientes frenan pedidos por la incertidumbre.',
    ['Contrato puente', 'Firmas contratos de 6 meses a precio fijo, con opción de ampliar a 12.'],
    ['Premio por firmar', 'Rebajas 8% a los 4 clientes que firmen este mes, aunque ya pensaban comprar.'],
    ['Ir a su ritmo', 'Adoptas el calendario que fije cada cliente y reprogramas la planta entera.'],
    ['Pausa de campaña', 'Pausas las ofertas durante la campaña y las retomas después de la elección.']],
  ['m09s', 'Contrato del proveedor', 'Tu proveedor clave (32% del costo) ofrece 6% menos por 3 años de contrato.',
    ['Contrato con salida', 'Firmas 36 meses con una cláusula de salida al mes 18 y precio indexado.'],
    ['Exclusividad total', 'Aceptas 5 años de exclusividad y consigues 9% menos de inmediato.'],
    ['Firmar sin cambios', 'Apruebas el texto del proveedor tal como llegó, con alzas anuales.'],
    ['Dejarlo caducar', 'Sigues comprando a precio de lista y la oferta caduca en 30 días.']],

  ['m10c', 'Equipos en comodato', 'Un cliente pide 3 dosificadores en comodato para sus faenas nuevas.',
    ['Comodato con mínimo', 'Entregas los equipos si compra un mínimo anual y paga el mantenimiento.'],
    ['Subir el precio', 'Recargas 3% al precio de los insumos y costeas los equipos con eso.'],
    ['Entregar sin trabas', 'Entregas los 3 equipos y asumes la mantención, aunque compre poco.'],
    ['Que los compre', 'Explicas que el comodato no existe y que compre sus propios equipos.']],
  ['m10p', 'Paro parcial', 'El sindicato anuncia 2 días de paro parcial si no hay bono de fin de año.',
    ['Bono por metas', 'Pagas un bono variable ligado a metas de planta y seguridad, en 2 cuotas.'],
    ['Cubrir con extras', 'Cubres los 2 días con supervisores y evitas hablar con el sindicato.'],
    ['Pagar el bono', 'Pagas el bono fijo que exigen y evitas el paro, aunque salga caro cada año.'],
    ['Dejar que avance', 'Ignoras el anuncio y ves si el paro sigue adelante o se diluye.']],
  ['m10e', 'Sequía en la planta', 'Una sequía recorta 20% el agua de tu planta y no cubre todos los pedidos.',
    ['Pedidos rentables', 'Asignas el volumen a los pedidos que más rinden y avisas al resto.'],
    ['Recargo por escasez', 'Impones un recargo de 10% por escasez, incluso a pedidos ya cotizados.'],
    ['Camiones aljibe', 'Contratas camiones aljibe para abastecer a todos, cueste lo que cueste.'],
    ['Orden de llegada', 'Operas con el agua disponible y entregas los pedidos según lleguen.']],
  ['m10s', 'Feria del sector', 'La feria anual cuesta 0,5 en stand y viajes, y 6 de tus clientes no irán.',
    ['Ir con citas', 'Vas con un stand pequeño y 15 citas ya agendadas con clientes.'],
    ['Descuento de feria', 'Das 5% a visitantes que firmen en feria, aunque ya compraban antes.'],
    ['Stand grande', 'Reservas el stand grande que pide Marketing para no quedar atrás.'],
    ['Repetir el stand', 'Repites el stand del año pasado, con el mismo equipo y presupuesto.']],

  ['m11c', 'Cargos en disputa', 'Un cliente objeta 3% de cargos en 4 facturas, pero sigue comprando.',
    ['Revisar cada cargo', 'Revisas las 4 facturas con el cliente y arreglas lo que esté mal.'],
    ['Cargos al precio', 'Prorrateas esos cargos dentro del precio de lista de las facturas siguientes.'],
    ['Nota de crédito', 'Emites notas de crédito por el 3% de las 4 facturas y cierras el tema.'],
    ['Dejar abierta', 'Mantienes abierta la disputa y revisas los cargos si el cliente insiste.']],
  ['m11p', 'Turnos de fin de año', 'Llega fin de año con 30% más de pedidos y gente que pide vacaciones.',
    ['Turnos rotativos', 'Rotas a la gente con permisos justos y un bono de 3% por cumplir.'],
    ['Congelar permisos', 'Congelas los permisos de diciembre y mantienes los 3 turnos al máximo.'],
    ['Dar los permisos', 'Das los permisos pedidos y toleras 2 semanas de atraso, aunque reclamen.'],
    ['Turnos al paso', 'Armas los turnos día a día y ves cómo evoluciona la demanda semanal.']],
  ['m11e', 'Bloqueo de caminos', 'Comunidades bloquean el camino y las ventas se detienen por 3 semanas.',
    ['Desvío', 'Coordinas un desvío con el cliente y hablas con la comunidad.'],
    ['Cobrar el atraso', 'Cargas al cliente el costo del bloqueo y se lo explicas con una carta formal.'],
    ['Pagar el paso', 'Pagas peaje y escolta para despachar los 20 pedidos pendientes.'],
    ['Pausar despachos', 'Detienes los despachos y otros resuelven el bloqueo con la comunidad.']],
  ['m11s', 'Comisiones de ventas', 'Tus vendedores cobran 3% sobre la venta, aunque el margen sea bajo.',
    ['Comisión por margen', 'Cambias la base de comisión a margen y fijas un piso de 1% por 6 meses.'],
    ['Metas más altas', 'Subes 15% la meta de ventas de todos y esperas más volumen de inmediato.'],
    ['Comisión de 4%', 'Subes la comisión a 4% para que no se vayan los vendedores más fuertes.'],
    ['Esquema actual', 'Dejas el esquema actual y lo revisas en la negociación anual de metas.']],

  ['m12c', 'Contrato a precio fijo', 'Un cliente ofrece renovar 3 años a precio fijo, sin reajuste por inflación.',
    ['Fijo con tope', 'Aceptas 36 meses y pides un tope de variación atado al costo de insumos.'],
    ['Alza y firma', 'Firmas con un precio inicial 3% más alto, aunque quede sobre el mercado.'],
    ['Firmar como piden', 'Firmas los 3 años tal como los redactó el cliente, con su propio texto.'],
    ['Dejar vencer', 'Pides más tiempo al área legal y la oferta caduca en 30 días.']],
  ['m12p', 'Inventario obsoleto', 'Cierra el año y 5% del inventario parece obsoleto antes de valorarlo.',
    ['Conteo y venta', 'Cuentas el stock, vendes lo recuperable y das de baja el resto.'],
    ['Valor de libro', 'Mantienes el 5% obsoleto a valor de libro y difieres el castigo.'],
    ['Castigar de más', 'Das de baja el 12% de una vez, como pide Auditoría, y absorbes el golpe.'],
    ['Cerrar con sistema', 'Usas las cifras del sistema y no demoras el cierre más de 3 días.']],
  ['m12e', 'Paro de camioneros', 'Un paro de camioneros amenaza los despachos de diciembre, 18% del año.',
    ['Adelantar despachos', 'Adelantas 40% de los despachos y reservas 3 transportistas alternativos.'],
    ['Sobreprecio', 'Cargas 5% a los despachos por el paro y lo explicas después de facturar.'],
    ['Autorizar tarifas', 'Autorizas la tarifa que pida cada transportista para cumplir las fechas.'],
    ['Seguir con el plan', 'Mantienes el plan con los camiones disponibles y los pedidos se acumulan.']],
  ['m12s', 'Cierre del año', 'Falta 1 mes para cerrar y el OI está 1 punto bajo el plan.',
    ['Congelar cargos', 'Congelas 2 cargos vacantes y pausas capacitaciones ajenas a las ventas.'],
    ['Adelantar facturas', 'Adelantas facturación de enero a diciembre y cierras el año en plan.'],
    ['Premiar al equipo', 'Otorgas el bono completo al equipo, aunque el resultado quede lejos.'],
    ['Ver qué sale', 'Cierras el año como viene y analizas la diferencia con el plan después.']],
];

const entries = ROWS.flatMap(([id, title, scene, ...answers]) => [
  [`year.${id}.title`, title],
  [`year.${id}.scene`, scene],
  ...answers.flatMap(([name, desc], i) => [
    [`year.${id}.${ANSWERS[i]}.name`, name],
    [`year.${id}.${ANSWERS[i]}.desc`, desc],
  ]),
]);

module.exports = Object.freeze(Object.fromEntries(entries));
