'use strict';

// Year mode interface, Spanish. Keep the same keys and {placeholders} as year-ui.en.js.

module.exports = Object.freeze({
  // Mode menu
  'menu.title': 'ELIGE EL MODO',
  'menu.year': 'Año completo',
  'menu.year.desc': '12 meses de 4 problemas. Unos 50 min.',
  'menu.half': 'Medio año',
  'menu.half.desc': '6 meses de 4 problemas. Unos 25 min.',
  'menu.tutorial': 'Tutorial de 5 pisos',
  'menu.tutorial.desc': 'Cómo se mueve el P&L. Unos 10 min.',
  'menu.endings': 'Ver los 6 finales',
  'menu.endings.desc': 'Simula un año con un estilo de juego.',
  'menu.best': 'Mejor año: {result}',
  'menu.endings.title': 'ELIGE UN ESTILO DE JUEGO',
  'profile.expert': 'Experto',
  'profile.expert.desc': 'Lee cada situación y equilibra.',
  'profile.careful': 'Cuidadoso',
  'profile.careful.desc': 'Acierta casi siempre, con algún error.',
  'profile.average': 'Regular',
  'profile.average.desc': 'Aciertos y errores a partes iguales.',
  'profile.weak': 'Flojo',
  'profile.weak.desc': 'Más errores que aciertos.',
  'profile.short': 'Siempre el atajo',
  'profile.short.desc': 'OI hoy, la cuenta llega después.',
  'profile.pleaser': 'Siempre ceder',
  'profile.pleaser.desc': 'Todos contentos: crece sin margen.',
  'profile.passive': 'No hacer nada',
  'profile.passive.desc': 'Deja pasar cada problema.',
  'profile.halfShort': 'Atajos a medias',
  'profile.halfShort.desc': 'Equilibra, pero cae en el atajo.',

  // Introduction
  'year.intro1': 'Diriges una unidad que vende higiene y agua a hoteles, hospitales, alimentos e industria. Dura 12 meses y cada mes trae 4 problemas.',
  'year.intro2': 'Tu meta: margen OI (utilidad operacional, plan 15%) y ventas que crezcan. Cuida los medidores Cliente, Planta y Estrategia.',
  'year.intro1.half': 'Diriges una unidad que vende higiene y agua a hoteles, hospitales, alimentos e industria. Dura 6 meses y cada decisión pesa el doble.',
  'year.intro2.half': 'Tu meta: margen OI (utilidad operacional, plan 15%) y ventas que crezcan. Cuida los medidores Cliente, Planta y Estrategia.',
  'year.intro.hint': 'Teclea 4 dígitos para elegir el código.',
  'year.intro.partial': 'Faltan dígitos. Borra con Retroceso.',
  'year.intro3': 'Gana quien equilibra. Un medidor en 0 es un golpe; el OI en 0, un plan de reestructuración. N: reglas.',

  // The four kinds of client
  'year.seg.hotel': 'HOTELES',
  'year.seg.hospital': 'HOSPITALES',
  'year.seg.food': 'ALIMENTOS',
  'year.seg.industry': 'INDUSTRIA',

  // Screen furniture
  'year.stage': 'Mes {m} - {p}/4',
  'year.voice.cliente': 'CLIENTE',
  'year.voice.planta': 'PLANTA',
  'year.voice.entorno': 'ENTORNO',
  'year.voice.estrategia': 'ESTRATEGIA',
  'year.meterTag.C': 'CLI',
  'year.meterTag.P': 'PLA',
  'year.meterTag.E': 'EST',
  'year.meterName.C': 'Cliente',
  'year.meterName.P': 'Planta',
  'year.meterName.E': 'Estrategia',
  'year.crisis.l1': '¡Crisis {tag}!',
  'year.crisis.l2': 'Rinde solo 40%',
  'year.goal': 'Meta: OI {n}%',
  'year.review.on': 'REVISOR',
  'year.tag.smart': 'EQUILIB.',
  'year.tag.temp': 'ATAJO',
  'year.tag.plac': 'CEDER',
  'year.tag.ign': 'PASIVA',
  'ui.btn.rules': 'N reglas',
  'ui.btn.decide': 'Enter: decidir',
  'ui.btn.quit': 'Enter: salir',
  'ui.btn.menu': 'Enter: menú',
  'ui.btn.report': 'Enter: informe',
  'ui.btn.feedback': 'Enter: análisis',
  'year.quit.title': 'SALIR AL MENÚ',
  'year.quit.body': 'Se pierde la partida en curso. ¿Salir?',
  'year.quit.hint': 'N o X: seguir jugando',

  // After an answer
  'year.res.chose': 'Elegiste: {name}',
  'year.note.crisis': 'En crisis: lo equilibrado rinde 40%',
  'year.note.recovery': 'Recuperación: lo equilibrado rinde 5x',
  'year.note.value': 'Valor medido: tu respuesta rinde más',
  'year.note.measured': '¡Valor medido! Ayudará con clientes',
  'year.note.redLine': 'Multa en el SG&A y confianza perdida',

  // Month close
  'year.close.title': 'CIERRE DEL MES {m}',
  'year.close.decay': 'Los tres medidores bajan {decay} por el desgaste del mes.',
  'year.close.drag': '{meter} bajo 42: {line} {pts}',
  'year.close.bonus': '{meter} sobre 70: {line} {pts}',
  'year.close.fly': 'Los tres sobre 60: Ventas {pts}',
  'year.close.bill': 'Llega la cuenta del atajo de {problem}: {meter} {value}',
  'year.close.chart': 'OI % por mes',

  // The blow of a meter at zero
  'year.shock.title': 'GOLPE',
  'year.shock.cause': 'Causa: {cause}',
  'year.shock.body.C': 'Se va tu cliente más grande y con él parte del volumen: el SG&A no se achica.',
  'year.shock.body.P': 'La planta para: pedidos perdidos y gastos de emergencia que no estaban en el plan.',
  'year.shock.body.E': 'El mercado deja de respetar tu precio y debes bajarlo para seguir vendiendo.',
  'year.shock.oi': 'El OI pasa de {from}% a {to}%: el golpe se queda en el P&L.',
  'year.shock.meter': 'El medidor vuelve a {n}. Cada golpe repetido es algo menor.',
  // Restructuring plan (the board's answer to an OI at zero)
  'year.rescue.title': 'CUENTA EN ROJO',
  'year.rescue.cause': 'Causa: {cause}',
  'year.rescue.body1': 'El Gross Profit ya no cubre el SG&A. El directorio aprueba un plan: recorta {sga}% del SG&A y {cost}% del costo.',
  'year.rescue.body2': 'Meta: OI {goal}% antes de fin de año. Bajo 15%, lo equilibrado rinde 5 veces más.',
  'year.rescue.body3': 'Cicatriz: a lo más, un año mediano. Quiebra si el Gross Profit cubre 70% del SG&A o menos dos cierres seguidos.',

  // Verdict
  'year.verdict.excellent': 'AÑO EXCELENTE',
  'year.verdict.good': 'AÑO BUENO',
  'year.verdict.fair': 'AÑO MEDIANO',
  'year.verdict.bad': 'AÑO MALO',
  'year.verdict.terrible': 'AÑO MUY MALO',
  'year.verdict.bankrupt': 'QUIEBRA',
  'year.verdict.oi': 'OI {oi}%',
  'year.verdict.plan': 'plan {plan}%',
  'year.verdict.time': '{time} min',
  'year.kpi.growth': 'Ventas {growth}%',
  'year.kpi.money': 'US${money}M',
  'year.kpi.tag.growthNoMargin': 'Crece sin margen',
  'year.kpi.tag.marginNoGrowth': 'Margen sin crecer',
  'year.walk.title': 'Puente del margen OI (pp)',
  'year.report.title': 'ESTADO DE RESULTADOS',
  'year.report.note': 'Anualizado. Ratios sobre ventas netas. Var.: (paréntesis) = desfavorable.',
  'year.fb.title': 'LO QUE PASÓ',
  'year.walk.plan': 'Plan',
  'year.walk.real': 'Real',
  'year.fb.cause.oi': 'el OI llegó a cero',
  'year.fb.cause.pl': 'el Gross Profit cubrió 70% del SG&A o menos en dos cierres seguidos',
  'year.fb.cause.C': 'el cliente se fue (Cliente en 0)',
  'year.fb.cause.P': 'la planta paró (Planta en 0)',
  'year.fb.cause.E': 'perdiste el mercado (Estrategia en 0)',
  'year.fb.sum.excellent': 'Año excelente: OI {oi}% y el medidor más débil ({meter}) en {value}. Resultado y salud a la vez.',
  'year.fb.sum.good': 'Buen año: OI {oi}%; tu punto más débil fue {meter} ({value}).',
  'year.fb.sum.fair': 'Año mediano: OI {oi}%. Se sostuvo, pero {meter} quedó en {value}, sin margen de error.',
  'year.fb.sum.bad': 'Año malo: OI {oi}%. {meter} terminó en {value} y el negocio quedó frágil.',
  'year.fb.sum.terrible': 'Año muy malo: OI {oi}%. {meter} quedó en {value}: sobreviviste, pero apenas.',
  'year.fb.sum.bankrupt': 'Quiebra en el mes {month}: {cause}.',
  'year.fb.temp': 'Tomaste {n} atajos. El más caro fue el de {problem} (mes {month}): {oiGain} pp de OI hoy y {meter} se resintió.',
  'year.fb.plac': 'Cediste {n} veces: los medidores aguantaron, pero el OI pagó {oiLost} pp.',
  'year.fb.ign': 'No hiciste nada {n} veces: cada una costó OI y dejó caer un medidor.',
  'year.fb.clean': 'Elegiste la respuesta equilibrada {n} de 48 veces: pocos errores y casi sin atajos.',
  'year.fb.mixed': 'Acertaste con lo equilibrado {n} de 48 veces; el resto fueron atajos, cesiones o pasividad.',
  'year.fb.tip.C': 'Para la próxima: cuida al cliente antes de que baje de 42; pasado ese punto todo cuesta más.',
  'year.fb.tip.P': 'Para la próxima: mantén la planta sobre 42; una planta cansada encarece todo.',
  'year.fb.tip.E': 'Para la próxima: protege la estrategia (medir valor, invertir por etapas); sin ella cae el precio.',
  'year.fb.tip.keep': 'Para la próxima: sigue así y vigila el medidor más débil antes de que baje de 42.',
  'year.fb.rescued.yes': 'Te salvó el plan de reestructuración del mes {month}: lograste la meta (OI {oi}%).',
  'year.fb.rescued.no': 'Pasaste por el plan de reestructuración del mes {month} y no llegaste a la meta de OI {goal}%.',
  'year.fb.growth.growthNoMargin': 'Vendiste {growth}% más que el plan y el OI quedó en US$ {money} M: crecer sin margen no es ganar.',
  'year.fb.growth.marginNoGrowth': 'Cuidaste el margen ({oi}%), pero las ventas no crecieron: ¿cuántos clientes dejaste ir por precio?',
  'year.fb.value': 'Mediste el ahorro del cliente en el mes 1: tus respuestas a clientes rindieron más.',
  'year.fb.noValue': 'No mediste el ahorro del cliente: tus respuestas a clientes no tuvieron respaldo.',

  // Game over
  'year.over.restart': 'La partida se reinicia...',
  'year.over.count': 'Nueva partida en {n}',

  // Rules overlay (N)
  'year.rules.title': 'REGLAS DEL AÑO',
  'year.rules.l1': 'OI = utilidad operacional / ventas netas. Plan: 15%. pp = puntos porcentuales.',
  'year.rules.l2': 'Cliente, Planta y Estrategia parten en 60 y bajan casi 2 por mes.',
  'year.rules.l2.half': 'Los medidores parten en 60 y bajan casi 4 por mes: todo pesa el doble.',
  'year.rules.l3': 'Bajo 42 restan OI; sobre 70 suman. Bajo 32: lo equilibrado rinde 40%.',
  'year.rules.l4': 'Un medidor en 0 es un golpe al P&L. OI en 0: plan de reestructuración, una vez, hasta el mes 9.',
  'year.rules.l4.half': 'Un medidor en 0 es un golpe al P&L. OI en 0: plan de reestructuración, una vez, hasta el mes 4.',
  'year.rules.l5': 'Vale la nota menor: la del OI o la del medidor más débil.',
  'year.rules.hNote': 'Nota',
  'year.rules.hOi': 'OI desde',
  'year.rules.hMeter': 'Medidor desde',
  'year.rules.below': 'menos',
  'year.grade.excellent': 'Excelente',
  'year.grade.good': 'Bueno',
  'year.grade.fair': 'Mediano',
  'year.grade.bad': 'Malo',
  'year.grade.terrible': 'Muy malo',
  'year.rules.hint': '< > cambiar de página ({n}/2)',
  'year.assump.title': 'SUPUESTOS DEL MODELO',
  'year.assump.a1': 'Todo es ficticio. US$ millones, anualizado al cierre de cada mes. Plan: ventas netas 100 y OI 15%.',
  'year.assump.a2': 'Ventas - Incentivos = Ventas netas. Menos Costo = M. contribución; menos Flete y Direct Chg = Gross Profit; menos SG&A = OI.',
  'year.assump.a3': 'Ratio = línea / ventas netas. Cada respuesta mueve una o dos líneas; las de crecimiento, precio y volumen.',
  'year.assump.a3.half': 'Ratio = línea / ventas netas. Cada respuesta mueve una o dos líneas; en el medio año, el doble.',
  'year.assump.a4': 'El volumen arrastra costo y servicio: más en un hospital que en un hotel.',
  'year.assump.a5': 'Termina en el OI: caja, deuda, intereses e impuestos quedan fuera. Es un juego, no un pronóstico.',
  'year.assump.a6': 'Quiebra: el Gross Profit cubre 70% del SG&A o menos en dos cierres seguidos.',
});
