'use strict';

// Year mode interface, English. Same keys and {placeholders} as year-ui.es.js.

module.exports = Object.freeze({
  // Mode menu
  'menu.title': 'CHOOSE A MODE',
  'menu.year': 'Full year',
  'menu.year.desc': '12 months of 4 problems. About 50 min.',
  'menu.half': 'Half year',
  'menu.half.desc': '6 months of 4 problems. About 25 min.',
  'menu.tutorial': '5-floor tutorial',
  'menu.tutorial.desc': 'How the P&L moves. About 10 min.',
  'menu.endings': 'See the 6 endings',
  'menu.endings.desc': 'Simulates a year with a play style.',
  'menu.best': 'Best year: {result}',
  'menu.endings.title': 'CHOOSE A PLAY STYLE',
  'profile.expert': 'Expert',
  'profile.expert.desc': 'Reads every situation and balances.',
  'profile.careful': 'Careful',
  'profile.careful.desc': 'Right almost always, a few slips.',
  'profile.average': 'Average',
  'profile.average.desc': 'Hits and misses in equal parts.',
  'profile.weak': 'Weak',
  'profile.weak.desc': 'More misses than hits.',
  'profile.short': 'Always the shortcut',
  'profile.short.desc': 'OI today, the bill comes later.',
  'profile.pleaser': 'Always give in',
  'profile.pleaser.desc': 'Everyone happy: growth, no margin.',
  'profile.passive': 'Do nothing',
  'profile.passive.desc': 'Lets every problem slide.',
  'profile.halfShort': 'Half shortcuts',
  'profile.halfShort.desc': 'Balances, but falls for the shortcut.',

  // Introduction
  'year.intro1': 'You run a unit that sells hygiene and water products to hotels, hospitals, food and industry. It lasts 12 months, 4 problems each.',
  'year.intro2': 'Your goal: the OI margin (operating income / net sales, plan 15%) and sales that grow. Watch the Client, Plant and Strategy meters.',
  'year.intro1.half': 'You run a unit that sells hygiene and water products to hotels, hospitals, food and industry. It lasts 6 months and every decision weighs double.',
  'year.intro2.half': 'Your goal: the OI margin (operating income / net sales, plan 15%) and sales that grow. Watch the Client, Plant and Strategy meters.',
  'year.intro.hint': 'Type 4 digits to choose the code.',
  'year.intro.partial': 'Digits missing. Erase with Backspace.',
  'year.intro3': 'Balance wins. A meter at 0 is a blow; OI at 0 brings a restructuring plan. N: rules.',

  // The four kinds of client
  'year.seg.hotel': 'HOTELS',
  'year.seg.hospital': 'HOSPITALS',
  'year.seg.food': 'FOOD',
  'year.seg.industry': 'INDUSTRY',

  // Screen furniture
  'year.stage': 'Month {m} - {p}/4',
  'year.voice.cliente': 'CLIENT',
  'year.voice.planta': 'PLANT',
  'year.voice.entorno': 'ENVIRON.',
  'year.voice.estrategia': 'STRATEGY',
  'year.meterTag.C': 'CLI',
  'year.meterTag.P': 'PLT',
  'year.meterTag.E': 'STR',
  'year.meterName.C': 'Client',
  'year.meterName.P': 'Plant',
  'year.meterName.E': 'Strategy',
  'year.crisis.l1': 'Crisis {tag}!',
  'year.crisis.l2': 'Pays only 40%',
  'year.goal': 'Goal: OI {n}%',
  'year.review.on': 'REVIEWER',
  'year.tag.smart': 'BALANCED',
  'year.tag.temp': 'SHORTCUT',
  'year.tag.plac': 'GIVE IN',
  'year.tag.ign': 'PASSIVE',
  'ui.btn.rules': 'N rules',
  'ui.btn.decide': 'Enter: decide',
  'ui.btn.quit': 'Enter: leave',
  'ui.btn.menu': 'Enter: menu',
  'ui.btn.report': 'Enter: report',
  'ui.btn.feedback': 'Enter: feedback',
  'year.quit.title': 'LEAVE TO MENU',
  'year.quit.body': 'You will lose the game in progress. Leave?',
  'year.quit.hint': 'N or X: keep playing',

  // After an answer
  'year.res.chose': 'You chose: {name}',
  'year.note.crisis': 'In crisis: balanced pays only 40%',
  'year.note.recovery': 'Recovery: balanced pays 5x',
  'year.note.value': 'Value measured: your answer pays more',
  'year.note.measured': 'Value measured: clients will pay more',
  'year.note.redLine': 'A fine in the SG&A and lost trust',

  // Month close
  'year.close.title': 'MONTH {m} CLOSE',
  'year.close.decay': 'All three meters drop {decay} from the month\'s wear.',
  'year.close.drag': '{meter} below 42: {line} {pts}',
  'year.close.bonus': '{meter} above 70: {line} {pts}',
  'year.close.fly': 'All three above 60: Sales {pts}',
  'year.close.bill': 'The bill for the {problem} shortcut arrives: {meter} {value}',
  'year.close.chart': 'OI % monthly',

  // Rescue plan
  // The blow of a meter at zero
  'year.shock.title': 'BLOW',
  'year.shock.cause': 'Cause: {cause}',
  'year.shock.body.C': 'Your biggest client leaves and takes part of the volume with him: the SG&A does not shrink.',
  'year.shock.body.P': 'The plant stops: lost orders and emergency costs that were not in the plan.',
  'year.shock.body.E': 'The market stops respecting your price and you must lower it to keep selling.',
  'year.shock.oi': 'OI goes from {from}% to {to}%: the blow stays in the P&L.',
  'year.shock.meter': 'The meter restarts at {n}. Every repeated blow is a bit smaller.',
  'year.rescue.title': 'IN THE RED',
  'year.rescue.cause': 'Cause: {cause}',
  'year.rescue.body1': 'The Gross Profit no longer covers the SG&A. The board approves a plan: it cuts {sga}% of the SG&A and {cost}% of the cost.',
  'year.rescue.body2': 'Goal: OI {goal}% before year-end. Below 15%, balanced answers earn 5x more.',
  'year.rescue.body3': 'It leaves a scar: a fair year at best. Bankruptcy if Gross Profit covers only 70% of the SG&A at two closes in a row.',

  // Verdict
  'year.verdict.excellent': 'EXCELLENT YEAR',
  'year.verdict.good': 'GOOD YEAR',
  'year.verdict.fair': 'FAIR YEAR',
  'year.verdict.bad': 'BAD YEAR',
  'year.verdict.terrible': 'TERRIBLE YEAR',
  'year.verdict.bankrupt': 'BANKRUPT',
  'year.verdict.oi': 'OI {oi}%',
  'year.verdict.plan': 'plan {plan}%',
  'year.verdict.time': '{time} min',
  'year.kpi.growth': 'Sales {growth}%',
  'year.kpi.money': 'US${money}M',
  'year.kpi.tag.growthNoMargin': 'Growth, no margin',
  'year.kpi.tag.marginNoGrowth': 'Margin, no growth',
  'year.walk.title': 'OI margin bridge (pp)',
  'year.report.title': 'INCOME STATEMENT',
  'year.report.note': 'Annualized. Ratios on net sales. Var.: (brackets) = unfavorable.',
  'year.fb.title': 'WHAT HAPPENED',
  'year.walk.plan': 'Plan',
  'year.walk.real': 'Real',
  'year.fb.cause.oi': 'OI reached zero',
  'year.fb.cause.pl': 'the Gross Profit covered 70% of the SG&A or less at two closes in a row',
  'year.fb.cause.C': 'the client left (Client at 0)',
  'year.fb.cause.P': 'the plant stopped (Plant at 0)',
  'year.fb.cause.E': 'you lost the market (Strategy at 0)',
  'year.fb.sum.excellent': 'Excellent year: OI {oi}% and the weakest meter ({meter}) at {value}. Result and health together.',
  'year.fb.sum.good': 'Good year: OI {oi}%; your weakest spot was {meter} ({value}).',
  'year.fb.sum.fair': 'Fair year: OI {oi}%. It held, but {meter} ended at {value}, with no room for error.',
  'year.fb.sum.bad': 'Bad year: OI {oi}%. {meter} ended at {value} and the business is fragile.',
  'year.fb.sum.terrible': 'Terrible year: OI {oi}%. {meter} ended at {value}: you survived, barely.',
  'year.fb.sum.bankrupt': 'Bankruptcy in month {month}: {cause}.',
  'year.fb.temp': 'You took {n} shortcuts. Costliest: {problem} (month {month}): {oiGain} pp of OI now, {meter} suffered.',
  'year.fb.plac': 'You gave in {n} times: the meters held, but OI paid {oiLost} pp.',
  'year.fb.ign': 'You did nothing {n} times: each one cost OI and let a meter fall.',
  'year.fb.clean': 'You chose the balanced answer {n} of 48 times: few mistakes and almost no shortcuts.',
  'year.fb.mixed': 'You got the balanced answer right {n} of 48 times; the rest were shortcuts, giving in or passivity.',
  'year.fb.tip.C': 'Next time: look after the client before it drops below 42; past that point everything costs more.',
  'year.fb.tip.P': 'Next time: keep the plant above 42; a tired plant makes everything dearer.',
  'year.fb.tip.E': 'Next time: protect strategy (measure value, invest in stages); without it price erodes.',
  'year.fb.tip.keep': 'Next time: keep it up and watch the weakest meter before it drops below 42.',
  'year.fb.rescued.yes': 'The month {month} restructuring plan saved you: you hit the goal (OI {oi}%).',
  'year.fb.rescued.no': 'You went through the month {month} restructuring plan and missed the OI {goal}% goal.',
  'year.fb.growth.growthNoMargin': 'You sold {growth}% above plan and OI ended at US$ {money} M: growth without margin is not profit.',
  'year.fb.growth.marginNoGrowth': 'You held the margin ({oi}%) but sales did not grow: how many clients did you lose over price?',
  'year.fb.value': 'You measured the client\'s savings in month 1: your answers to clients paid off more.',
  'year.fb.noValue': 'You did not measure the client\'s savings: your answers to clients had no backing.',

  // Game over
  'year.over.restart': 'The game restarts...',
  'year.over.count': 'New game in {n}',

  // Rules overlay (N)
  'year.rules.title': 'RULES OF THE YEAR',
  'year.rules.l1': 'OI = operating income / net sales. Plan: 15%. pp = percentage points.',
  'year.rules.l2': 'Client, Plant and Strategy start at 60 and drop almost 2 a month.',
  'year.rules.l2.half': 'Client, Plant and Strategy start at 60 and drop almost 4 a month: every decision weighs twice as much.',
  'year.rules.l3': 'Below 42 they cost OI, above 70 they add. Below 32 balance pays only 40%.',
  'year.rules.l4': 'A meter at 0 is a blow to the P&L. OI at 0: restructuring plan, once, up to month 9.',
  'year.rules.l4.half': 'A meter at 0 is a blow to the P&L. OI at 0: restructuring plan, once, up to month 4.',
  'year.rules.l5': 'The result is the lower of the OI grade and the weakest-meter grade.',
  'year.rules.hNote': 'Grade',
  'year.rules.hOi': 'OI from',
  'year.rules.hMeter': 'Meter from',
  'year.rules.below': 'lower',
  'year.grade.excellent': 'Excellent',
  'year.grade.good': 'Good',
  'year.grade.fair': 'Fair',
  'year.grade.bad': 'Bad',
  'year.grade.terrible': 'Terrible',
  'year.rules.hint': '< > switch page ({n}/2)',
  'year.assump.title': 'MODEL ASSUMPTIONS',
  'year.assump.a1': 'Everything is fictional. US$ millions, annualized at each month close. Plan: net sales 100, OI 15%.',
  'year.assump.a2': 'Sales - Incentives = Net sales. Less Cost = Contribution margin; less Freight and Direct Chg = Gross Profit; less SG&A = OI.',
  'year.assump.a3': 'Ratio = line / net sales. Each answer moves one or two lines; growth answers use price and volume.',
  'year.assump.a3.half': 'Ratio = line / net sales. Each answer moves one or two lines; in the half year, twice as much.',
  'year.assump.a4': 'Volume drags cost and service: more in a hospital than in a hotel.',
  'year.assump.a5': 'The game ends at OI: cash, debt, interest and taxes are left out. A game, not a forecast.',
  'year.assump.a6': 'Bankruptcy: Gross Profit covers 70% of the SG&A or less at two closes in a row.',
});
