'use strict';

// Year mode, Spanish. One row per problem:
//   [id, title, scene, [smart name, desc], [temp name, desc], [plac name, desc], [ign name, desc]]
// The four answers are always written in that order; the game shuffles what the player sees.

const ANSWERS = ['smart', 'temp', 'plac', 'ign'];

const ROWS = [
  ['m01c', 'Renovación anual', 'La minera exige 3% de rebate y pago a 90 días para renovar.',
    ['Contrato a 2 años', 'Rebate de 1% y pago a 60 días, atado a un ahorro que medimos juntos.'],
    ['Aceptar y compensar', 'Aceptas todo y subes el precio de otros productos sin avisar.'],
    ['Dar todo lo pedido', 'Rebate 3% y 90 días: el cliente sale feliz y tú pagas el margen.'],
    ['Esperar su decisión', 'No respondes hasta que ellos decidan; el contrato queda en el aire.']],
  ['m01p', 'Inventario bajo', 'Arranca el año con poco stock de insumos clave y pedidos grandes.',
    ['Compra escalonada', 'Compras en dos lotes y avisas a Comercial qué pedidos son seguros.'],
    ['Producir al límite', 'Exiges el máximo a la planta con insumos justos para ahorrar stock.'],
    ['Comprar todo ya', 'Compras el inventario completo hoy: sin riesgo, pero a precio spot.'],
    ['Ver cómo evoluciona', 'No haces nada hasta que falte algo: ya se verá.']],
  ['m01e', 'Presupuesto y dólar', 'El dólar está volátil y el presupuesto se fijó con un solo tipo de cambio.',
    ['Reajuste por dólar', 'Pactas reajuste por dólar con clientes y compras insumo a plazo.'],
    ['Subir precios ya', 'Subes todos los precios 3% hoy, aunque el contrato no lo permita.'],
    ['Absorber el golpe', 'No tocas precios ni costos: el margen absorbe la volatilidad.'],
    ['Esperar al cierre', 'Lo dejas para el cierre del trimestre y ves qué pasa.']],
  ['m01s', 'Medir o empujar', 'Corporativo quiere más volumen; tú podrías medir el ahorro de tus clientes.',
    ['Medir el ahorro', 'Documentas el ahorro de agua y reactivos del cliente para negociarlo después.'],
    ['Empujar volumen', 'Vendes más con descuento hoy; el ahorro del cliente queda sin medir.'],
    ['Plan de corporativo', 'Aplicas el plan de corporativo tal cual, sin cuestionarlo.'],
    ['Dejar para después', 'Postergas ambas ideas: el año ya está andando.']],

  ['m02c', 'Cambio de especificación', 'El cliente pide otra especificación con solo 2 semanas de aviso.',
    ['Piloto y cronograma', 'Haces una prueba corta y acuerdas fechas realistas con el cliente.'],
    ['Cambiar sin pruebas', 'Cambias la fórmula con lo que hay en bodega para cumplir la fecha.'],
    ['Decir que sí a todo', 'Aceptas el plazo y la especificación, y asumes el costo extra.'],
    ['Responder más tarde', 'Dejas el pedido sin respuesta y el cliente sigue esperando.']],
  ['m02p', 'Mantención vs pedidos', 'Toca la mantención mayor de la línea, pero hay pedidos urgentes.',
    ['Mantención parcial', 'Paras media línea por turnos y repartes los pedidos urgentes.'],
    ['Aplazar mantención', 'Cumples todos los pedidos ahora y dejas la mantención para después.'],
    ['Parar la planta', 'Detienes toda la línea 3 días: planta perfecta, pedidos esperando.'],
    ['Seguir como está', 'No decides: la mantención se atrasa y los pedidos salen como pueden.']],
  ['m02e', 'Lluvias altiplánicas', 'Las lluvias cortan el camino a la faena y hay despachos pendientes.',
    ['Ruta alterna', 'Usas una ruta más larga, avisas al cliente y priorizas lo crítico.'],
    ['Despachar igual', 'Mandas los camiones por el camino riesgoso para cumplir la fecha.'],
    ['Flete aéreo a todo', 'Envías todo por vía urgente: el cliente no espera, tú pagas el flete.'],
    ['Esperar que pase', 'Detienes los despachos hasta que el camino abra.']],
  ['m02s', 'Pronóstico agresivo', 'Corporativo pide subir 8% el pronóstico del año para la reunión.',
    ['Pronóstico en rango', 'Entregas un caso base y uno optimista, con los supuestos claros.'],
    ['Inflar el número', 'Subes el número para quedar bien hoy; ya se verá después.'],
    ['Aceptar lo pedido', 'Aceptas el 8% y comprometes al equipo sin discutir los supuestos.'],
    ['No responder', 'Postergas el pronóstico hasta que corporativo insista.']],

  ['m03c', 'Lote fuera de norma', 'El cliente reclama un lote que salió fuera de especificación.',
    ['Asumir y reponer', 'Reconoces el error, repones el lote y compartes el análisis de causa.'],
    ['Culpar al flete', 'Dices que el daño fue del transporte para no pagar la reposición.'],
    ['Descuento grande', 'Ofreces 10% de descuento en el próximo pedido sin investigar.'],
    ['Esperar el reclamo', 'No respondes hasta que el reclamo llegue de forma oficial.']],
  ['m03p', 'Falla y materia prima', 'Falla una bomba de la línea y falta una materia prima clave.',
    ['Priorizar pedidos', 'Ordenas los pedidos por criticidad y compras la bomba a un proveedor local.'],
    ['Reparar con parche', 'Haces una reparación provisoria y sigues produciendo para no parar.'],
    ['Pagar por urgencia', 'Compras todo por vía urgente y a cualquier precio para no atrasarte.'],
    ['Esperar repuestos', 'No haces nada hasta que el proveedor aparezca con repuestos.']],
  ['m03e', 'Reforma tributaria', 'Se anuncia una reforma tributaria minera y los clientes se ponen cautelosos.',
    ['Ver escenarios', 'Conversas con cada cliente sus escenarios de compra y ajustas el plan.'],
    ['Adelantar ventas', 'Empujas a los clientes a comprar hoy con descuentos antes de la reforma.'],
    ['Congelar precios', 'Congelas los precios del año para tranquilizar a todos los clientes.'],
    ['Esperar a ver', 'No haces nada hasta que la reforma se apruebe.']],
  ['m03s', 'Producto de agua', 'Hay una oportunidad: un programa de ahorro de agua para las mineras.',
    ['Piloto acotado', 'Lo pruebas con un cliente amigo y mides resultados antes de escalar.'],
    ['Lanzar sin probar', 'Lo ofreces a todos desde ya para vender más este año.'],
    ['Esperar aprobación', 'No avanzas hasta que corporativo apruebe todo el presupuesto.'],
    ['Dejarlo pasar', 'Priorizas lo de siempre y el programa queda en un cajón.']],

  ['m04c', 'Recorte de presupuesto', 'El cliente recorta su presupuesto de insumos y pide bajar los precios.',
    ['Bajar su consumo', 'Ajustas la dosis con el cliente para bajar su costo sin bajar tu precio.'],
    ['Alzas escondidas', 'Bajas el precio del producto principal y subes el de los servicios.'],
    ['Bajar el precio', 'Rebajas 5% a todo el contrato para que el cliente no se vaya.'],
    ['Mantener la oferta', 'No cambias nada y esperas que el cliente se acostumbre.']],
  ['m04p', 'Rotación de operadores', 'Se van dos operadores clave y los turnos quedan incompletos.',
    ['Plan de relevo', 'Capacitas a dos jóvenes y reorganizas los turnos mientras tanto.'],
    ['Horas extra', 'Pides turnos dobles al equipo que queda para no contratar.'],
    ['Subir sueldos', 'Subes el sueldo de todo el turno para que nadie más se vaya.'],
    ['Dejar los cupos', 'No reemplazas a nadie y confías en que los turnos se arreglen solos.']],
  ['m04e', 'Royalty minero', 'Se aprueba un royalty más alto y las mineras revisan todos los contratos.',
    ['Contratos por valor', 'Propones contratos atados al ahorro que generas, no al volumen.'],
    ['Apretar a cautivos', 'Subes precios a los clientes que no tienen otro proveedor.'],
    ['Ofrecer descuentos', 'Das descuentos preventivos a todos antes de que los pidan.'],
    ['Esperar la revisión', 'No te mueves hasta que cada minera pida renegociar.']],
  ['m04s', 'Recorte de SG&A', 'Corporativo pide bajar el SG&A 5% de inmediato.',
    ['Recorte selectivo', 'Recortas gastos que no tocan al cliente y proteges visitas y medición.'],
    ['Recorte parejo', 'Bajas todo 5% parejo, incluso lo que sostiene el servicio.'],
    ['Pedir excepción', 'Argumentas que no se puede y pides postergar el recorte al próximo año.'],
    ['No ejecutar', 'Dejas la orden en pausa y sigues gastando como siempre.']],

  ['m05c', 'Visitas sin costo', 'El cliente pide visitas semanales de servicio sin pagar más.',
    ['Visitas por demanda', 'Ofreces monitoreo remoto y visitas solo cuando el dato las pide.'],
    ['Mandar a un junior', 'Dices que sí, pero mandas a un técnico junior sin experiencia.'],
    ['Todas las visitas', 'Aceptas visitas semanales completas y asumes el costo del servicio.'],
    ['No contestar', 'No respondes y el cliente se queja con tu jefe.']],
  ['m05p', 'Incidente de seguridad', 'Hay un incidente sin heridos en la planta y viene una auditoría.',
    ['Investigar', 'Detienes la zona, buscas la causa y corriges el procedimiento.'],
    ['Cerrar rápido', 'Cierras el informe sin cambios para no perder producción.'],
    ['Detener todo', 'Paras la planta una semana para revisar todo desde cero.'],
    ['Dejarlo pasar', 'Como no hubo heridos, sigues trabajando igual.']],
  ['m05e', 'Cae el cobre', 'Baja el precio del cobre y las mineras frenan las compras no esenciales.',
    ['Bajar su costo', 'Ofreces un programa que baja el costo por tonelada de tu cliente.'],
    ['Cobrar más al resto', 'Subes tus precios a los clientes que siguen comprando.'],
    ['Alargar sus plazos', 'Das más plazo de pago a todos para ayudarlos a pasar el ciclo.'],
    ['Esperar el rebote', 'No cambias nada y esperas que el cobre vuelva a subir.']],
  ['m05s', 'Monitoreo remoto', 'Puedes invertir en monitoreo remoto para varias faenas.',
    ['Invertir por etapas', 'Instalas en las dos faenas más grandes y mides el ahorro en visitas.'],
    ['Cancelar inversión', 'Cancelas la inversión y recortas visitas para subir el margen.'],
    ['Invertir en todas', 'Instalas en todas las faenas a la vez, aunque no esté probado.'],
    ['Pensarlo más', 'Sigues evaluando sin decidir y las visitas siguen costando igual.']],

  ['m06c', 'Competidor 8% menor', 'Un competidor ofrece 8% menos y amenaza con quitarte el contrato.',
    ['Mostrar el ahorro', 'Presentas el ahorro medido y propones un contrato a 2 años.'],
    ['Subir la barrera', 'Amarras al cliente con un contrato largo y multas de salida.'],
    ['Igualar el precio', 'Bajas 8% y mantienes todo igual para no perder el contrato.'],
    ['Confiar y esperar', 'No haces nada: das por hecho que te serán leales por años.']],
  ['m06p', 'Deriva de calidad', 'Varios lotes salen al límite de la especificación esta semana.',
    ['Ajustar el proceso', 'Ajustas el proceso con el equipo y refuerzas los controles.'],
    ['Mezclar lotes', 'Mezclas lotes buenos con dudosos para que el promedio pase.'],
    ['Más controles', 'Agregas controles a cada lote: lento y caro.'],
    ['Mirar después', 'Esperas a ver si algún cliente reclama.']],
  ['m06e', 'Norma de agua', 'Una nueva norma ambiental limita el uso de agua en las faenas.',
    ['Programa de ahorro', 'Propones un programa de reuso de agua que ayuda al cliente a cumplir.'],
    ['Vender cumplimiento', 'Ofreces un paquete llave en mano a precio alto, sin probarlo.'],
    ['Diagnóstico gratis', 'Haces diagnósticos gratis a todos para ganarte su confianza.'],
    ['Que lo vean ellos', 'Esperas que cada cliente pida ayuda por su cuenta.']],
  ['m06s', 'Nuevo país', 'Aparece un cliente grande en otro país, con requisitos nuevos.',
    ['Entrar con socio', 'Entras con un distribuidor local y limitas la inversión inicial.'],
    ['Entrar rápido', 'Atiendes desde aquí con precios altos y sin presencia local.'],
    ['Lo que pidan', 'Aceptas todos sus requisitos y contratos desde el primer día.'],
    ['No responder', 'No contestas la consulta y el cliente se va con otro.']],

  ['m07c', 'Auditoría de costos', 'El cliente pide auditar tus costos para revisar tu margen.',
    ['Abrir con reglas', 'Muestras tus costos de servicio y acuerdan cómo se comparan.'],
    ['Mostrar a medias', 'Entregas solo la parte que te conviene y escondes el resto.'],
    ['Abrir todo', 'Entregas todos tus costos y aceptas bajar tu margen.'],
    ['Postergar auditoría', 'Respondes que ahora no puedes y lo dejas pasar.']],
  ['m07p', 'Proveedor atrasado', 'Tu proveedor único se atrasa 3 semanas con un insumo crítico.',
    ['Segundo proveedor', 'Calificas un segundo proveedor y usas stock para cubrir el hueco.'],
    ['Cambiar el insumo', 'Cambias a un insumo más barato sin avisar al cliente.'],
    ['Flete aéreo', 'Traes el insumo en avión a cualquier precio.'],
    ['Esperar y ver', 'No hay plan B: esperas que el proveedor cumpla.']],
  ['m07e', 'Temporal de nieve', 'Un temporal de nieve cierra el paso a las faenas por una semana.',
    ['Stock en la faena', 'Adelantas stock a la bodega del cliente y reprogramas los despachos.'],
    ['Mandar igual', 'Envías camiones en la ventana de calma aunque sea riesgoso.'],
    ['Helicóptero', 'Cubres lo crítico con envíos aéreos muy caros.'],
    ['Esperar el deshielo', 'Detienes todo y esperas que se abra el paso.']],
  ['m07s', 'Reorganización', 'Corporativo propone reorganizar el equipo y bajar la dotación 10%.',
    ['Rediseñar roles', 'Reasignas funciones y automatizas tareas antes de bajar gente.'],
    ['Recorte total', 'Bajas 10% parejo y supones que el servicio se las arregla.'],
    ['Mantener a todos', 'Mantienes la dotación y pides tiempo para mejorar.'],
    ['No decidir', 'Dejas la reorganización sin responsable ni fecha.']],

  ['m08c', 'Nuevo comprador', 'Llega un nuevo jefe de compras que quiere licitar todo.',
    ['Reunión de valor', 'Presentas resultados medidos y propones una mejora conjunta.'],
    ['Pago por adelantado', 'Pides pago por adelantado para reducir tu riesgo.'],
    ['Licitar al mínimo', 'Entras a la licitación con el precio más bajo posible.'],
    ['Esperar licitación', 'No haces nada hasta que llegue la invitación.']],
  ['m08p', 'Capacidad al límite', 'La demanda supera la capacidad de la planta por tres meses.',
    ['Turno adicional', 'Agregas un turno planificado y priorizas por margen.'],
    ['Producción continua', 'Operas sin pausas de mantención para sacar más.'],
    ['Aceptar todo', 'Aceptas todos los pedidos aunque lleguen tarde.'],
    ['Ver qué pasa', 'No cambias nada y los pedidos se acumulan.']],
  ['m08e', 'Sube el dólar', 'El dólar sube 10% y tu costo de insumos importados también.',
    ['Traspaso gradual', 'Traspasas parte del alza con aviso y compras a plazo el resto.'],
    ['Subir todo ya', 'Subes los precios 10% a todos sin avisar.'],
    ['Absorber el alza', 'Mantienes los precios y absorbes todo el aumento.'],
    ['Mirar el dólar', 'Esperas a ver si el dólar baja solo.']],
  ['m08s', 'Alianza con distribuidor', 'Un distribuidor ofrece atender a los clientes pequeños por una comisión.',
    ['Piloto de 6 meses', 'Pruebas con 10 clientes pequeños y mides servicio y margen.'],
    ['Cederles todo', 'Entregas todos los clientes pequeños para bajar tus costos.'],
    ['Aceptar la comisión', 'Aceptas la comisión que piden sin negociar.'],
    ['Rechazar la oferta', 'Dices que no sin mirar los números.']],

  ['m09c', 'Plazo de 120 días', 'El cliente pide 120 días de pago y tu caja está justa.',
    ['Plazo con descuento', 'Ofreces 90 días con un pequeño descuento por pronto pago.'],
    ['Subir el precio', 'Aceptas los 120 días y subes el precio para cubrir el costo.'],
    ['Dar los 120 días', 'Aceptas el plazo pedido sin condiciones.'],
    ['No responder', 'No respondes y el pedido queda en pausa.']],
  ['m09p', 'Auditoría regulatoria', 'Llega una auditoría regulatoria con foco en tu almacenamiento.',
    ['Preparar a tiempo', 'Preparas los documentos y corriges lo menor antes de la visita.'],
    ['Maquillar bodega', 'Ordenas solo lo que se ve para pasar la auditoría.'],
    ['Rehacer todo', 'Detienes todo para rehacer la bodega por completo.'],
    ['Confiar en suerte', 'No preparas nada: siempre sale bien.']],
  ['m09e', 'Elecciones', 'Vienen elecciones y los clientes frenan inversiones por la incertidumbre.',
    ['Contratos flexibles', 'Ofreces contratos con salidas claras para dar tranquilidad.'],
    ['Presionar cierres', 'Presionas a los clientes a firmar ahora con descuentos fuertes.'],
    ['Ir a su ritmo', 'Aceptas cualquier plazo que pidan sin proponer nada.'],
    ['Esperar la elección', 'Dejas todo en pausa hasta el resultado.']],
  ['m09s', 'Comprar al proveedor', 'Puedes comprar a tu proveedor clave para asegurar los insumos.',
    ['Contrato a 3 años', 'Negocias suministro y precio por 3 años sin comprar la empresa.'],
    ['Comprar con deuda', 'Compras con deuda para bajar costos rápido.'],
    ['No comprar nada', 'Evitas el riesgo y sigues con un proveedor único.'],
    ['Seguir evaluando', 'Postergas una decisión que ya lleva un año.']],

  ['m10c', 'Consignación', 'El cliente pide inventario en consignación dentro de su faena.',
    ['Consignar un tope', 'Aceptas un volumen acotado con reposición e informes mensuales.'],
    ['Cobrar al entrar', 'Facturas el inventario apenas llega y dejas el riesgo al cliente.'],
    ['Consignar todo', 'Dejas todo el inventario que pidan, sin control.'],
    ['Rechazar', 'Dices que no se puede y no ofreces otra opción.']],
  ['m10p', 'Paro parcial', 'El sindicato anuncia un paro parcial por el bono del año.',
    ['Negociar con datos', 'Muestras el resultado real y acuerdas un bono atado a metas.'],
    ['Traer reemplazos', 'Contratas reemplazos temporales para quebrar el paro.'],
    ['Pagar el bono', 'Pagas el bono completo que piden para evitar el paro.'],
    ['Esperar el paro', 'No respondes y dejas que el paro avance.']],
  ['m10e', 'Sequía', 'Una sequía obliga a la minera a reducir su consumo de agua.',
    ['Programa de agua', 'Propones un programa de reuso con ahorro medido y pago por resultado.'],
    ['Cobrar la urgencia', 'Subes los precios aprovechando la urgencia del cliente.'],
    ['Regalar programa', 'Entregas el programa gratis para ganarte su confianza.'],
    ['No es lo nuestro', 'Dices que es un tema del cliente y no ofreces ayuda.']],
  ['m10s', 'Presupuesto del año', 'Corporativo pide el presupuesto del próximo año con alto crecimiento.',
    ['Presupuesto real', 'Presentas el crecimiento con las palancas concretas que lo sostienen.'],
    ['Inflar el plan', 'Entregas el crecimiento pedido sin respaldo.'],
    ['Plan conservador', 'Presentas un presupuesto bajo para quedar tranquilo.'],
    ['Copiar el anterior', 'Repites el presupuesto del año pasado con ajuste de inflación.']],

  ['m11c', 'Pagos atrasados', 'El cliente atrasa pagos por caja y pide seguir comprando.',
    ['Plan de pagos', 'Acuerdan un calendario de pagos y limitas el crédito mientras tanto.'],
    ['Cortar despachos', 'Cortas los despachos de inmediato sin hablar con el cliente.'],
    ['Seguir despachando', 'Despachas igual y esperas que algún día paguen.'],
    ['No cobrar', 'No haces seguimiento y la deuda crece.']],
  ['m11p', 'Turnos de fin de año', 'Llega fin de año con pedidos altos y gente que quiere vacaciones.',
    ['Turnos rotativos', 'Armas turnos rotativos con permisos justos y un bono pequeño.'],
    ['Cancelar vacaciones', 'Cancelas todas las vacaciones para cumplir los pedidos.'],
    ['Dar las vacaciones', 'Das todos los permisos pedidos y aceptas atrasos.'],
    ['Sin plan', 'No planificas y los turnos se arman sobre la marcha.']],
  ['m11e', 'Bloqueo de caminos', 'Comunidades bloquean el camino y las ventas se paran tres semanas.',
    ['Plan con el cliente', 'Coordinas con el cliente rutas, horarios y una mesa con la comunidad.'],
    ['Cobrar el atraso', 'Le cobras al cliente los costos del bloqueo sin conversarlo antes.'],
    ['Pagar por pasar', 'Pagas por paso y escolta para cumplir cada pedido.'],
    ['Esperar el diálogo', 'Detienes todo hasta que otros resuelvan el conflicto.']],
  ['m11s', 'Contrato grande afuera', 'Ofrecen un contrato grande en otro país, pero tu planta está al límite.',
    ['Entrega por etapas', 'Aceptas con entregas por etapas y una ampliación pactada.'],
    ['Prometer todo', 'Aceptas todo el volumen y ves cómo lo cumples.'],
    ['Rechazar contrato', 'Dices que no para proteger a los clientes actuales.'],
    ['Sin respuesta', 'Dejas la oferta sin contestar hasta enero.']],

  ['m12c', 'Contrato a precio fijo', 'El cliente ofrece 3 años de contrato a precio fijo, sin reajuste.',
    ['Fijo con reajuste', 'Aceptas el plazo con un reajuste mínimo atado a los costos.'],
    ['Subir y firmar', 'Subes el precio base antes de firmar el contrato fijo.'],
    ['Firmar tal cual', 'Firmas el contrato fijo exactamente como lo pide el cliente.'],
    ['No tomar postura', 'Dejas la oferta sin respuesta y vence.']],
  ['m12p', 'Cierre de inventario', 'Cierra el año: debes decidir cómo valorar y cerrar el inventario.',
    ['Conteo y ajuste', 'Haces el conteo físico y das de baja lo que no existe.'],
    ['Aplazar ajustes', 'Dejas los ajustes malos para el próximo año.'],
    ['Castigar todo', 'Das de baja todo lo dudoso de una vez, aunque sea de más.'],
    ['Cerrar sin contar', 'Cierras con los números del sistema, sin revisar.']],
  ['m12e', 'Paro de camioneros', 'Un paro de camioneros amenaza los despachos de diciembre.',
    ['Adelantar despachos', 'Adelantas despachos y coordinas rutas con otros transportistas.'],
    ['Cobrar recargo', 'Cobras recargos altos a los clientes sin avisar.'],
    ['Pagar lo que pidan', 'Aceptas el costo de cualquier transportista disponible.'],
    ['Esperar el paro', 'No haces nada y los pedidos se acumulan.']],
  ['m12s', 'Cierre del año', 'Falta poco para el cierre: ¿empujar números o cerrar limpio?',
    ['Cerrar limpio', 'Cierras con los números reales y presentas un plan claro para enero.'],
    ['Maquillar el cierre', 'Adelantas facturas y difieres gastos para llegar al número.'],
    ['Bajar la meta', 'Pides bajar la meta para llegar cómodo.'],
    ['Ver qué sale', 'No haces nada especial y miras el resultado.']],
];

const entries = ROWS.flatMap(([id, title, scene, ...answers]) => [
  [`year.${id}.title`, title],
  [`year.${id}.scene`, scene],
  ...answers.flatMap(([name, desc], i) => [
    [`year.${id}.${ANSWERS[i]}.name`, name],
    [`year.${id}.${ANSWERS[i]}.desc`, desc],
  ]),
]);

module.exports = Object.freeze(Object.fromEntries(entries));
